### PR TITLE
Fix crash when calling `mbedtls_ssl_cache_free` twice

### LINKED ISSUE #1104: Crash when calling mbedtls_ssl_cache_free twice
When using the cache i have a crash when calling mbedtls_ssl_cache_free more than one time. This happens because **cache->chain** is deleted on the first call and not set to NULL so the second call will try to free it up again.

This can be fixed by adding a simple memset at the end of mbedtls_ssl_cache_free
`memset( cache, 0, sizeof( mbedtls_ssl_cache_context ) );`

- Type: Bug
- Priority: Minor

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Set `cache` to zero at the end of `mbedtls_ssl_cache_free` 
fixes #1104

## Status
**READY**

## Requires Backporting

Yes 
Which branch?
mbedtls-2.1
mbedtls-1.3

## Steps to test or reproduce
call ``mbedtls_ssl_cache_free` when session has been set to the chain

### CODE REVIEW

File: library/ssl_cache.c [hunk 1]
```diff
@@ -43,6 +43,11 @@
 
 #include <string.h>
 
+/* Implementation that should never be optimized out by the compiler */
+static void mbedtls_zeroize( void *v, size_t n ) {
```
Comment (yanesca) [inline library/ssl_cache.c]: I don't think that this is necessary, because if you use `cache->chain` later, then the compiler can't optimise it out and it really doesn't matter otherwise.

File: library/ssl_cache.c [hunk 2]
```diff
@@ -321,6 +326,8 @@ void mbedtls_ssl_cache_free( mbedtls_ssl_cache_context *cache )
 #if defined(MBEDTLS_THREADING_C)
     mbedtls_mutex_free( &cache->mutex );
 #endif
+
+    mbedtls_zeroize( cache, sizeof(mbedtls_ssl_cache_context) );
```
Comment (yanesca) [inline library/ssl_cache.c]: This line does the job, but I would prefer to simply set `cache->chain` to `NULL` here, because that it conveys the purpose behind this line much better to the reader.

**Comment by RonEld** [comment]
@yanesca I addressed your comments and modified accordingly

File: library/ssl_cache.c (hunk 2 above)
Comment (hanno-arm) [reply library/ssl_cache.c]: I don't think it's worth another commit, but in general I think our `xxx_free` functions zeroize the entire structure, so I'd prefer the original version of the PR. But for `mbedtls_ssl_cache_context` specifically, clearing `chain` is the important step.

**Comment by gilles-peskine-arm** [comment]
The regular Jenkins job can't check this out for some reason. Running manually on https://jenkins-internal.mbed.com/job/mbedtls-commit-tests/33/

**Comment by gilles-peskine-arm** [comment]
CI https://jenkins-internal.mbed.com/job/mbedtls-commit-tests/33/ on 22360825ae64374fb897d366c39f6704a56441b4 failed only due to timing issues, ok to merge
