### PR TITLE
Fix hmac_drbg failure in benchmark, with threading

### LINKED ISSUE #1095: hmac_drbg_free() called too often and too early inside benchmark.c
### Description
- Type: Bug
- Priority: Minor

There's a bug in the mbedTLS benchmark program. When HMAC_DRBG_C is tested, two configurations, namely with SHA1 and with SHA256 are tested. However for both configurations mbedtls_hmac_drbg_free() is called, which means that the context is freed too early although it is being used later. mbedtls_hmac_drbg_free() should only be called at the end of the 
`#if defined(MBEDTLS_HMAC_DRBG_C)` - code.

---------------------------------------------------------------
## Bug
**mbed TLS build:**  
Version: 2.6.0

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Remove redunadnat calls to `hmac_drbg_free()` between seeding operations,
which make the mutex invalid. Fixes #1095

## Status
**READY**

## Requires Backporting
Yes
Which branch?
mbedtls-2.1
mbedtls-2.7

## Migrations
 NO

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Changelog updated
- [x] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

File: programs/test/benchmark.c [hunk 1]
```diff
@@ -648,7 +648,6 @@ int main( int argc, char *argv[] )
         TIME_AND_TSC( "HMAC_DRBG SHA-1 (NOPR)",
                 if( mbedtls_hmac_drbg_random( &hmac_drbg, buf, BUFSIZE ) != 0 )
                 mbedtls_exit(1) );
-        mbedtls_hmac_drbg_free( &hmac_drbg );
```
Comment (andresag01) [inline programs/test/benchmark.c]: I definitely think that calling mbedtls_hmac_drbg_free() here is not correct, but I am not sure whether just removing it should work in all cases. That is, there are probably no issues with just calling mbedtls_hmac_drbg_seed() repeatedly when using the default software code, but I am not sure what happens if, for example, the implementation is a hardware accelerator. Are we expected to call init->seed->seed->free or is it necessary to do init->seed->free->init->seed->free?

Also, I was trying to check what happens inside mbedtls_hmac_drbg_seed(), so I looked up the documentation for mbedtls_md_setup() which is called internally from seed and found the following:
```
 *                  It should be called after mbedtls_md_init() or
 *                  mbedtls_md_free(). Makes it necessary to call
 *                  mbedtls_md_free() later.
```
So according to this, it not necessary to call init at all when using the MD abstraction?

Comment (RonEld) [reply programs/test/benchmark.c]: @andresag01 if by HW acceleration you mean the HW entropy source, then I don't see a problem. Calling seed the second time is *similar* to reseeding. The HW should be stateless and should return the desirted entropy whenever asked.

**Comment by RonEld** [comment]
@andresag01 I agree that the `mbed-os-example-tls` has the same issue.
Do you know if `MBEDTLS_THREADING_C` can be defined in Mbed OS?

File: programs/test/benchmark.c (hunk 1 above)
Comment (andresag01) [reply programs/test/benchmark.c]: Ok

**Comment by andresag01** [comment]
As far as I remember, we had some pending changes to Mbed TLS to make sure that the Mbed TLS multithreading abstraction used through MBEDTLS_THREADING_C had an implementation in Mbed OS, but I do not think it has been merged because some changes are needed to the Mbed TLS APIs (e.g. https://github.com/ARMmbed/mbedtls/pull/1131) that have not been finalized. So I think for now the mbed-os-example-tls will work, but it would still be good to fix it there as well or to raise an issue.

File: ChangeLog [hunk 2]
```diff
@@ -1,5 +1,11 @@
 mbed TLS ChangeLog (Sorted per branch, date)
 
+= mbed TLS x.xx.x branch released xxxx-xx-xx
+
+Bugfix
+   * Fix efailure in hmac_drbg in the benchmark sample application, when
```
Comment (sbutcher-arm) [inline ChangeLog]: 'efailure?' - typo surely?

**Comment by RonEld** [comment]
@sbutcher-arm I fixed the typo

I will rebase to resolve conflicts once the PR is reviewed.

**Comment by sbutcher-arm** [comment]
@roneld - I've approved it, but I think you should go ahead and rebase now, else you'll need another review now, and another two after rebasing, which will just slow things down.

**Comment by RonEld** [comment]
@sbutcher-arm I have rebased and resolved conflicts.
Could you please review?
cc @andresag01

**Comment by RonEld** [comment]
Backported to branches 2.1 and 2.7 in #1898 and #1899 

cc @andresag01 @sbutcher-arm

**Comment by andresag01** [comment]
@sbutcher-arm @RonEld: Please note that the PR https://github.com/ARMmbed/mbed-os-example-tls/pull/194 already addresses these problems.

**Comment by RonEld** [comment]
Removing the "needs backports" label, as all backports have been fully approved
