### PR TITLE
Fix aarch64 assembly for bignum multiplication

### LINKED ISSUE #4962: Clang 12 bignum issue also affects aarch64
Issue #4943 exists as a reminder but it doesn't look like you're aware of concrete bugs, so I'm opening this issue.
If you are aware of this bug already feel free to close this one.

This is functionally identical to #4917.

Just like the other issue it goes away with gcc *or* `-O1` *or* by downgrading to mbedTLS 2.26.0.

### Steps to reproduce

```bash
git clone https://github.com/ARMmbed/mbedtls -b development
cd mbedtls
make -j4 programs || exit 1

echo "Running on $(uname -rms)"
echo "compiler: $($CC --version | head -1)"
echo "commit: $(git rev-parse HEAD)"

./programs/ssl/ssl_server &>/dev/null &
sleep 1
./programs/ssl/ssl_client1
killall ssl_server
```

### Expected behavior

Running on Linux 5.14.1-0-ARCH aarch64
compiler: gcc (GCC) 10.2.0
commit: 304689e4c413ada1991ef5e0199b022bb1123441
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake... ok
  . Verifying peer X.509 certificate... ok
[...]
</pre>

### Actual behavior

Running on Linux 5.14.1-0-ARCH aarch64
compiler: clang version 12.0.1
commit: 304689e4c413ada1991ef5e0199b022bb1123441
<pre>
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...ssl_tls.c:2121: x509_verify_cert() returned -9984 (-0x2700)
ssl_msg.c:4384: mbedtls_ssl_fetch_input() returned -29312 (-0x7280)
ssl_msg.c:3735: ssl_get_next_record() returned -29312 (-0x7280)
ssl_cli.c:2932: mbedtls_ssl_read_record() returned -29312 (-0x7280)
 failed
  ! mbedtls_ssl_handshake returned -0x7280

Last error was: -29312 - SSL - The connection indicated an EOF
</pre>

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
Add missing memory constraint in aarch64 bignum multiplication code to remedy Clang 12+ issues. Fixes #4962.
Part of the larger super-issue #4943.

Tested with the following steps:
```
mkdir build && cd build
CC=clang CFLAGS="--target=aarch64-linux-gnu" cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8
cd tests
qemu-aarch64 -L /usr/aarch64-linux-gnu ./test_suite_mpi
```

## Status
**READY**

## Requires Backporting
Yes
Only to [2.x](https://github.com/ARMmbed/mbedtls/pull/4978) as `2.16` does not have this aarch64 assembly

### CODE REVIEW

**Review by xffbai — DISMISSED** [review]
LGTM and tested good on local arm machine.

File: ChangeLog.d/muladdc-aarch64-memory.txt [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Bugfix
+    * Add missing memory constraints in aarch64 inline assembly for
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/muladdc-aarch64-memory.txt:2]: We probably should combine the two changelog entries that concern the same bug on different architectures.

**Review by gilles-peskine-arm — APPROVED** [review]
LGTM except I think we should combine the changelog entries.

I reviewed the code change and I verified that this fixes the bug with Clang 12 on Ubuntu 20.04, cross-compiling for aarch64 and testing with Qemu.

**Review by gilles-peskine-arm — APPROVED** [review]

**Review by xffbai — APPROVED** [review]
