### PR TITLE
Remove MBEDTLS_CHECK_PARAMS option

### LINKED ISSUE #4313: Remove MBEDTLS_CHECK_PARAMS
### Context

The option `MBEDTLS_CHECK_PARAMS` (disabled by default) enables certain kinds of “parameter validation”. It covers two kinds of validations:
* In some functions that require a valid pointer, “parameter validation” checks that the pointer is non-null. With the feature disabled, a null pointer is not treated differently from any other invalid pointer, and typically leads to a runtime crash. 90% of the uses of the feature are of this kind.
* In some functions that take an enum-like argument, “parameter validation” checks that the value is a valid one. With the feature disabled, an invalid value causes a silent default to one of the valid values.

The default reaction to a failed check is to call a function `mbedtls_param_failed` which the application must provide. If this function returns, its caller returns an error `MBEDTLS_ERR_xxx_BAD_INPUT_DATA`.

This feature is only used in some classic (non-PSA) cryptography modules. It is not used in X.509, TLS or in PSA crypto, and it has not been implemented in all classic crypto modules.

### Proposal

Remove `MBEDTLS_CHECK_PARAMS` and all dependent features. Keep the validation of enum values, but remove the null pointer checks. This means changing code that does something like this:
```
#if MBEDTLS_CHECK_PARAMS
#define VALIDATE(cond) do {if(cond) return BAD_INPUT_DATA;} while (0)
#else
#define VALIDATE(cond) do {} while (0)
#endif
…
VALIDATE(coin == HEADS || coin == TAILS);
VALIDATE(data != NULL);
if (coin == HEADS) heads();
else tails();
```
to something like this:
```
if (coin == HEADS) heads();
else if (coin == TAILS) tails();
else return BAD_INPUT_DATA;
```

### Rationale

**Maintenance burden**: Every compilation option has a testing cost. Beyond this general observation, `MBEDTLS_CHECK_PARAMS` has a major impact on the design of our test framework and scripts because it requires applications to provide their own implementation of `mbedtls_check_params` (unlike other platform functions for which the library provides a sensible default which applications can override).

**Limited benefits**:
* Null pointer checks prevent runtime errors from badly written applications, but null pointers usually have a relatively benign effect: on most platforms, a null pointer dereference is a hard crash which can't be exploited as information disclosure or data injection. The presence of these null pointer checks can be counter productive because they give the appearance that the function accepts a null pointer, which makes it harder to find places where calling code is passing a potentially null pointer (both humans and some static analyzers have heuristics about which pointers are nullable, and extra null checks tend to confuse these heuristics).
* Validation of enum-like values is somewhat useful, but not extremely important, because the parameters concerned are usually constants in applications. This could be made systematic at little cost in effort and code size (see statistics below).

**Misleading documentation**: In some modules, the documentation mentions “parameter validation” (or “parameter-verification failure”), which should mean that the function validates all of its parameters, but this in fact refers specifically to null pointer check and enum-like value checks. Some of these functions omit checks that are more important such as buffer sizes.

**Inconsistent use**: not all modules have this form of “parameter validation”, and this is solely for historical reasons.

### Statistics

(From d5200371ec383d32dd3cb9a105cb11f75749ae25, which is `development` as of a few days ago.)

* Total quasi-hits: 837
    ```
    grep _VALIDATE library/*.c
    ```
* Without false positives: 738
    False positives: definitions of auxiliary macros; MPS.
    ```
    grep _VALIDATE library/*.c |grep -v -F -e ':#' -e MBEDTLS_INTERNAL_VALIDATE -e MBEDTLS_MPS_STATE_VALIDATE_RAW
    ```
* Null checks: 688
    Allowing for whitespace variations, a cast of the pointer, and
    allowing null for a length of 0.
    ```
    grep _VALIDATE library/*.c |grep -E '_VALIDATE(_RET)?\( *(\w+ *== *0 *\|\| *)?(\([^()]+\* *\))? *\*?\w+ *!= *NULL *(\|\| *\w+ *== *0)? *\);'
    ```
* Without null checks and false positives: 51
    ```
    grep _VALIDATE library/*.c |grep -v -E '_VALIDATE(_RET)?\( *(\w+ *== *0 *\|\| *)?(\([^()]+\* *\))? *\*?\w+ *!= *NULL *(\|\| *\w+ *== *0)? *\);' |grep -v -F -e ':#' -e MBEDTLS_INTERNAL_VALIDATE -e MBEDTLS_MPS_STATE_VALIDATE_RAW
    ```
    * RSA mode validation (not applicable in 3.0): 13
    ```
    grep -F 'RSA_VALIDATE_RET( mode ==' library/*.c
    ```
* Remaining calls that are not _RET and not false positives: 2
    ```
    grep _VALIDATE library/*.c |grep -v -E '_VALIDATE(_RET)?\( *(\w+ == 0 *\|\| *)?(\([^()]+\* *\))? *\w+ *!= *NULL *(\|\| \w+ == 0)? *\);' |grep -v -e _RET -e '#define' -e MBEDTLS_INTERNAL_VALIDATE -e MBEDTLS_MPS_STATE_VALIDATE_RAW
    ```
    Both RSA padding mode validation (in mbedtls_rsa_init, mbedtls_rsa_set_padding).

### Work items for 3.0

(size:S)

* Remove `MBEDTLS_CHECK_PARAMS`, `MBEDTLS_CHECK_PARAMS_ASSERT` and `MBEDTLS_PARAM_FAILED` from `config.h`.
* Make it a compile-time error to enable `MBEDTLS_CHECK_PARAMS`.
* Remove `component_test_check_params*` from `all.sh`.
* A minimum amount of changes so that the CI passes.
* Tweak the API for RSA context initialization to have better handling for an invalid padding mode. This is best reviewed separately, so it is not part of the current issue and [filed separately](https://github.com/ARMmbed/mbedtls/issues/4523).

### Work items for 3.x

(size:L)

* Remove all uses of the feature for null pointer checks.
* Change all uses of the feature for enum value checks to code that is executed unconditionally. In 3.0 phase, unit test cases related to invalid enum values have been kept but deactivated with a NOT_DEFINED dependency. When enum values checks are re-enabled in the library code, do not forget to re-activate the corresponding test cases.
* Remove all related auxiliary macros.
* Remove all related tests.
* Remove support code from the test framework.
* Remove mentions of “parameter validation” or “parameter-validation failure” or any related wording from the documentation, or change them to correctly reflect what the code actually does.
* In 2.25+, MBEDTLS_CHECK_PARAMS feature was used in PSA crypto (functions psa_wipe_key_slot() and psa_unlock_key_slot()) to reduce the risk of missing invalid key slot unlock or wiping when running Mbed TLS tests. In 3.0 due to the removal of the  MBEDTLS_CHECK_PARAMS feature and as not critical, those risk mitigations have been removed. This has to be revisited in 3.x: restore the risk mitigations using MBEDTLS_TEST_HOOKS ? do not restore them ?

### Mailing list discussion

https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-April/000326.html

### PR DESCRIPTION
**Pull request by TRodziewicz**
## Description
**Remove MBEDTLS_CHECK_PARAMS option**
**Work items for 3.0**
* Remove MBEDTLS_CHECK_PARAMS, MBEDTLS_CHECK_PARAMS_ASSERT and MBEDTLS_PARAM_FAILED from config.h.
* Make it a compile-time error to enable MBEDTLS_CHECK_PARAMS.
* Remove component_test_check_params* from all.sh.
* A minimum amount of changes so that the CI passes.
* Tweak the API for RSA context initialization to have better handling for an invalid padding mode - separate issue #4523 

Fixes #4313

## Status
READY

## Requires Backporting
NO  

## Migrations
NO

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog updated

### CODE REVIEW

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
I do not think that starting with a merge commit is a good habit. At least that's not the way we usually do it. We rather fetch locally the latest development and base our work on it.

**Comment by TRodziewicz** [comment]
> I do not think that starting with a merge commit is a good habit. At least that's not the way we usually do it. We rather fetch locally the latest development and base our work on it.

Should I re-create this PR?

**Comment by ronald-cron-arm** [comment]
You don't have to. You can just re-base your two commits on top of `development` in your "Remove__CHECK_PARAMS_option" local branch and then force-push it: "git push <your fork repo remote name> --force-with-leave Remove__CHECK_PARAMS_option".
Otherwise, if this is more convenient for you, you can just close this one and create another one. This hasn't been reviewed yet thus this is not a problem.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
I can see that the PR does not start with a merge commit anymore, thanks for that. But there is still a merge commit at the end and we prefer to start reviews with a commit history without any merge commit and anyway we use merge commits sparsely in specific cases (when rebasing is difficult). Thus please fix that as well. Otherwise I can see that your commits are based on commit 07a35f68ee469d8d79ecef9184d76c789f362186 "Update key type name" which is not a merge commit and thus quite unusual and unexpected. Thus please fetch in your local repo the head of the development branch (which is a merge commit) and rebase your commits on top of it. Like this for sure you won't need the last merge commit. Last point, as the review has not started, please just squash commit "Fixing too long line in ChangeLog file" with the previous one.

File: ChangeLog.d/issue4313.txt [hunk 1]
```diff
@@ -0,0 +1,25 @@
+Removals
+   * Remove the following macros: MBEDTLS_CHECK_PARAMS,
+     MBEDTLS_CHECK_PARAMS_ASSERT, MBEDTLS_PARAM_FAILED,
+     MBEDTLS_PARAM_FAILED_ALT, TEST_INVALID_PARAM, TEST_INVALID_PARAM_RET,
+     the following macros have been inactivated MBEDTLS_INTERNAL_VALIDATE_RET
+     and MBEDTLS_INTERNAL_VALIDATE, structures: param_failed_ctx_t,
+     mbedtls_test_param_failed_location_record_t, functions:
```
Comment (mpg) [inline ChangeLog.d/issue4313.txt:7]: Thanks for writing a thorough ChangeLog entry and making sure it is complete. However, I think test functions as well as internal functions and all.sh components don't need to be mentioned here as they are not part of the interface. The target audience for ChangeLog is mostly users of the library, so we should list everything that affects them, which is mostly just the public API of the library. Contributors/developers, who are interested in the tests and internal components, are expected to be able to figure some details on their own.

File: docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md [hunk 2]
```diff
@@ -0,0 +1,49 @@
+Remove MBEDTLS_CHECK_PARAMS option
+----------------------------------
+
+This change affects the way of how parameters are validated.
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md:4]: I think here we want to start with "This change does not affect people who use the default configuration; in only affects users who enabled that option." - that way, a lot of users will immediately know they can skip the rest of that section.

File: docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+The option `MBEDTLS_CHECK_PARAMS` (disabled by default) enables certain kinds of
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md:6]: That should be the past tense now: `enabled` - because it no longer does. Same for the next paragraphs.

File: docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+The default reaction to a failed check is to call a function mbedtls_param_failed
+which the application must provide. If this function returns, its caller returns
+an error `MBEDTLS_ERR_xxx_BAD_INPUT_DATA`.
+
+This feature is only used in some classic (non-PSA) cryptography modules. It is
+not used in X.509, TLS or in PSA crypto, and it has not been implemented in all
+classic crypto modules.
+
+Removal of `MBEDTLS_CHECK_PARAMS` and all dependent features means changing
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md:25]: This entire paragraph should be removed, as it's written from the perspective of library developer, while the migration guide is for users. I think we can instead conclude here with: "This feature has been removed. The library no longer checks for NULL pointers; checks for enum-like arguments will be kept or re-introduced on a case-by-case basis, but their presence will no longer be dependent on a compile-time option."

**Review by mpg — CHANGES_REQUESTED** [review]
This is pretty good and I only have nitpicks about the ChangeLog and migration guide. Also, can you rebase on top of current development in order to resolve conflicts and avoid spurious merge commits as suggested by Ronald? Thanks!

File: ChangeLog.d/issue4313.txt (hunk 1 above)
Comment (TRodziewicz) [reply ChangeLog.d/issue4313.txt:7]: I left only four macros from the beginning of the list.

File: docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md (hunk 2 above)
Comment (TRodziewicz) [reply docs/3.0-migration-guide.d/remove_mbedtls_check_params_option.md:4]: Done

**Review by mpg — COMMENTED** [review]
Thanks for addressing my feedback.

I noticed some changes in the new version of the first commit (done by @ronald-cron-arm ?) which I didn't expected and didn't understand at first, but I think it became clear in a later commit when some dependencies were changed to depend on `NOT_DEFINED`. For my peace of mind, I'd still like to check my understanding here:

- in the library, we kept all calls to `XXX_VALIDATE()`, all inactive for now - later we'll remove the `NULL` checks, keep the enum-like checks, and make them active again;
- for the tests, we've remove the tests for `NULL` pointers and kept the enum-like checks, just inactive for now - later once they're re-enabled in the library we'll make the tests active again.

I think that's a sensible strategy. We just need to created an issue in the 3.x EPIC clearly documenting the remaining work.

File: tests/suites/test_suite_rsa.function [hunk 5]
```diff
@@ -17,454 +17,6 @@
  * END_DEPENDENCIES
  */
 
-/* BEGIN_CASE depends_on:MBEDTLS_CHECK_PARAMS:!MBEDTLS_PARAM_FAILED_ALT */
-void rsa_invalid_param( )
-{
-    mbedtls_rsa_context ctx;
-    const int valid_padding = MBEDTLS_RSA_PKCS_V21;
-    const int invalid_padding = 42;
```
Comment (ronald-cron-arm) [inline tests/suites/test_suite_rsa.function:25]: There is an `invalid_padding` and an `invalid_mode`  thus there are probably some checks to preserve here, please double check.

File: tests/src/helpers.c [hunk 6]
```diff
@@ -222,66 +204,14 @@ int mbedtls_test_hexcmp( uint8_t * a, uint8_t * b,
...
-{
-    return &param_failed_ctx.state;
-}
-
-void mbedtls_test_param_failed_reset_state( void )
-{
-    memset( param_failed_ctx.state, 0, sizeof( param_failed_ctx.state ) );
-}
-
 void mbedtls_param_failed( const char *failure_condition,
```
Comment (ronald-cron-arm) [inline tests/src/helpers.c:207]: mbedtls_param_failed() should be completely removed eventually.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
This looks pretty good. A few things to adjust though.

File: tests/include/test/macros.h [hunk 7]
```diff
@@ -271,12 +195,6 @@
...
  *
- *          Note: this macro is available even when #MBEDTLS_CHECK_PARAMS is
- *          disabled, as it makes sense to check that the functions accept all
- *          legal values even if this option is disabled - only in that case,
- *          the test is more about whether the function segfaults than about
- *          whether it invokes MBEDTLS_PARAM_FAILED().
- *
  * \param   TEST                The test expression to be tested.
  */
 #define TEST_VALID_PARAM( TEST )                                    \
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply tests/include/test/macros.h]: Done, see [c17da26](https://github.com/ARMmbed/mbedtls/pull/4516/commits/c17da2687d276b47b30d5c53e420ade618fe6522).

File: tests/src/helpers.c (hunk 6 above)
Comment (TRodziewicz) [reply tests/src/helpers.c:207]: Should I remove it in this iteration? I mean mbedtls 3.0.

File: tests/suites/main_test.function [hunk 8]
```diff
@@ -176,26 +176,7 @@ void execute_function_ptr(TestWrapper_t fp, void **params)
     mbedtls_test_enable_insecure_external_rng( );
 #endif
 
-#if defined(MBEDTLS_CHECK_PARAMS)
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply tests/suites/main_test.function:179]: It's used in `dispatch_test()` (line 197, see below) - what to do there?
```
int dispatch_test( size_t func_idx, void ** params )
{
    int ret = DISPATCH_TEST_SUCCESS;
    TestWrapper_t fp = NULL;

    if ( func_idx < (int)( sizeof( test_funcs ) / sizeof( TestWrapper_t ) ) )
    {
        fp = test_funcs[func_idx];
        if ( fp )
            execute_function_ptr(fp, params);
        else
            ret = DISPATCH_UNSUPPORTED_SUITE;
    }
    else
    {
        ret = DISPATCH_TEST_FN_NOT_FOUND;
    }

    return( ret );
}
```

[the remark this answers is not in the document]
Comment (ronald-cron-arm) [reply tests/suites/main_test.function:179]: I think I was thinking to just move the code of execute_function_ptr() which is quite small now here.

File: tests/src/helpers.c (hunk 6 above)
Comment (ronald-cron-arm) [reply tests/src/helpers.c:207]: I think at the end of the PR it is not used anymore at all, is it?

Comment (TRodziewicz) [reply tests/src/helpers.c:207]: Yes, you're right. Removed.

File: tests/suites/test_suite_rsa.function (hunk 5 above)
Comment (TRodziewicz) [reply tests/suites/test_suite_rsa.function:25]: Yes, there is `invalid_padding` but I don't see the `invalid_mode`. I reverted the deletion and retained the `invalid_padding` checks. But should I use the `TEST_EQUAL` instead of the `TEST_INVALID_PARAM`?

File: tests/suites/main_test.function (hunk 8 above)
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply tests/suites/main_test.function:179]: OK, done.

File: tests/suites/test_suite_rsa.function (hunk 5 above)
Comment (TRodziewicz) [reply tests/suites/test_suite_rsa.function:25]: Ah, OK, the function will not run now, so it can be left as it is until the next step.

Comment (ronald-cron-arm) [reply tests/suites/test_suite_rsa.function]: The functions tested with `invalid_padding` do not return an error code thus we can just remove the tests. Otherwise there is an `invalid_mode` (see line 27 below) and the associated tests can probably be kept (even if some parameters are equal to NULL).

Comment (ronald-cron-arm) [reply tests/suites/test_suite_rsa.function]: Nope the `invalid_mode` tests have been removed by #4515 and I was looking before the merge commit probably. Thus eventually we just have to get rid of rsa_invalid_param() in tests/suites/test_suite_rsa.function.

File: library/psa_crypto.c [hunk 9]
```diff
@@ -1028,9 +1028,6 @@ psa_status_t psa_wipe_key_slot( psa_key_slot_t *slot )
      */
     if( slot->lock_count != 1 )
     {
-#ifdef MBEDTLS_CHECK_PARAMS
-        MBEDTLS_PARAM_FAILED( slot->lock_count == 1 );
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply library/psa_crypto.c:1032]: Maybe we can just remove the `#ifdef` and `#endif` lines?

File: tests/suites/test_suite_aria.function [hunk 10]
```diff
@@ -36,169 +35,27 @@ void aria_invalid_param( )
     ((void) iv_off);
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply tests/suites/test_suite_aria.function:28]: Done

**Review by mpg — COMMENTED** [review]
This looks good to me, except for the two places in PSA where Ronald has pointed out that we need to find a replacement.

**Comment by gilles-peskine-arm** [comment]
> two places in PSA where Ronald has pointed out that we need to find a replacement.

These are test assertions, not something we rely on for security, so it's ok to file them as a high-priority 3.x follow-up, not a blocker for 3.0.

**Review by mpg — DISMISSED** [review]
After discussion those two places with Ronald and Gilles, I'm happy to merge accept this PR as it is and improve testing in those places later in 3.x.

File: library/psa_crypto.c [hunk 11]
```diff
@@ -1021,16 +1021,10 @@ psa_status_t psa_wipe_key_slot( psa_key_slot_t *slot )
 
     /*
      * As the return error code may not be handled in case of multiple errors,
-     * do our best to report an unexpected lock counter: if available
-     * call MBEDTLS_PARAM_FAILED that may terminate execution (if called as
-     * part of the execution of a test suite this will stop the test suite
-     * execution).
+     * do our best to report an unexpected lock counter.
```
Comment (ronald-cron-arm) [inline library/psa_crypto.c:1024]: Please remove completely that paragraph.

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
Just one paragraph to completely remove and it will be ok on my side as well. Otherwise a conflict has shown up thus yo probably need to update the last merge commit.

File: library/psa_crypto.c (hunk 11 above)
Comment (TRodziewicz) [reply library/psa_crypto.c]: Done

**Comment by ronald-cron-arm** [comment]
There are two conflicts with `development` thus please add a last merge commit with `development` as you have done before, with a commit message explaining the resolution of the conflicts.

**Review by mpg — DISMISSED** [review]
I'm happy with the merge commits: it has the correct parents and the conflict resolution makes sense (concurrent additions to the same place).

**Review by ronald-cron-arm — CHANGES_REQUESTED** [review]
There is an issue in tests/include/test/macros.h. We end-up with two definitions of ASSERT_ALLOC(). Please replay the merge and when it comes to tests/include/test/macros.h don't keep the ASSERT_ALLOC() in the conflict. The issue roots probably from a previous commit but acting at the merge level seems to let eventually tests/include/test/macros.h in a correct state.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Comment by ronald-cron-arm** [comment]
@mpg are you ok with the last version ?

**Review by mpg — APPROVED** [review]
Looks good to me with the latest fix.
