### PR TITLE
 Robustness fix in mbedtls_ssl_derive_keys

### LINKED ISSUE #1437: Status checks return error
### Description
- Type: Bug 
- Priority: Major

---------------------------------------------------------------

## Bug
after adding status checks in function `mbedtls_ssl_derive_keys()` CI tests are failing line [893](https://github.com/ARMmbed/mbedtls/pull/1421/files#diff-995204bbb15401337db9b64bc314e1f6R893) in `ssl_tls.c

**OS**  
linux

**mbed TLS build:**  
Version: Development /  [Commit](https://github.com/ARMmbed/mbedtls/pull/1421/commits/fecf48f51abebd911c49c1a88f89ddbda79d8a0a)

**Expected behavior**   
The status check should return success.
**Actual behavior**  
tests are failing 
**Steps to reproduce**  
run test with the branch from [PR](https://github.com/ARMmbed/mbedtls/pull/1421)

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
In `mbedtls_ssl_derive_keys`, don't call `mbedtls_md_hmac_starts` in ciphersuites that don't use HMAC. This doesn't change the behavior of the code, but avoids relying on an uncaught error when attempting to start an HMAC operation that hadn't been initialized.

This is the root cause for #1437, see https://github.com/ARMmbed/mbedtls/pull/1421/files#r175520310. While #1437 could be best resolved as part of #1421, we can make this robustness fix independently, more for documentation than anything else since it doesn't change the behavior.

* Backport 2.1: #1461
* Backport 2.7: #1464
* A similar fix was contributed independently in #1377.

Fixes #1437

### CODE REVIEW

File: library/ssl_tls.c [hunk 1]
```diff
@@ -855,8 +855,13 @@ int mbedtls_ssl_derive_keys( mbedtls_ssl_context *ssl )
     defined(MBEDTLS_SSL_PROTO_TLS1_2)
     if( ssl->minor_ver >= MBEDTLS_SSL_MINOR_VERSION_1 )
     {
-        mbedtls_md_hmac_starts( &transform->md_ctx_enc, mac_enc, mac_key_len );
-        mbedtls_md_hmac_starts( &transform->md_ctx_dec, mac_dec, mac_key_len );
+        /* For HMAC-based ciphersuites, initialize the HMAC transforms.
+           For AEAD-based ciphersuites, there is nothing to do here. */
+        if( mac_key_len != 0 )
+        {
+            mbedtls_md_hmac_starts( &transform->md_ctx_enc, mac_enc, mac_key_len );
```
Comment (RonEld) [inline library/ssl_tls.c]: `mbedtls_md_hmac_starts()` returns an error. We should check the function doesn't fail.

File: library/ssl_tls.c [hunk 2]
```diff
@@ -855,8 +855,13 @@ int mbedtls_ssl_derive_keys( mbedtls_ssl_context *ssl )
...
+            mbedtls_md_hmac_starts( &transform->md_ctx_dec, mac_dec, mac_key_len );
```
Comment (RonEld) [inline library/ssl_tls.c]: same comment as before

File: library/ssl_tls.c (hunk 1 above)
Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: That's out of scope. #1421 has the job of fixing this.

Comment (RonEld) [reply library/ssl_tls.c]: ok
