### PR TITLE
Backport 2.7: test and fix mutex usage

### LINKED ISSUE #4017: Problem with mutex used in CTR_DRBG and HMAC_DRBG
## Bug

**OS**  
embedded system

**mbed TLS build:**  
Version: 2.7.17

Hello everyone.

I am trying to upgrade the library from version 2.7.17 to 2.7.18.
In my application I use the mbedtls library together with curl.
After updating, my device stops connecting to servers properly after some time.

My application control the number of mutexes used by mbedtls. Logs show that there are no free mutexes to use and a new one could not be initialized.

This has to do with 'In CTR_DRBG and HMAC_DRBG, don't reset the reseed interval in seed (). Fixes # 2927. '

In the mbedtls_crt_drbg_free and mbedtls_hmac_drbg_free functions, a new mutex is initialized at the end of these functions. What if we don't want to use mbedtls_crt_drbg_context or mbedtls_hmac_drbg_context anymore?

In the library I found this function:
https://github.com/ARMmbed/mbedtls/blob/d0c7b79170dbfa42932523c8b4dd326559cf698e/library/ecp.c#L2241
which uses the local ecp_drbg_context. After executing the function, ecp_drbg_context is released but the mutex is initialized and its address is dropped.

Perhaps this is the real problem. I cannot define it.

### LINKED ISSUE #4022: Test mutex resource management
The goal of this issue is to test mutex resource management. We should run the unit tests (and optionally SSL tests) in a mode that would detect:

* Calling `mbedtls_mutex_lock` or `mbedtls_mutex_unlock` or `mbedtls_mutex_free` on a mutex that hasn't been initialized.
* Calling `mbedtls_mutex_lock` twice on a mutex with no intervening unlock.
* Calling `mbedtls_mutex_unlock` on a mutex that isn't locked.
* Calling `mbedtls_mutex_lock` or `mbedtls_mutex_unlock` on a mutex that has been freed.
* Forgetting to call `mbedtls_mutex_free` on a mutex that has been initialized, as reported in https://github.com/ARMmbed/mbedtls/issues/4017.

Note that this does not require any multithreaded execution. The proper use of the mutex to protect data structures is out of scope.

### LINKED ISSUE #4045: Potential memory leak issue caused by new changes to *_drbg_free
### Description
- Type: Bug

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.25.0 or git commit 6aceb51 

Hi,

I'm trying to upgrade from v2.24.0 to v2.25.0 and found a potential memory leak issue during my unit testing.

The new changes to `mbedtls_*_drbg_free()` function allows the drbg context to be reset to the state to just after `mbedtls_*_drbg_init()`. But if I enable multi-threading with `MBEDTLS_THREADING_C`, `mbedtls_*_drbg_free()` function will call `mbedtls_mutex_free()` to free the mutex and call `mbedtls_mutex_init()` to init it again. So `mbedtls_*_drbg_free()` will never actually free the mutex, and if there is memory allocation happens inside `mbedtls_mutex_init()`, this will cause the memory leak on the mutex.

### LINKED ISSUE #4071: multiple call to mbedtls_ssl_handshake on server create a memory leak
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

when calling multiple time mbedtls_ssl_handshake, it will create a memory leak

**OS**  
Freertos

**mbed TLS build:**    
TLS 2.25
Following define are used as we are using multiple threads
#define MBEDTLS_THREADING_C
#define MBEDTLS_THREADING_ALT

**Expected behavior**   
We have a TLS server, upon client connection we call mbedtls_ssl_handshake. Once the connection is terminated FW waits for a new client connection and call again mbedtls_ssl_handshake.

mbedtls_ssl_handshake calls multiple times
mbedtls_ctr_drbg_init
mbedtls_ctr_drbg_free
mbedtls_ctr_drbg_init
mbedtls_ctr_drbg_free

Issue is that at the end of mbedtls_ssl_handshake we have 1 mutex created and it will never be deleted so next call to mbedtls_ssl_handshake will add a new mutex.

There is only 1 way to delete the mbedtls_ctr_drbg_context mutex is by calling mbedtls_ctr_drbg_free, but mbedtls_ctr_drbg_free will create a new mutex.

To reproduce,  call multiple times mbedtls_ssl_handshake with MBEDTLS_THREADING_C and MBEDTLS_THREADING_ALT defined

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Add a framework to test the correct usage of mutex objects: paring of init/free and lock/unlock, etc. Fix #4022.
* Fix a resource leak due to a mutex being left in the initialized state after `mbedtls_ctr_drbg_free` and `mbedtls_hmac_drbg_free`. Fix #4017, fix #4045, fix #4071.

Status: ready for review.

* I'm not completely sure way I fixed the DRBG is right. I changed `drbg_free()` not to re-initialize the mutex, and moved the mutex initialization from `drbg_free()` to `drbg_seed()`, which _should_ be called exactly once before the DRBG is in a usable state. The tests pass, but some “unusual” usage may stop working.
* The tests uncovers a related issue: in the RSA code, we believe that calling `mbedtls_threading_mutex_free()` twice on the same mutex object is safe. This is true with Linux's (and I guess most Unix systems') pthreads, but not necessarily with other mutex implementations. I fixed the RSA issue by using the unused field `ver` to remember whether the mutex is initialized. It's ugly, but hopefully won't break application code even if it sets up the context manually.

This is the 2.7 backport, which I created first so as to ensure that the tests would be easy to port to all supported branches. The DRBG mutex bug was a regression in the current LTS releases.

Note: the PR for development is #4104 and compared to this it has extra tests (in `ssl_server2` and `ssl_client2`, taking advantage of the fact that program can access test functions in development). [added by Manuel]

### CODE REVIEW

File: library/rsa.c [hunk 1]
```diff
@@ -535,15 +538,15 @@ int mbedtls_rsa_gen_key( mbedtls_rsa_context *ctx,
...
-
-    if( nbits % 2 )
-        return( MBEDTLS_ERR_RSA_BAD_INPUT_DATA );
-
     mbedtls_mpi_init( &H );
     mbedtls_mpi_init( &G );
 
+    if( f_rng == NULL || nbits < 128 || exponent < 3 || nbits % 2 != 0 )
+    {
+        ret = MBEDTLS_ERR_RSA_BAD_INPUT_DATA;
```
Comment (gilles-peskine-arm) [inline library/rsa.c:546]: I found out that a failing `mbedtls_rsa_gen_key` did not free the RSA context in these few cases because the PSA wrapper code relied on it. I didn't write a test case for 2.7 because it didn't seem worth the trouble.

File: tests/suites/helpers.function [hunk 2]
```diff
@@ -539,25 +580,87 @@ typedef struct
...
 {
     mutex_functions.init( mutex );
 }
 
 static void mbedtls_test_wrap_mutex_free( mbedtls_threading_mutex_t *mutex )
 {
+    switch( mutex->is_valid )
+    {
+        case MUTEX_FREED:
+            mbedtls_test_mutex_usage_error( mutex, "free without init" );
```
Comment (mpg) [inline tests/suites/helpers.function:626]: Minor: this could also be a double-free (perhaps even more likely).

File: tests/suites/helpers.function [hunk 3]
```diff
@@ -539,25 +580,87 @@ typedef struct
...
+            break;
+        case MUTEX_IDLE:
+            /* Do nothing. The underlying free function will reset is_valid
+             * to 0. */
+            break;
+        case MUTEX_LOCKED:
+            mbedtls_test_mutex_usage_error( mutex, "free without unlock" );
+            break;
+        default:
+            mbedtls_test_mutex_usage_error( mutex, "corrupted state" );
```
Comment (mpg) [inline tests/suites/helpers.function:636]: Minor: this is most likely to be failure to call init, right?

File: library/ctr_drbg.c [hunk 4]
```diff
@@ -103,14 +99,12 @@ void mbedtls_ctr_drbg_free( mbedtls_ctr_drbg_context *ctx )
         return;
 
 #if defined(MBEDTLS_THREADING_C)
-    mbedtls_mutex_free( &ctx->mutex );
+    if( ctx->f_entropy != NULL )
```
Comment (mpg) [inline library/ctr_drbg.c:102]: As the PR description says, some comments should be added. I understand this is a check on whether the context has been seeded, but out of the context of that PR, that wouldn't be obvious.

**Review by mpg — COMMENTED** [review]
Regarding the test framework: I'm a big fan. In the future there's another kind of testing we could be doing regarding mutexes: check what happens when locking or unlocking fails (for example we're more likely to have memory leaks on such errors paths which are rarely taken). This could probably be done in a similar way to your work on memory allocation failure. This is obviously way out of scope for this PR, I'm just mentioning because I think the framework you introduced here would be suitable for such an extension, so that's a good thing.

Regarding fixing the bugs themselves, I feel a bit conflicted about the way you re-use existing struct members. It would perhaps feel cleaner to have a dedicated member just for this, but OTOH this would raise ABI stability questions and also use a bit more RAM... I think I'm not opposed to the current re-use of struct members, as long as it's properly documented (which you already listed as a to-do in the description).

Regarding the DRBG logic, I think the current fix is correct. For the future perhaps it would be better to mandate that after calling `xxx_free()` on a context you can't re-use it without calling `xxx_init()` on it first. That's the kind of contract change that could be done in 3.0. It would certainly make our life much easier. (Also, while we sometimes rely on `xxx_free()` leaving things in the same state as `xxx_init()`, I'm not sure we consistently do it, and this is not consistently tested.)

File: tests/suites/helpers.function [hunk 5]
```diff
@@ -519,3 +525,51 @@ int rnd_pseudo_rand( void *rng_state, unsigned char *output, size_t len )
...
+    return( mutex_functions.unlock( mutex ) );
+}
+
+static void mbedtls_test_mutex_usage_init( void )
+{
+    mutex_functions.init = mbedtls_mutex_init;
+    mutex_functions.free = mbedtls_mutex_free;
+    mutex_functions.lock = mbedtls_mutex_lock;
+    mutex_functions.unlock = mbedtls_mutex_unlock;
+    mbedtls_mutex_init = &mbedtls_test_wrap_mutex_init;
```
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function:694]: Using `ALT` was my first idea, but that requires either significant restructuring of `threading.c` (definitely too much for LTS branches and I'm not even keen on it for development) or arranging to compile tests (and, on development, sample programs) with a `threading_alt.h` which is a pain to set up in the build scripts.

[the remark this answers is not in the document]
Comment (mpg) [reply tests/suites/helpers.function:694]: I think there's a misunderstanding here: I was not suggesting use of any compile-time `_ALT` thing, just calling the `set_alt()` function that's available as part of the normal `threading.h`. Mainly because using a setter function when it's available seems better style than setting the variables directly.

However, looking at the code I can see that the setter function also calls init on the global mutexes we have, which might not be desirable here. In that case, perhaps adding a comment explaining why we're not calling the setter function would be useful.

[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function:694]: `mbedtls_threading_set_alt` isn't compiled unless `MBEDTLS_THREADING_ALT` is defined. I wanted to minimize changes to the library, and this way I needed zero changes.

[the remark this answers is not in the document]
Comment (mpg) [reply tests/suites/helpers.function:694]: Oh, sorry I failed to notice it was only compiled when `MBEDTLS_THREADING_ALT` is defined. Then of course it makes send to not use it.

**Comment by alavrentiev** [comment]
Hi, are you guys expecting to commit the fixes any soon?  Our tests show a great deal of leaking (the more connections the app uses, the more there are the leaked locks -- we use the _ALT model, providing our own mutexes).  As I understand it, the problem is that the context which is freed by these two functions, mbedtls_hmac_drbg_free and mbedtls_ctr_drbg_free, can actually be getting dropped by the caller, yet the re-inited mutex (at the bottom of both) remains hanging around, and thus, is lost.
Thanks,
Anton

File: tests/suites/helpers.function (hunk 3 above)
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function:641]: Maybe, although in practice a failure to call init often results in 0 which is `MUTEX_FREED`.

File: tests/suites/helpers.function (hunk 2 above)
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function]: I deliberately kept these messages short because they can pile up (it would take too much effort to accumulate them and report them at the end of the test case, plus it's somewhat useful to display them synchronously). But indeed double-free is likely so I added it.

**Comment by gilles-peskine-arm** [comment]
@mpg I've pushed additional documentation for the testing part. Later I'll push additional documentation for the bug fixes.

**Comment by gilles-peskine-arm** [comment]
@alavrentiev We expect this fix to be in the next release. We are going to take the time to properly review the fixes (and the tests) before merging to the `mbedtls-2.7`, `mbedtls-2.16` and `development` branches. If you want the fix quickly, please apply the relevant fix commits locally (00fe2428b16798177c25b4270fa23b8a17a65c78 and 0fc7480b4abbba486c11e29293f33df304295f7d). And please let us know if they work for you! At this stage we aren't sure whether this fixes all use cases.

File: library/ctr_drbg.c (hunk 4 above)
Comment (gilles-peskine-arm) [reply library/ctr_drbg.c:103]: I added some comments.

File: include/mbedtls/hmac_drbg.h [hunk 6]
```diff
@@ -374,7 +404,17 @@ int mbedtls_hmac_drbg_random_with_add( void *p_rng,
  *
  * This function automatically reseeds if the reseed counter is exceeded
  * or prediction resistance is enabled.
- *
+ */
+#if defined(MBEDTLS_THREADING_C)
+/**
+ * \note                When Mbed TLS is built with threading support,
+ *                      after this function returns successfully,
```
Comment (mpg) [inline include/mbedtls/hmac_drbg.h:411]: Copy-pasta: "this function" was referring to seed...

File: include/mbedtls/ctr_drbg.h [hunk 7]
```diff
@@ -259,6 +259,15 @@ void mbedtls_ctr_drbg_init( mbedtls_ctr_drbg_context *ctx );
...
  */
 #endif
+#if defined(MBEDTLS_THREADING_C)
+/**
+ * \note                When Mbed TLS is built with threading support,
+ *                      after this function returns successfully,
+ *                      it is safe to call mbedtls_ctr_drbg_random()
+ *                      from multiple threads. Other operations, including
+ *                      reseeding, are not thread-safe.
+ */
```
Comment (mpg) [inline include/mbedtls/ctr_drbg.h:269]: Suggestion: you might want to document random() as thread-safe as you did for HMAC-DRBG (but adapting the text).

File: ChangeLog.d/drbg-mutex.txt [hunk 8]
```diff
@@ -0,0 +1,5 @@
+Bugfix
+   * Fix a resource leak in CTR_DRBG and HMAC_DRBG when MBEDTLS_THREADING_C
+     is enabled, on platforms where initializing a mutex allocates resources.
+     This was a regression introduced in the previous released. Reported in
```
Comment (mpg) [inline ChangeLog.d/drbg-mutex.txt:4]: Typo: releaseD

File: ChangeLog.d/rsa-mutex.txt [hunk 9]
```diff
@@ -0,0 +1,5 @@
+Bugfix
+   * Ensure that calling mbedtls_rsa_free() twice is safe. This happens
+     when some Mbed TLS library functions fail. Such a double-free was safe
+     when MBEDTLS_THREADING_C was enabled on platforms where freeing a mutex
+     twice is not safe.
```
Comment (mpg) [inline ChangeLog.d/rsa-mutex.txt:5]: The last sentence is not clear (and I think it says the opposite of what it should). How about something more concrete like "This fixes a potential resource leak when MBEDTLS_THREADING_C is enabled and the mutex implementation allocates resources on mutex initialisation."?

Actually perhaps the entry should start with that: what are we doing that users care about? Fixing a potential resource leak in RSA with threading. When could that leak happen? On some error paths when init-ing a mutex allocates resources. How are we doing it? By ensuring it's safe to call `rsa_free()` twice.

**Review by mpg — CHANGES_REQUESTED** [review]
Thanks for documenting the changes. This looks good to me except for a couple minor points, and I believe [this comment](https://github.com/ARMmbed/mbedtls/pull/4090/files/a0d5d77b2ded3a63787b9c36b5f5de2a63c3afdd..04ea1064a61e5913bcade25598729173d4e076b7#diff-f781da22676e488056bc0453f79e0e4dee75eb68433a7ae66e257d17e50cfd89) from my previous review hasn't been addressed yet.

File: ChangeLog.d/rsa-mutex.txt (hunk 9 above)
Comment (gilles-peskine-arm) [reply ChangeLog.d/rsa-mutex.txt:5]: There was no resource leak in RSA. The issue was a double free. (In testing terms, the DRBG tests revealed more init calls than free, whereas the RSA tests revealed more free calls than init.) So I think the description is accurate.

The last sentence was indeed missing a negation, so I'm fixing that.

**Comment by gilles-peskine-arm** [comment]
I take Manuel's review as being a design approval.

File: ChangeLog.d/rsa-mutex.txt (hunk 9 above)
Comment (mpg) [reply ChangeLog.d/rsa-mutex.txt]: Oh, sorry, my bad, I mixed up the two cases indeed.

**Review by mpg — APPROVED** [review]
Looks good to me, thanks for addressing my feedback.

**Comment by gilles-peskine-arm** [comment]
In the interest of simplifying the history, I've tweaked it a bit. The final result is the same.

* I squashed fixup commits that were doing nothing but documentation tweaks (e.g. fixing a typo).
* I reordered commits to group them in a more logical way: 2.7 preparation, then test framework, then DRBG fix+doc, then RSA fix+doc. Only commits touching disjoint sets of files changed their relative position.

File: ChangeLog.d/rsa-mutex.txt (hunk 9 above)
Comment (gilles-peskine-arm) [reply ChangeLog.d/rsa-mutex.txt]: Actually there were two bugs in RSA: a double free and a leak. I modified the commit that adds the changelog entry to add another entry for the leak.

**Comment by gilles-peskine-arm** [comment]
I made another rebase to inject [a part of the changelog entry that I'd forgotten](https://github.com/ARMmbed/mbedtls/pull/4090#discussion_r575300905).

**Review by mpg — APPROVED** [review]
Thanks for adding the missing entry. I also checked that the history rewriting didn't modify the final result.

**Review by chris-jones-arm — COMMENTED** [review]
Not sure I'm completely happy about the design of the mutex testing framework but other than that I'm pretty happy with the code as it stands.

File: tests/suites/helpers.function [hunk 10]
```diff
@@ -193,6 +193,9 @@ static struct
     const char *test;
     const char *filename;
     int line_no;
+#if defined(MBEDTLS_TEST_MUTEX_USAGE)
+    const char *mutex_usage_error;
+#endif
```
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply tests/suites/helpers.function:198]: I did it this way so that the functional result is not suppressed. If a test case is failing because it's functionally broken, there may be “auxiliary” errors in that it misuses mutexes. It's easier to understand what's going on if the functional error is reported. For example, if a data structure is in the wrong state at some point in the middle of the test, it's typically easier to figure this out because a library function returned a `BAD_INPUT` error code, than because a mutex turns out to be used after freeing.

I do wish we could report multiple errors from a test case, but that's a long-term wish, not something that can be retrofitted easily. I don't see a problem with having specific fields in `test_info` for library/platform usage errors (now mutex, tomorrow memory, etc.).

[the remark this answers is not in the document]
Comment (chris-jones-arm) [reply tests/suites/helpers.function:198]: Thanks for the example. I think something like a `test_warn` would be of use here and although I'm still not particularly happy about this workaround at least it works for now.

**Review by chris-jones-arm — DISMISSED** [review]
Thanks for the typo fix. As mentioned before I don't know that I'm particularly happy about the way the testing framework reports errors but it does work and is okay for the time being so I'm approving.

**Review by mpg — DISMISSED** [review]
Still looks good to me after fixing the typo.

**Comment by mpg** [comment]
The CI failure in pr-merge was due to an infrastructure issue, and pr-head fully passed, so that's good enough.

**Review by mpg — APPROVED** [review]
LGTM

**Review by chris-jones-arm — APPROVED** [review]
I can verify that the new commits are a clean backport from the development branch. LGTM.

**Comment by gilles-peskine-arm** [comment]
The Windows jobs in pr-merge didn't run due to a CI issue. They passed on pr-head and with a slightly earlier version of the PR with no Windows-related changes, so that's good enough to merge.

**Comment by alavrentiev** [comment]
Hi,
I'm happy to report that with the 2.7.18 LTS and all leaking mutex fixes from this issue backported into there, it all works cleanly for our project now.  We'll be switching to the new LTS (the 2.16 series) very soon.
Thanks,
Anton

**Comment by gilles-peskine-arm** [comment]
@alavrentiev Thanks for confirming!
