### PR TITLE
conditionaly compile ECDH and ECDSA alt functions

### LINKED ISSUE #2163: build error when using alternative ECDH and ECDSA functions
### Description
- Type: Bug
- Priority: Blocker
---------------------------------------------------------------
## Bug

**OS**  
Mbed OS

**mbed TLS build:**  
Version: since https://github.com/ARMmbed/mbedtls/commit/66ba48a3c8e6522b48acffca9cb6beb7c9d7a23e

When defining `MBEDTLS_ECDH_COMPUTE_SHARED_ALT` and all the rest of the ECDH and ECDSA alternative functions, you get build error. 
Reason is that the functions were taken out of hte MACRO check, with the insertion of the restartable ECC feature.

**Expected behavior**   
build to succeed
**Actual behavior**  
Build fails on multiple definition:
~~~
       ecdh.o: In function `mbedtls_ecdh_compute_shared':
        ecdh.c:122: multiple definition of `mbedtls_ecdh_compute_shared'
        ecdh_alt.o:ecdh_alt.c:143: first defined here
        ecdsa.o: In function `mbedtls_ecdsa_sign':
        ecdsa.c:380: multiple definition of `mbedtls_ecdsa_sign'
        ecdsa_alt.o:ecdsa_alt.c:69: first defined here
        ecdsa.o: In function `ecdsa_sign_det_restartable':
        ecdsa.c:394: multiple definition of `mbedtls_ecdsa_verify'
        ecdsa_alt.o:ecdsa_alt.c:33: first defined here
~~~

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Return the condition compilation flags surrounding
`mbedtls_ecdh_compute_shared()`, `mbedtls_ecdh_gen_public()`,
`mbedtls_ecdsa_sign()` and `mbedtls_ecdsa_verify()` that were accidentally
removed in a previous merge.
Resolves #2163

## Status
**READY**

## Requires Backporting
 NO  
The bug was introduced on a recent PR, that is not in the LTS branches

## Migrations
 NO

## Additional comments
May be fixed in a simpler way, having a restartable and a non restartable path, when only the non-restartable path can be hw accelerated. Requires architectural discussion 

## Steps to test or reproduce
Compile the on target tests with the development branch with `NRF52840_DK` target

### CODE REVIEW

File: library/ecdh.c [hunk 1]
```diff
@@ -287,9 +294,15 @@ int mbedtls_ecdh_make_public( mbedtls_ecdh_context *ctx, size_t *olen,
...
 
+#if defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)
+    if( ( ret = mbedtls_ecdh_gen_public( &ctx->grp, &ctx->d, &ctx->Q,
+                                         f_rng, p_rng ) ) != 0 )
+        return( ret );
+#else
     if( ( ret = ecdh_gen_public_restartable( &ctx->grp, &ctx->d, &ctx->Q,
                     f_rng, p_rng, rs_ctx ) ) != 0 )
         return( ret );
+#endif
```
Comment (hanno-arm) [inline library/ecdh.c]: Minor: Could you add `/* MBEDTLS_ECDH_GEN_PUBLIC_ALT */`?

File: library/ecdh.c [hunk 2]
```diff
@@ -335,11 +348,19 @@ int mbedtls_ecdh_calc_secret( mbedtls_ecdh_context *ctx, size_t *olen,
...
+    {
+        return( ret );
+    }
+#else
     if( ( ret = ecdh_compute_shared_restartable( &ctx->grp,
                     &ctx->z, &ctx->Qp, &ctx->d, f_rng, p_rng, rs_ctx ) ) != 0 )
     {
         return( ret );
     }
+#endif
```
Comment (hanno-arm) [inline library/ecdh.c]: Same here.

File: library/ecdsa.c [hunk 3]
```diff
@@ -432,8 +432,13 @@ static int ecdsa_sign_det_restartable( mbedtls_ecp_group *grp,
 
 sign:
 #endif
+#if defined(MBEDTLS_ECDSA_SIGN_ALT)
+    ret = mbedtls_ecdsa_sign( grp, r, s, d, buf, blen,
+                              mbedtls_hmac_drbg_random, p_rng );
+#else
     ret = ecdsa_sign_restartable( grp, r, s, d, buf, blen,
                       mbedtls_hmac_drbg_random, p_rng, rs_ctx );
+#endif
```
Comment (hanno-arm) [inline library/ecdsa.c]: Same here.

File: library/ecdsa.c [hunk 4]
```diff
@@ -575,6 +579,7 @@ int mbedtls_ecdsa_verify( mbedtls_ecp_group *grp,
 {
     return( ecdsa_verify_restartable( grp, buf, blen, Q, r, s, NULL ) );
 }
+#endif /* MBEDTLS_ECDSA_VERIFY_ALT */
```
Comment (hanno-arm) [inline library/ecdsa.c]: Minor: `! MBEDTLS_ECDSA_VERIFY_ALT` instead of `MBEDTLS_ECDSA_VERIFY_ALT`.

File: library/ecdsa.c [hunk 5]
```diff
@@ -626,8 +631,13 @@ int mbedtls_ecdsa_write_signature_restartable( mbedtls_ecdsa_context *ctx,
 #else
     (void) md_alg;
 
+#if defined(MBEDTLS_ECDSA_SIGN_ALT)
+    MBEDTLS_MPI_CHK( mbedtls_ecdsa_sign( &ctx->grp, &r, &s, &ctx->d,
+                         hash, hlen, f_rng, p_rng ) );
+#else
     MBEDTLS_MPI_CHK( ecdsa_sign_restartable( &ctx->grp, &r, &s, &ctx->d,
                          hash, hlen, f_rng, p_rng, rs_ctx ) );
+#endif
```
Comment (hanno-arm) [inline library/ecdsa.c]: Could you add `/* MBEDTLS_ECDSA_SIGN_ALT */` here?

**Comment by RonEld** [comment]
@hanno-arm Thanks for the review!
Yes, I have unused variable warnings, I will fix that.

I would like, however, to have an architectural discussion first, since there are two options of fixing this issue:
1. Having two seperate paths, one hw accelerated non-restartable ECDSA\ECDH operations, and another sw implemented restartable operations. (surrounding only the relevant functions, and if user chooses not to use the restartable functions, then linker will remove them)
2. Using the hw accelerated full operation, also on restartable path, as I did here.

I don't think the difference between the two is big though.

**Comment by RonEld** [comment]
@hanno-arm I have addressed your comments

File: library/ecdh.c [hunk 6]
```diff
@@ -284,7 +286,9 @@ int mbedtls_ecdh_make_public( mbedtls_ecdh_context *ctx, size_t *olen,
                       void *p_rng )
 {
     int ret;
+#if !defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)
```
Comment (hanno-arm) [inline library/ecdh.c]: We can't do that, because now compilation will fail if `MBEDTLS_ECP_RESTARTABLE` and `MBEDTLS_ECDH_GEN_PUBLIC_ALT` are defined simultaenously.

Comment (RonEld) [reply library/ecdh.c]: Why? This was a fix for compilation warning.
In case `MBEDTLS_ECDH_GEN_PUBLIC_ALT ` is defined, the local `rs_ctx` variable will not be used, because of using the non restartable version of `mbedtls_ecdh_gen_public()`, in line [302](https://github.com/ARMmbed/mbedtls/pull/2165/files#diff-97f71deba621674b90985642f0884ebdR302)

Comment (hanno-arm) [reply library/ecdh.c]: See L.294

**Comment by RonEld** [comment]
@hanno-arm I fixed the compilation error

**Comment by mpg** [comment]
I don't think is makes sense to support builds with both `MBEDTLS_ECP_RESTARTABLE` and `MBEDTLS_ECDH_GEN_PUBLIC_ALT` (or any other ECP-related `_ALT`) enabled. I think we should consider documenting that as a restriction on `MBEDTLS_ECP_RESTARTABLE`, and add a corresponding check in `check_config.h`, if it makes the code simpler to manage (and I think it does).

**Comment by RonEld** [comment]
@mpg I agree with you, however this requires bigger changes, I think.
In addition, what should be the behavior if there is only alternative implementation for ECDH but not for ECDSA? I can add the check in `check_config.h` as the likelihood of this scenario is small, I believe

**Comment by mpg** [comment]
@RonEld I don't think it requires bigger changes than documenting in the `config.h` entry for `MBEDTLS_ECP_RESTARTABLE` that this is not compatible with any of the `ECP`, `ECDH` or `ECDSA` `_ALT` options, and adding something like the following to `check_config.h`:
```
#if defined(MBEDTLS_ECP_RESTARTABLE) && ( \
        defined(MBEDTLS_ECP_INTERNAL_ALT) || \
        defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT) || \
        defined(MBEDTLS_ECDH_COMPUTE_SHARED_ALT) || \
        defined(MBEDTLS_ECDSA_VERIFY_ALT) || \
        defined(MBEDTLS_ECDSA_SIGN_ALT) || \
        defined(MBEDTLS_ECDSA_GENKEY_ALT) )
#error "MBEDTLS_ECP_RESTARTABLE defined as well as an incompatible _ALT option"
#endif
```
Then we no longer need to care about those particular combinations in the code - but we don't actually need to change the code if it happened to support those already.

**Comment by RonEld** [comment]
@mpg What I mean, is that now, the public API uses the restartable path. But, I believe that I fixed this in my PR anyway.

**Comment by mpg** [comment]
@RonEld Yes, sorry, I meant no further changes beyond those already made in this PR - I took it for granted that these changes are good and we want them regardless of whether we apply those I'm suggesting in addition, but I should have stated that explicitly, sorry for the confusion.

**Comment by RonEld** [comment]
@mpg, anyway, if for example, only ECDSA has alternative implementation, we don't have the restartable feature for ECDH as well.
If you can live with that, I'm fine

**Comment by mpg** [comment]
@RonEld Yeah, that's what I was suggesting. If any of the ecp, ecdh or ecdsa-related alt options is enabled, then you're not allowed to enable restartable at all. That's what the lines I suggested for `check_config.h` are meant to enforce.

File: include/mbedtls/config.h [hunk 7]
```diff
@@ -694,6 +694,9 @@
  * for too long on ECC (and, hence, X.509 or SSL/TLS) operations.
  *
  * Uncomment this macro to enable restartable ECC computations.
+ *
+ * \note  MBEDTLS_ECP_RESTARTABLE cannot be defined if there is an alternative
```
Comment (gilles-peskine-arm) [inline include/mbedtls/config.h]: Avoid using “cannot” to mean “if you do this, something will break”. Use “must not” or “do not”. Suggestion:

> This option only works with the default software implementation of elliptic curve functionality. It is incompatible with `MBEDTLS_ECP_ALT`, `MBEDTLS_ECDH_xxx_ALT` and `MBEDTLS_ECDSA_xxx_ALT`.

File: library/ecdh.c [hunk 8]
```diff
@@ -191,19 +191,28 @@ int mbedtls_ecdh_make_params( mbedtls_ecdh_context *ctx, size_t *olen,
...
+
+#if defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)
+    if( ( ret = mbedtls_ecdh_gen_public( &ctx->grp, &ctx->d, &ctx->Q,
+                                         f_rng, p_rng ) ) != 0 )
+        return( ret );
+#else
     if( ( ret = ecdh_gen_public_restartable( &ctx->grp, &ctx->d, &ctx->Q,
                                              f_rng, p_rng, rs_ctx ) ) != 0 )
         return( ret );
+#endif /* MBEDTLS_ECDH_GEN_PUBLIC_ALT */
```
Comment (gilles-peskine-arm) [inline library/ecdh.c]:
```suggestion
#endif /* !MBEDTLS_ECDH_GEN_PUBLIC_ALT */
```

File: library/ecdh.c [hunk 9]
```diff
@@ -191,19 +191,28 @@ int mbedtls_ecdh_make_params( mbedtls_ecdh_context *ctx, size_t *olen,
 {
     int ret;
     size_t grp_len, pt_len;
+#if !defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)
```
Comment (gilles-peskine-arm) [inline library/ecdh.c]: I think it would be better to change this to `#if defined(MBEDTLS_ECP_RESTARTABLE)`, and below to call `mbedtls_ecdh_gen_public` under `#if defined(MBEDTLS_ECP_RESTARTABLE)` instead of `#if defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)`. That way the data flow is easier to follow in the “base case” (no restartable, no alt implementations). It may help compilers eliminate a little RAM usage in the base case as well.

The same applies to the other functions with a similar idiom.

Comment (RonEld) [reply library/ecdh.c]: Yes, I agree

File: library/ecdh.c (hunk 8 above)
Comment (RonEld) [reply library/ecdh.c]: but the check is for [`#if defined(MBEDTLS_ECDH_GEN_PUBLIC_ALT)`](https://github.com/ARMmbed/mbedtls/pull/2165/files#diff-97f71deba621674b90985642f0884ebdR207)

**Comment by RonEld** [comment]
@gilles-peskine-arm I addressed your comments

File: library/ecdh.c (hunk 8 above)
Comment (gilles-peskine-arm) [reply library/ecdh.c]: There's an `#else`

Comment (RonEld) [reply library/ecdh.c]: yes, but we usually comment what `#if defined` this closes.
I'll change it

Comment (gilles-peskine-arm) [reply library/ecdh.c]: Huh, seems that we do. Weird, I've never seen this convention before. Please don't change it, it's better to be consistent inside the library.

**Comment by Patater** [comment]
@mpg @RonEld Agreed. Not supporting enabling both at the same time keeps things much simpler. Approved for design.

**Comment by RonEld** [comment]
@gilles-peskine-arm The CI failure is because both `MBEDTLS_ECP_RESTARTABLE` and `MBEDTLS_ECDH_XXX_ALT` are not defined.
Changing to compile only if `MBEDTLS_ECP_RESTARTABLE` is defined does not work, as the context should be used whenever the alternative implementation is not used.
I'll revert the changes

File: library/ecdh.c (hunk 9 above)
Comment (RonEld) [reply library/ecdh.c]: This breaks CI, because the context is used even if `MBEDTLS_ECP_RESTARTABLE` is not defined.

Comment (gilles-peskine-arm) [reply library/ecdh.c]: Not if you change the test around the call to `mbedtls_ecdh_gen_public`. That's the only place where this function uses `rs_ctx`.

Comment (RonEld) [reply library/ecdh.c]: no, the actual call `ecdh_gen_public_restartable` is used regardless whether restarbale feature is used or not.
Unless you want to call `mbedtls_ecdh_gen_public` when restartable is not used?

Comment (gilles-peskine-arm) [reply library/ecdh.c]: > Unless you want to call mbedtls_ecdh_gen_public when restartable is not used?

Yes, that's what I requested above.

**Comment by RonEld** [comment]
@gilles-peskine-arm I changed back to positive flow, and use the non restartable functions when `MBEDTLS_ECP_RESTARTABLE` is not defined

File: library/ecdh.c (hunk 9 above)
Comment (hanno-arm) [reply library/ecdh.c]: I disagree here - I think the restartable ECC feature was implemented in a way that the `xxx_restartable()` functions would be called regardless of whether restartable operations are enabled statically or dynamically, with the restart context parameter deciding whether the feature is actually used or not. I think @RonEld's original approach of guarding the calls through `MBEDTLS_XXX_ALT` suited that better, and it didn't change the existing code in case the `MBEDTLS_XXX_ALT` feature wasn't used.

File: include/mbedtls/config.h [hunk 10]
```diff
@@ -694,6 +694,10 @@
  * for too long on ECC (and, hence, X.509 or SSL/TLS) operations.
  *
  * Uncomment this macro to enable restartable ECC computations.
+ *
+ * \note  This option only works with the default software implementation of
+ *        elliptic curve functionality. It is incompatible with
+ *        MBEDTLS_ECP_ALT, MBEDTLS_ECDH_xxx_ALT and MBEDTLS_ECDSA_xxx_ALT.
```
[the remark this answers is not in the document]
Comment (RonEld) [reply include/mbedtls/config.h]: You are correct, missed that.

**Comment by RonEld** [comment]
@hanno-arm my original approach was also not to call the _restartable functions in case the alternative implementation was defined. The difference is, that I didn't enforce dis allowing the restartable function with the alternative function.
I agree with @mpg that if we have alternative implementation, there is no real need for the restartable feature.

@Patater the approach @gilles-peskine-arm suggested is not really different than the original approach.
In case `MBEDTLS_ECP_RESTARTABLE` is not defined(in sw implementation).
the original approach:
`rs_ctx` is initiated to NULL, and assigned to the restartable context only if `MBEDTLS_ECP_RESTARTABLE` is defined (which isn't in this case), and then call the `_restartable` function with the `rs_ctx (which is `NULL`)

current approach:
we don't have `rs_ctx` at all defined, an dwe call the non restartable function. This function calls the _restartable function with `NULL` as parameter for the restartable context.

So, there isn't any difference between the two approaches, except that the new approach doesn't have a needles variable ( which personally I prefer)

File: library/ecdh.c (hunk 9 above)
Comment (RonEld) [reply library/ecdh.c]: As I mentioned in https://github.com/ARMmbed/mbedtls/pull/2165#issuecomment-436014239 I think that having a positive flow is much readable. note that in previous implementation as well, if `MBEDTLS_ECP_RESTARTABLE` was not defined, then `rs_ctx` is NULL anyway, and there was no difference between calling the _restartable function with a NULL pointer variable, or calling the non restartable functions, which in place calls the restartable function with NULL.
For example https://github.com/ARMmbed/mbedtls/pull/2165#diff-97f71deba621674b90985642f0884ebdR122

**Comment by RonEld** [comment]
@gilles-peskine-arm @hanno-arm I fixed the typo described in https://github.com/ARMmbed/mbedtls/pull/2165#pullrequestreview-171639907

please approve

**Comment by mpg** [comment]
> @mpg I'm interested in hearing your opinion on the new approach suggested by @gilles-peskine-arm as well, before I decide if the new design is OK. Thanks.

I agree with @RonEld that both approaches are not so different, and it's debatable whether that question a matter of design or execution (it's mostly about which way we find the code most readable). As far as I'm concerned, at this stage of the release process any approach that works and doesn't make my eyes bleed when reading the code is good enough.

**Comment by Patater** [comment]
Thanks. Approving the new approach for design.

**Comment by gilles-peskine-arm** [comment]
The Jenkins PR job passed except for FreeBSD timing tests. Jenkins release job: https://jenkins-internal.mbed.com/job/mbedtls-release/791/
