### PR TITLE
Enhance support for signature-hash-algorithm extension

### LINKED ISSUE #823: ssl_server2 does not work with Chrome
Using mbedTLS-2.4.0 and Chrome 56.0.2924.87 (on Windows 7), running ssl_server2 works fine with Firefox and IE but Chrome fails with "ERR_SSL_PROTOCOL_ERROR". A Wireshark trace shows an SSL_Alert (Illegal Parameter) being sent from Chrome after the certificate is received. 

Issue #30 seems related. The comments there indicate there was an issue with ECHDE_ECDSA in Chrome but that it should be resolved in later versions?

### PR DESCRIPTION
**Pull request by hanno-arm**
__Context:__ Fixes #823.

__Summary:__ This PR improves our support for the signature-hash-algorithm extension. During parsing, we now remember one suitable hash algorithm per signature algorithm, and we pick a cipher suite only if there is at least one suitable hash algorithm available.

__Changes on more detail:__ This PR is split in five commits which have detailed explanations in their respective commit messages. Roughly, we proceed in three steps:
* _Commit 1:_ Change use of PK abstraction layer; clarify the way signatures are treated as PK types.
* _Commit 2:_ Introduce helper functions and macros related to the encoding and decoding of signature and hash algorithms, and do some simplifications to ease overlooking the `ServerKeyExchange` write.
* _Commit 3:_ Change signature-hash-extension parsing routine to remember one suitable hash algorithm per signature algorithm.
* _Commit 4 and 5:_ Minors: line splitting and documentation improvements.

__Backports:__ Needs backports to mbed TLS 1.3 and 2.1.

@gilles-peskine-arm @andresag01 @yanesca @mpg Could some of you review this? While the changes are numerous in total, proceeding commit-by-commit hopefully eases reviewing. The signature-hash-algorithm extension is only part of TLS 1.2, so it is important to make sure not to break compatibility with the older protocol version when touching its implementation - I'd appreciate if you could keep a particular focus on that.

### CODE REVIEW

File: include/mbedtls/md.h [hunk 1]
```diff
@@ -49,6 +49,12 @@ typedef enum {
     MBEDTLS_MD_RIPEMD160,
 } mbedtls_md_type_t;
 
+typedef enum {
+    MBEDTLS_SIG_RSA=0,
+    MBEDTLS_SIG_ECDSA,
+    MBEDTLS_SIG_NONE,
```
Comment (mpg) [inline include/mbedtls/md.h]: NONE should be the first value and equal to 0:
- it's a better default value to be used when structures that contain a member of this type are zeroed (as a result of `calloc()` for example)
- if we ever add value to that enum, we can't change the position of existing values (for ABI compatibility), and it would look weird to have NONE in the middle of the list.

File: include/mbedtls/md.h [hunk 2]
```diff
@@ -49,6 +49,12 @@ typedef enum {
...
+} mbedtls_sig_type_t;
```
Comment (mpg) [inline include/mbedtls/md.h]: This type doesn't belong in `md.h`, it should probably go in `ssl_internal.h` if possible, or `ssl.h` otherwise.

File: include/mbedtls/ssl_ciphersuites.h [hunk 3]
```diff
@@ -308,8 +308,9 @@ const mbedtls_ssl_ciphersuite_t *mbedtls_ssl_ciphersuite_from_string( const char
 const mbedtls_ssl_ciphersuite_t *mbedtls_ssl_ciphersuite_from_id( int ciphersuite_id );
 
 #if defined(MBEDTLS_PK_C)
-mbedtls_pk_type_t mbedtls_ssl_get_ciphersuite_sig_pk_alg( const mbedtls_ssl_ciphersuite_t *info );
+mbedtls_pk_type_t mbedtls_ssl_get_ciphersuite_pk_alg( const mbedtls_ssl_ciphersuite_t *info );
```
Comment (mpg) [inline include/mbedtls/ssl_ciphersuites.h]: You can't rename a public function.

File: include/mbedtls/ssl_internal.h [hunk 4]
```diff
@@ -387,8 +387,12 @@ unsigned char mbedtls_ssl_sig_from_pk( mbedtls_pk_context *pk );
 mbedtls_pk_type_t mbedtls_ssl_pk_alg_from_sig( unsigned char sig );
 #endif
 
-mbedtls_md_type_t mbedtls_ssl_md_alg_from_hash( unsigned char hash );
-unsigned char mbedtls_ssl_hash_from_md_alg( int md );
+mbedtls_md_type_t mbedtls_ssl_md_decode( unsigned char hash );
```
Comment (mpg) [inline include/mbedtls/ssl_internal.h]: Again, renaming a public function: even if it's defined in a header with "internal" in its name, so arguably not public, it's still visible to the linker, and I'm really not sure how it would affect people who use mbed TLS as a shared library.

File: include/mbedtls/ssl_ciphersuites.h [hunk 5]
```diff
@@ -315,6 +352,105 @@ mbedtls_sig_type_t mbedtls_ssl_get_ciphersuite_sig_alg( const mbedtls_ssl_cipher
 int mbedtls_ssl_ciphersuite_uses_ec( const mbedtls_ssl_ciphersuite_t *info );
 int mbedtls_ssl_ciphersuite_uses_psk( const mbedtls_ssl_ciphersuite_t *info );
 
+#if defined(MBEDTLS_KEY_EXCHANGE__SOME_PFS__ENABLED)
+static inline int mbedtls_ssl_ciphersuite_has_pfs( const mbedtls_ssl_ciphersuite_t *info )
```
Comment (mpg) [inline include/mbedtls/ssl_ciphersuites.h]: I think this could be merged with its `no_pfs()` sibling, and be declared unconditionally, as we always have at least one ciphersuite, and it always either supports PFS or not. Otherwise in the common case where both kinds of ciphersuites are defined, we end up with  essentially duplicated functions, wasting ROM (and perplexing programmers).

(If you really want to kill it, you can make the function always return 0 or always 1 when it's clear from what's not enabled that a switch statement is not needed.)

File: include/mbedtls/ssl_ciphersuites.h [hunk 6]
```diff
@@ -315,6 +352,105 @@ mbedtls_sig_type_t mbedtls_ssl_get_ciphersuite_sig_alg( const mbedtls_ssl_cipher
...
+                return( 1 );
+
+            default:
+                return( 0 );
+        }
+    }
+#endif /* MBEDTLS_KEY_EXCHANGE__SOME_NON_PFS__ENABLED */
+
+#if defined(MBEDTLS_KEY_EXCHANGE__SOME__ECDH_ENABLED)
+    static inline int mbedtls_ssl_ciphersuite_uses_ecdh( const mbedtls_ssl_ciphersuite_t *info )
```
Comment (mpg) [inline include/mbedtls/ssl_ciphersuites.h]: I like this and the following functions but the indentation looks wrong.

File: library/ssl_srv.c [hunk 7]
```diff
@@ -607,7 +646,7 @@ static int ssl_pick_cert( mbedtls_ssl_context *ssl,
                           const mbedtls_ssl_ciphersuite_t * ciphersuite_info )
 {
     mbedtls_ssl_key_cert *cur, *list, *fallback = NULL;
-    mbedtls_pk_type_t pk_alg = mbedtls_ssl_get_ciphersuite_pk_alg( ciphersuite_info );
+    mbedtls_pk_type_t pk_alg  = mbedtls_ssl_get_ciphersuite_pk_alg ( ciphersuite_info );
```
Comment (mpg) [inline library/ssl_srv.c]: I don't think you meant to introduce those spaces.

File: include/mbedtls/md.h (hunk 1 above)
Comment (mpg) [inline include/mbedtls/md.h]: Ok, having read the other commits, I understand why you wanted to make NONE the last, but if that's a public type that won't work.

File: include/mbedtls/md.h (hunk 2 above)
Comment (mpg) [inline include/mbedtls/md.h]: By the way, a comment explaining why we need a new type instead of re-using `mbedtls_pk_type_t` could be useful, as it wasn't immediately obvious to me.

File: include/mbedtls/ssl_internal.h (hunk 4 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: Thanks @mpg for your comments, I will rework the PR accordingly and check the CI.

File: library/ssl_srv.c [hunk 8]
```diff
@@ -2886,11 +2877,8 @@ static int ssl_write_server_key_exchange( mbedtls_ssl_context *ssl )
         {
             md_alg = MBEDTLS_MD_SHA1;
         }
-        else
-#endif
-        {
-            md_alg = MBEDTLS_MD_NONE;
-        }
```
Comment (hanno-arm) [inline library/ssl_srv.c]: That's wrong, fixed in next push.

File: include/mbedtls/md.h (hunk 2 above)
Comment (hanno-arm) [inline include/mbedtls/md.h]: @mpg From my understanding, elements of `mbedtls_pk_type_t` are public key types together with the information on what kind of operations (encryption, signing, key exchange) they can be used for. Signature algorithms can be extracted from them, and conversely we have the embedding `mbedtls_ssl_pk_alg_from_sig` picking for any signature algorithm one representative pubkey which supports it, but I think it might bring some clarification to introduce a designated type for signature algorithms only. For example, when the client checks whether the signature algorithm in the server's `ServerKeyExchange` matches the server's certificate, it wraps the signature algorithm into a `mbedtls_pk_type_t` and uses `pk_can_do` to check whether there's a match. This looks a bit roundabout to me, and I'd find it clearer to check whether the provided signature algorithm is the underlying signature algorithm of the server's pubkey.

Comment (gilles-peskine-arm) [inline include/mbedtls/md.h]: The reason not to reuse `mbedtls_pk_type_t` is that we're using this as an array index but most public key types don't have an index entry so we don't want to maintain an array that's large enough for `mbedtls_pk_type_t` values.

File: include/mbedtls/md.h (hunk 1 above)
Comment (gilles-peskine-arm) [inline include/mbedtls/md.h]: The type isn't public in the sense that nobody outside us is meant to use these constants. The values aren't part of the ABI. It would be best if this type could be restricted to a single source file.

Instead of having `NONE` at the end, maybe it should be -1? And there should be a different constant `MBEDTLS_SIG_ARRAY_SIZE` for the array size (a good idea for clarity anyway).

File: include/mbedtls/md.h (hunk 2 above)
Comment (hanno-arm) [inline include/mbedtls/md.h]: @gilles-peskine-arm Yes that's another more pragmatic reason, but also conceptually I think it shouldn't be used.

**Comment by hanno-arm** [comment]
@gilles-peskine-arm @mpg I have decided to try to stay with the way signatures are handled within the current PK interface as closely as possible and considerably changed the PR. The old state is still available at https://github.com/hanno-arm/mbedtls/tree/sig_hash_compat_PR1.

File: include/mbedtls/ssl_internal.h [hunk 9]
```diff
@@ -165,8 +183,12 @@ struct mbedtls_ssl_handshake_params
...
      * Handshake specific crypto variables
      */
-    int sig_alg;                        /*!<  Hash algorithm for signature   */
-    int verify_sig_alg;                 /*!<  Signature algorithm for verify */
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && \
+    defined(MBEDTLS_KEY_EXCHANGE__WITH_CERT__ENABLED)
+    mbedtls_ssl_sig_hash_set hash_algs;             /*!<  Set of suitable sig-hash pairs */
+#endif
+    int verify_sig_alg;                         /*!<  Signature algorithm for verify */
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl_internal.h]: Could be a `uint8_t` (possibly through a typedef), and should be at the end to avoid padding. Let's stop abusing `int`.

File: include/mbedtls/ssl_internal.h [hunk 10]
```diff
@@ -157,6 +157,24 @@
 extern "C" {
 #endif
 
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && \
+    defined(MBEDTLS_KEY_EXCHANGE__WITH_CERT__ENABLED)    
+/*
+ * Abstraction for a grid of allowed signature-hash-algorithm pairs.
+ */
+struct mbedtls_ssl_sig_hash_set
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl_internal.h]: That's not a set. `mbedtls_ssl_sig_hash_map_t`?

File: library/ssl_srv.c [hunk 11]
```diff
@@ -776,6 +818,24 @@ static int ssl_ciphersuite_match( mbedtls_ssl_context *ssl, int suite_id,
     }
 #endif
 
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && \
+    defined(MBEDTLS_KEY_EXCHANGE__WITH_CERT__ENABLED)
+    /* If the ciphersuite requires signing, check whether
+     * a suitable hash algorithm is present. */
+    if( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_3                     &&
+        ( sig_type = mbedtls_ssl_get_ciphersuite_sig_alg( suite_info ) )
```
Comment (gilles-peskine-arm) [inline library/ssl_srv.c]: Please avoid burying assignments in tests. I don't think we need such a trick here.

File: ChangeLog [hunk 12]
```diff
@@ -1,5 +1,10 @@
 mbed TLS ChangeLog (Sorted per branch, date)
 
+mbed TLS 2.x.x branch released xxxx-xx-xx
+
+Feature
+    * Enhance support for signature-hash-algorithm extension.
```
Comment (gilles-peskine-arm) [inline ChangeLog]: Mention that this resolves issue #823

File: include/mbedtls/ssl_internal.h (hunk 10 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: Currently, it's a map, but to fully adhere to the standard, it will need to be a set of signature-hash-pairs at some point, and I don't want to rename the type then. That's why I choose this name (I initially did use `mbedtls_ssl_sig_hash_map`), and tried to document accordingly.

File: library/ssl_srv.c (hunk 11 above)
Comment (hanno-arm) [inline library/ssl_srv.c]: Aren't we doing this regularly, e.g. with return value checks? I deliberately choose this variant here to avoid nesting conditionals.

File: include/mbedtls/ssl_internal.h (hunk 9 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: That's a takeover from previous versions, I haven't yet checked the use of this member.

Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: @gilles-peskine-arm It seems this member wasn't used at all - it's removed now.

File: ChangeLog (hunk 12 above)
Comment (hanno-arm) [inline ChangeLog]: @gilles-peskine-arm Updated. Could you have another look, and comment on the open points?

File: library/ssl_srv.c (hunk 11 above)
Comment (gilles-peskine-arm) [inline library/ssl_srv.c]: `if ((ret = f()) != 0)` is one thing, adding a conditional operator into the mix is another, it makes it really hard to notice the assignment. Plus we mostly do this for a return status variable, not for more complex state changes. There's nothing wrong with nesting conditionals.

File: ChangeLog (hunk 12 above)
Comment (gilles-peskine-arm) [inline ChangeLog]: The changelog entry is also missing credit to the initial reporter (following the model of other changelog entries).

File: library/ssl_srv.c (hunk 11 above)
Comment (hanno-arm) [inline library/ssl_srv.c]: @gilles-peskine-arm Changed.

File: ChangeLog (hunk 12 above)
Comment (hanno-arm) [inline ChangeLog]: @gilles-peskine-arm Changed.

**Comment by hanno-arm** [comment]
@gilles-peskine-arm Concerning testing: Unfortunately, the only way for the client to configure the use of the signature hash algorithm extension at the moment is via `mbedtls_ssl_conf_sig_hashes`, which takes a list of hash-algorithms and marks each of them as suitable for _both_ RSA and ECDSA. Therefore there's no easy way to extend `ssl_client2` and our test infrastructure to include tests that would catch this compatibility problem at the moment. I suggest to make this another ticket, and to content ourselves with manual checks for this PR. What do you think?

**Comment by gilles-peskine-arm** [comment]
@hanno-arm We can't test against mbedtls, because it doesn't support this skewed configuration. But can't we test against openssl or gnutls? OpenSSL's [`SSL_set1_sigalgs`](https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set1_sigalgs_list.html) seems to allow this at first glance.

**Comment by hanno-arm** [comment]
@gilles-peskine-arm Yes, and the current branch there's also a test application which allows the configuration of the signature-hash extension from a config file. However, there doesn't seem to a way to pass such a config file to the main OpenSSL executable, so we'd need to opt-in handwritten OpenSSL compatibility tests into our CI which would depend on the availability of the OpenSSL development files.

**Comment by hanno-arm** [comment]
Please don't review this further at the moment, I'm currently making some changes.

**Comment by hanno-arm** [comment]
@gilles-peskine-arm Given that we won't implement client side and test support now, could you give this PR a final look?

File: include/mbedtls/pk.h [hunk 13]
```diff
@@ -170,6 +176,31 @@ typedef size_t (*mbedtls_pk_rsa_alt_key_len_func)( void *ctx );
...
+ *                  (2) The target PK-type has the same underlying
+ *                      mathematical entity but uses it differently
+ *                      for some of its functionality. For example,
+ *                      PK_RSA converts to PK_RSASSA_PSS which has uses
+ *                      different padding scheme for signatures.
+ *
+ * \return          0 if \c from is convertible to \c to, nonzero otherwise.
+ *
+ */
+int mbedtls_pk_type_convertible( mbedtls_pk_type_t from, mbedtls_pk_type_t to );
```
Comment (mpg) [inline include/mbedtls/pk.h]: I'm slightly worried about the name and return convention. IMO it would be clearer to either: rename it as "check_convertible" as we have a consistent convention that "check_foo" returns 0 if foo is true, or rename as "type_is_convertible" and reverse the return value. Sorry for being picky, this kind of things has been an issue in the past.

File: include/mbedtls/ssl_ciphersuites.h [hunk 14]
```diff
@@ -308,7 +308,15 @@ const mbedtls_ssl_ciphersuite_t *mbedtls_ssl_ciphersuite_from_string( const char
 const mbedtls_ssl_ciphersuite_t *mbedtls_ssl_ciphersuite_from_id( int ciphersuite_id );
 
 #if defined(MBEDTLS_PK_C)
+/* Get the weakest (wrt. \c mbedtls_pk_can_do) type of public key
+ * required in the server's certificate for a given cipher suite. 
+ * E.g., an ECDH ciphersuite maps to MBEDTLS_PK_ECKEY_DH. */
```
Comment (mpg) [inline include/mbedtls/ssl_ciphersuites.h]: I like that! Thanks for making this change, this is way better that the previous code.

If I understand correctly, the name should be changed next time we have an occasion to rename (semi-)public functions. If so, can we make a note about it somewhere (doesn't have to be in the code).

File: include/mbedtls/pk.h [hunk 15]
```diff
@@ -251,6 +282,11 @@ static inline size_t mbedtls_pk_get_len( const mbedtls_pk_context *ctx )
  * \param ctx       Context to test
  * \param type      Target type
  *
+ * \note            The return value of this function only depends on the
+ *                  underlying public key type of the given context and gives
+ *                  the same result as the function \c mbedtls_pk_type_convertible. 
+ *                  For more information, see the documentation of the latter.
+ *
```
Comment (hanno-arm) [inline include/mbedtls/pk.h]: Yes, `mbedtls_pk_can_do` is functionally equivalent `mbedtls_pk_type_convertible` on the underlying PK types. If you'd find the time to have a look at the proposed PK changes (our internal ticket has more details), I would really appreciate it, because you know the library better than I do and while I think the changes clarify matters, it might of course be that I miss something.

File: include/mbedtls/pk.h (hunk 13 above)
Comment (hanno-arm) [inline include/mbedtls/pk.h]: No need to apologize, these things have to be consistent of course. I have no objections against either of the two changes you suggested. Which one do you think would be more suitable?

Comment (hanno-arm) [inline include/mbedtls/pk.h]: @mpg I will rename it to `mbedtls_pk_check_convertible`, keeping the meaning of the return value as is.

**Comment by hanno-arm** [comment]
_Update:_ Renamed `mbedtls_pk_type_convertible` to `mbedtls_pk_type_check_convertible` and added commit message for first commit. No other changes.

File: library/ssl_srv.c [hunk 16]
```diff
@@ -204,28 +219,48 @@ static int ssl_parse_signature_algorithms_ext( mbedtls_ssl_context *ssl,
...
-        }
-    }
 
-    /* Some key echanges do not need signatures at all */
-    MBEDTLS_SSL_DEBUG_MSG( 3, ( "no signature_algorithm in common" ) );
-    return( 0 );
+    for( p = buf + 2; p < end; p += 2 ) {
+
+        /* Silently ignore unknown signatures or such where
+         * we have already found a suitable hash algorithm. */
```
Comment (andresag01) [inline library/ssl_srv.c]: Perhaps you should just return when it has been found instead of going though the whole thing.

File: include/mbedtls/ssl_internal.h [hunk 17]
```diff
@@ -165,8 +183,11 @@ struct mbedtls_ssl_handshake_params
     /*
      * Handshake specific crypto variables
      */
-    int sig_alg;                        /*!<  Hash algorithm for signature   */
-    int verify_sig_alg;                 /*!<  Signature algorithm for verify */
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && \
+    defined(MBEDTLS_KEY_EXCHANGE__WITH_CERT__ENABLED)
+    mbedtls_ssl_sig_hash_set_t hash_algs;             /*!<  Set of suitable sig-hash pairs */
```
Comment (andresag01) [inline include/mbedtls/ssl_internal.h]: Do we need to initialise this to `MBEDTLS_MD_NONE` in the `ssl_handshake_params_ini()` function?

File: include/mbedtls/ssl_internal.h [hunk 18]
```diff
@@ -329,6 +350,62 @@ struct mbedtls_ssl_flight_item
...
+{
+    set->rsa   = md_alg;
+    set->ecdsa = md_alg;
+}
+
+/* Setup an empty signature-hash set */
+static inline void mbedtls_ssl_sig_hash_init( mbedtls_ssl_sig_hash_set_t *set )
+{
+    mbedtls_ssl_sig_hash_set_const_hash( set, MBEDTLS_MD_NONE );
+}
```
Comment (gilles-peskine-arm) [inline include/mbedtls/ssl_internal.h]: @andresag01  This is a trivial function — just a function call. I expect that inlining the function results in the same code size or even smaller on most architectures.

File: include/mbedtls/ssl_internal.h (hunk 17 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: Currently it's safe because the handshake params are zeroized, but it's still safer to explicitly call `mbedtls_ssl_sig_hash_init`, so I will add it.

File: library/ssl_srv.c (hunk 16 above)
Comment (hanno-arm) [inline library/ssl_srv.c]: Thanks, the second part of the comment is outdated. We ignore unknown signatures, but we _are_ in principle interested in the full list of supported hash algorithms per signature. The current implementation keeps only one because there's not yet the need for more, but there will be once the sig-hash extension is also taken into account in the choice of server certificate.

File: include/mbedtls/ssl_internal.h (hunk 17 above)
Comment (andresag01) [inline include/mbedtls/ssl_internal.h]: It probably is save, but please recall that the SSL context can be restarted, in which case the handshake parameters are not zeroized

File: library/ssl_cli.c [hunk 19]
```diff
@@ -2518,23 +2514,14 @@ static int ssl_parse_server_key_exchange( mbedtls_ssl_context *ssl )
...
     const mbedtls_ssl_ciphersuite_t *ciphersuite_info = ssl->transform_negotiate->ciphersuite_info;
 
     MBEDTLS_SSL_DEBUG_MSG( 2, ( "=> parse certificate request" ) );
 
-    if( ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_PSK ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_RSA_PSK ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_DHE_PSK ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_PSK ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECJPAKE )
+    if( ! mbedtls_ssl_ciphersuite_no_client_auth( ciphersuite_info ) )
```
Comment (hanno-arm) [inline library/ssl_cli.c]: I have renamed the macro to `MBEDTLS_KEY_EXCHANGE__CERT_REQ_ALLOWED__ENABLED` which better reflects its purpose. I am not quite sure whether the combination of ciphersuites used here is correct, but if it's not it's a pre-existing defect that should be discussed elsewhere; for now, it's only a renaming.

File: library/ssl_cli.c [hunk 20]
```diff
@@ -2332,12 +2332,8 @@ static int ssl_parse_server_key_exchange( mbedtls_ssl_context *ssl )
         return( MBEDTLS_ERR_SSL_INTERNAL_ERROR );
     }
 
-#if defined(MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED) ||                       \
-    defined(MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED) ||                     \
-    defined(MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED)
-    if( ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_DHE_RSA ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_RSA ||
-        ciphersuite_info->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA )
+#if defined(MBEDTLS_KEY_EXCHANGE__WITH_SERVER_SIGNATURE__ENABLED)
```
Comment (hanno-arm) [inline library/ssl_cli.c]: Yes

File: include/mbedtls/ssl_ciphersuites.h [hunk 21]
```diff
@@ -308,7 +308,15 @@ const mbedtls_ssl_ciphersuite_t *mbedtls_ssl_ciphersuite_from_string( const char
...
 mbedtls_pk_type_t mbedtls_ssl_get_ciphersuite_sig_pk_alg( const mbedtls_ssl_ciphersuite_t *info );
+/* Get the weakest (wrt. \c mbedtls_pk_can_do) type of public key
+ * supporting the server signing operation needed for the given 
+ * cipher suite (if any). 
+ * E.g., ECDHE_ECDSA gives MBEDTLS_PK_ECDSA, while ECDH_XXX gives MBEDTLS_PK_NONE. */
+mbedtls_pk_type_t mbedtls_ssl_get_ciphersuite_sig_alg( const mbedtls_ssl_ciphersuite_t *info );
```
Comment (hanno-arm) [inline include/mbedtls/ssl_ciphersuites.h]: Yes

File: include/mbedtls/pk.h [hunk 22]
```diff
@@ -170,6 +176,31 @@ typedef size_t (*mbedtls_pk_rsa_alt_key_len_func)( void *ctx );
...
+ *                  (1) The target PK-type has the same underlying
+ *                      mathematical entity but is restricted in its
+ *                      functionality. For example, the type PK_ECKEY
+ *                      of unrestricted EC keys converts to PK_ECDSA
+ *                      of EC keys to use for ECDSA signing only, but
+ *                      not conversely.
+ *                  (2) The target PK-type has the same underlying
+ *                      mathematical entity but uses it differently
+ *                      for some of its functionality. For example,
+ *                      PK_RSA converts to PK_RSASSA_PSS which has uses
```
Comment (hanno-arm) [inline include/mbedtls/pk.h]: Yes

File: include/mbedtls/ssl_internal.h (hunk 17 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: I agree.

File: include/mbedtls/ssl_internal.h (hunk 18 above)
Comment (hanno-arm) [inline include/mbedtls/ssl_internal.h]: I have moved all but this function to `ssl_tls.c` and hence no longer declared `static inline` here.

**Comment by hanno-arm** [comment]
_Update:_ Incorporated @andresag01 suggestions.

**Comment by mpg** [comment]
@andresag01 It seems to me that alternative implementations will have type `MBEDTLS_PK_RSA_ALT`, not `MBEDTLS_PK_RSA`. I'm don't think that really changes your point but I wanted to clarify.

Now that you mention it, I think in the handshake we should check for `PK_RSA`, not `PK_RSA_RSASSA_PSS`, TLS up to 1.2 only uses PKCS1v1.5 signatures anyway.

**Comment by hanno-arm** [comment]
@andresag01 @mpg As far as I see, there is currently no freedom in what an alternative implementation `can_do` (in particular, they can never do RSASSA-PSS): specifically, alternative implementations cannot provide their own `pk_can_do`, but instead they are tied to a fixed one which only accepts `PK_RSA` (see https://github.com/ARMmbed/mbedtls/blob/development/library/pk_wrap.c#L399).

But your point is still very valid, there is a mismatch between `pk_can_do` and `pk_check_convertible` for `PK_RSA_ALT`: `pk_can_do` matches `RSA_ALT` exactly with `RSA`, while `pk_check_convertible` matches it with itself only. The problem is that `RSA_ALT` isn't a sensible element of `pk_type_t` and should be removed when taking on the view on `pk_type_t` that I proposed. Alternative realizations of RSA are a matter of _implementation_, while `pk_type_t` is about keys and algorithms - `RSA_ALT` doesn't belong there. Of course, if `pk_type_t` is supposed to parametrize the different implementations, that would be different.

So the status might be summarized as: The PK interface needs reworking. The changes in this PR try to make a first improvement but things are still in an inconsistent, though working, state. I suggest to therefore postpone the changes, or at least the introduction of the public function `pk_check_convertible`, to a point where the PK module design has been revised.

**Comment by hanno-arm** [comment]
I have removed the PK interface related changes. @andresag01 @mpg @gilles-peskine-arm Could you have a look?

**Comment by gilles-peskine-arm** [comment]
@hanno-arm Ok for me. Good to keep it simple when we aren't taking the time to do in-depth changes.
