### PR TITLE
psa: Support RSA signature without MBEDTLS_GENPRIME

### LINKED ISSUE #4512: PSA fails to account for configurations with RSA but without MBEDTLS_GENPRIME
---------------------------------------------------------------
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.25.0 or newer
Configuration: Default without `MBEDTLS_GENPRIME`

**Expected behavior**   
PSA should offer features based on the Mbed TLS features available.

**Actual behavior**  
When `MBEDTLS_GENPRIME` is not set, PSA attempts to call `mbedtls_rsa_gen_key()` which isn't available.

**Steps to reproduce**  
Build Mbed TLS with its default configuration, but unset `MBEDTLS_GENPRIME`
Observe linker error

```
        psa_crypto_rsa.c.obj: in function `rsa_generate_key':
        psa_crypto_rsa.c:320: undefined reference to `mbedtls_rsa_gen_key'
```

### PR DESCRIPTION
**Pull request by Patater**
## Description

On space-constrained platforms, it is a useful configuration to be able
to import/export and perform RSA key pair operations, but to exclude RSA
key generation, potentially saving flash space. It is not possible to
express this with the PSA_WANT_ configuration system at the present
time. However, in previous versions of Mbed TLS (v2.24.0 and earlier) it
was possible to configure a software PSA implementation which was
capable of making RSA signatures but not capable of generating RSA keys.
To do this, one unset MBEDTLS_GENPRIME.

Since the addition of MBEDTLS_PSA_BUILTIN_KEY_TYPE_RSA_KEY_PAIR, this
expressivity was lost. Expressing that you wanted to work with RSA key
pairs forced you to include the ability to generate key pairs as well.

Change psa_crypto_rsa.c to only call mbedtls_rsa_gen_key() if
MBEDTLS_GENPRIME is also set. This restores the configuration behavior
present in Mbed TLS v2.24.0 and earlier versions.

It left as a future exercise to add the ability to PSA to be able to
express a desire for a software or accelerator configuration that
includes RSA key pair operations, like signature, but excludes key pair
generation.

Without this change, linker errors will occur when attempts to call,
which doesn't exist when MBEDTLS_GENPRIME is unset.
    psa_crypto_rsa.c.obj: in function `rsa_generate_key':
    psa_crypto_rsa.c:320: undefined reference to `mbedtls_rsa_gen_key'

Fixes #4512

Signed-off-by: Jaeden Amero <jaeden.amero@arm.com>

## Status
**READY**

## Requires Backporting

Yes

- [X] development_2.x (https://github.com/ARMmbed/mbedtls/pull/4546)

## Migrations
If there is any API change, what's the incentive and logic for it.
NO

## Additional comments
None

## Todos
- [x] Tests
- ~[ ] Documentation~
- [x] Changelog updated
- [X] Backported (https://github.com/ARMmbed/mbedtls/pull/4546)

## Steps to test or reproduce
Build with MBEDTLS_GENPRIME unset.

### CODE REVIEW

**Comment by Patater** [comment]
@paul-elliott-arm Could you verify that the `needs: work` label is correct still? It appears that CI was flaky before (experimental TLS 1.3 test). Re-running CI since then, we now have a pass.

File: include/mbedtls/config_psa.h [hunk 1]
```diff
@@ -593,8 +593,10 @@ extern "C" {
 #define MBEDTLS_PSA_BUILTIN_ALG_RSA_PSS 1
 #define PSA_WANT_ALG_RSA_PSS 1
 #endif /* MBEDTLS_PKCS1_V21 */
+#if defined(MBEDTLS_GENPRIME)
```
Comment (gilles-peskine-arm) [inline include/mbedtls/config_psa.h:596]: This also disables signature and decryption.

Unfortunately, there is no way to express “private-key operations but not key generation” in the current PSA crypto configuration system. This is a known limitation. Resolving this limitation will require more design work.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Unfortunately the simple solution is not acceptable since it breaks other use cases.

File: include/mbedtls/config_psa.h (hunk 1 above)
Comment (Patater) [reply include/mbedtls/config_psa.h:596]: Maybe this is a bug, but I am able to perform a signature using an imported RSA key pair even when MBEDTLS_GENPRIME is not set (without this fix in Mbed TLS v2.24.0, and with this fix in v2.25.0). I can provide a sample application if that's helpful.

What's the intention behind both `MBEDTLS_PSA_BUILTIN_KEY_TYPE_RSA_KEY_PAIR ` and `MBEDTLS_PSA_BUILTIN_KEY_TYPE_RSA_PUBLIC_KEY `? Why differentiate?

The fix here provides symmetry in what `MBEDTLS_PSA_BUILTIN_KEY_TYPE_RSA_KEY_PAIR` sets, and what TLS options enable it.

There was (in Mbed TLS v2.24.0) a way to express “private-key operations but not key generation” in the PSA crypto configuration system. Was it intentional to remove this in v2.25.0 and up?

Comment (gilles-peskine-arm) [reply include/mbedtls/config_psa.h:596]: The intention between differentiating have-key-pair and have-public-key is to allow builds that have public-key operations only (typically: I want to verify some signatures, but I'm not going to sign anything), which can save significant code size if the implementation is structured for it: you don't need any blinding code, CRT parameter handling, etc. Mbed TLS is not yet structured for it, but we'll work on that in the coming months.

Private key operations may have worked accidentally even when only `PSA_WANT_KEY_TYPE_RSA_PUBLIC_KEY` was enabled and not `PSA_WANT_KEY_TYPE_RSA_KEY_PAIR`, but we're progressively tightening down on the configuration, and also ramping up testing (https://github.com/ARMmbed/mbedtls/pull/4444 will add systematic negative testing).

> There was (in Mbed TLS v2.24.0) a way to express “private-key operations but not key generation” in the PSA crypto configuration system.

In the classic configuration system, yes. In the PSA configuration system, no. We didn't intend to remove anything, but we're aware that the new system doesn't exactly match the granularity of the old one.

Comment (Patater) [reply include/mbedtls/config_psa.h:596]: I should also highlight that I'm not using `MBEDTLS_PSA_CRYPTO_CONFIG` or `PSA_WANT_*`. Indeed, with `PSA_WANT_*` there is no way to express "private-key operations but not key generation".

I am using the "old-style configuration mechanism", which it seems there is some intention to provide backwards compatibility with, hence my raising of this PR to help with that effort. If this aspect of PSA configuration isn't one you want to support because `PSA_WANT_*` can't express it yet, that's not great for my use case, but I can understand.

Another question would be if the configuration settings I've added to all.sh are considered invalid somehow. Is building with the default config minus `MBEDTLS_GENPRIME` (and no other changes) no longer supported?

Comment (gilles-peskine-arm) [reply include/mbedtls/config_psa.h:596]: Breaking configurations without `MBEDTLS_GENPRIME` was an unintended regression. I fully agree that we should fix it. But I don't want to fix it by breaking something else. I think it should be possible to fix it by adding (back?) a few `#ifdef MBDETLS_GENPRIME` in the right places.

With `MBEDTLS_PSA_CRYPTO_CONFIG`, `MBEDTLS_GENPRIME` is a mandatory consequence of `PSA_WANT_KEY_TYPE_RSA_KEY_PAIR` for the time being, that's a limitation to fix later.

File: tests/scripts/all.sh [hunk 2]
```diff
@@ -1306,6 +1306,12 @@ component_build_crypto_baremetal () {
   if_build_succeeded are_empty_libraries library/libmbedx509.* library/libmbedtls.*
 }
 
+component_build_psa_crypto_rsa_no_genprime() {
+    msg "build: default config minus MBEDTLS_GENPRIME"
+    scripts/config.py unset MBEDTLS_GENPRIME
+    make
```
Comment (gilles-peskine-arm) [inline tests/scripts/all.sh:1312]: Please run `make test` as well

File: include/mbedtls/config_psa.h (hunk 1 above)
Comment (gilles-peskine-arm) [reply include/mbedtls/config_psa.h:596]: As a quick fix, I think the best solution would be to add `#if defined(MBEDTLS_GENPRIME)` back into `psa_crypto_*.c`. That's not the long-term solution, because it only matters for the software implementation, it doesn't allow e.g. an accelerator to declare that it can accelerate RSA signatures but not RSA key generation. But it's a good short-term solution because it fixes the problem you care about without breaking (or worsening) things that currently work (-ish), and it doesn't require any new design that we're not sure is the right design.

**Comment by Patater** [comment]
Also call `make test`, even though not necessary to run into the discovered linker error, it is helpful to see if the configuration without MBEDTLS_GENPRIME is broken in some other fashion.

**Comment by Patater** [comment]
One outstanding issue is if the accelerator configuration `PSA_CRYPTO_DRIVER_TEST && MBEDTLS_PSA_ACCEL_KEY_TYPE_RSA_KEY_PAIR` needs to work without `MBEDTLS_GENPRIME` being set.

```C
#if ( defined(MBEDTLS_PSA_BUILTIN_KEY_TYPE_RSA_KEY_PAIR) ||  \
      ( defined(PSA_CRYPTO_DRIVER_TEST) &&                   \
        defined(MBEDTLS_PSA_ACCEL_KEY_TYPE_RSA_KEY_PAIR) ) )
#define BUILTIN_KEY_TYPE_RSA_KEY_PAIR    1
#endif
```

File: library/psa_crypto_rsa.c [hunk 3]
```diff
@@ -274,7 +274,10 @@ static psa_status_t rsa_export_public_key(
 #endif /* defined(BUILTIN_KEY_TYPE_RSA_KEY_PAIR) ||
         * defined(BUILTIN_KEY_TYPE_RSA_PUBLIC_KEY) */
 
-#if defined(BUILTIN_KEY_TYPE_RSA_KEY_PAIR)
+/* XXX Does MBEDTLS_PSA_ACCEL_KEY_TYPE_RSA_KEY_PAIR use these functions? Both
+ * of them or just rsa_generate_key? */
```
Comment (gilles-peskine-arm) [inline library/psa_crypto_rsa.c:278]: Currently only `rsa_generate_key`.

File: library/psa_crypto_rsa.c [hunk 4]
```diff
@@ -274,7 +274,10 @@ static psa_status_t rsa_export_public_key(
...
+#if defined(BUILTIN_KEY_TYPE_RSA_KEY_PAIR) && \
+    defined(MBEDTLS_GENPRIME)
 static psa_status_t psa_rsa_read_exponent( const uint8_t *domain_parameters,
```
Comment (gilles-peskine-arm) [inline library/psa_crypto_rsa.c:281]: You need to change the guard where this function is used in `psa_crypto.c` as well.

File: library/psa_crypto_rsa.c (hunk 3 above)
Comment (Patater) [reply library/psa_crypto_rsa.c:278]: Does it use this implementation of `rsa_generate_key()` or is another `rsa_generate_key()` substituted in at link time?

File: library/psa_crypto_rsa.c (hunk 4 above)
Comment (Patater) [reply library/psa_crypto_rsa.c:281]: Added, although without fully seeing how accelerators related to the software implementation, I'm not sure it's correct. My worry is we will return "sorry, not supported" when the accelerator does provide a way to generate an RSA key and `MBEDTLS_GENPRIME` is unset. I would expect for the most part that `MBEDTLS_GENPRIME` will be set even when generators are used, given how the `PSA_WANT_*` options work (there is no way for an accelerator to say "don't provide a software implementation for RSA key generation").

Comment (Patater) [reply library/psa_crypto_rsa.c:281]: I think we are OK if MBEDTLS_GENPRIME is always set where we want to use accelerators and want to generate RSA keys.

File: library/psa_crypto_rsa.c (hunk 3 above)
Comment (gilles-peskine-arm) [reply library/psa_crypto_rsa.c:278]: We don't do link-time substitution.

File: library/psa_crypto_rsa.c (hunk 4 above)
Comment (gilles-peskine-arm) [reply library/psa_crypto_rsa.c:281]: Yes, let's just say that for now if your RSA accelerator supports key generation then you must set `MBEDTLS_GENPRIME`.

**Comment by Patater** [comment]
Updated with removal of XXX review comment question and addition of GENPRIME ifdef in `psa_generate_key_internal()` to gate calling `mbedtls_psa_rsa_generate_key()`.

**Comment by Patater** [comment]
Updated to add missing dependency to "PSA generate key: RSA, 1024 bits, good, encrypt (OAEP
    SHA-256)". It wasn't depending on MBEDTLS_GENPRIME, but should have been.

File: ChangeLog.d/psa-without-genprime-fix.txt [hunk 5]
```diff
@@ -0,0 +1,5 @@
+Bugfix
+   * Restore the ability to configure PSA via Mbed TLS options to support RSA
+     key pair operations but exclude RSA key generation. When MBEDTLS_GENPRIME
+     is not defined PSA will no longer attempt to use mbedtls_rsa_gen_key().
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/psa-without-genprime-fix.txt:4]: I think this could just have said “Fix the build when `MBEDTLS_GENPRIME` is disabled.” But ok.

**Review by gilles-peskine-arm — APPROVED** [review]
Looks good to me. Please make a backport to `development_2.x`.

**Comment by Patater** [comment]
Raised backport to `development_2.x` https://github.com/ARMmbed/mbedtls/pull/4546

**Review by ronald-cron-arm — APPROVED** [review]
