### PR TITLE
Remove use of DRBG modules from sample programs

### LINKED ISSUE #10546: Remove use of DRBG modules from sample programs
Most of our sample programs still use the old pattern of directly using entropy and drbg modules. These days, they're supposed to just call `psa_crypto_init()` and then use the PSA RNG:
- either directly with `psa_generate_random()`;
- or indirectly via `mbedtls_psa_get_random()` for functions that need an RNG callback.

Programs under `test` (selftests, benchmark) are an exception: they're allowed to still use drbg for the purpose of directly testing/benchmarking it.

Target programs (might want to split into 1 PR per directory if doing all in one go is a bit much for a single PR):
- ssl
- x509
- fuzz (one occurrence in the crypto repo too)

If entropy and drbg were the only internal thing used, also remove `#define MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS` from the program while at it. If they were not the only thing, ideally create a follow-up issue about what remains.

### PR DESCRIPTION
**Pull request by bjwtaylor**
## Description

Remove use of DRBG modules from sample programs

Resolves #10546

## PR checklist

- [x] **changelog** not required because:  No public changes
- [x] **development PR** provided #HERE
- [x] **TF-PSA-Crypto PR** not required because: No changes
- [x] **framework PR** not required
- [x] **3.6 PR** not required because: No Backports
- **tests**  not required because: No changes to the test matrix

### CODE REVIEW

File: programs/ssl/ssl_test_lib.c [hunk 1]
```diff
@@ -97,87 +61,14 @@ int rng_seed(rng_context_t *rng, int reproducible, const char *pers)
                         "The PSA RNG does not support reproducible mode.\n");
         return -1;
     }
```
Comment (gilles-peskine-arm) [inline programs/ssl/ssl_test_lib.c]: The `if (reproducible) error()` logic somehow got duplicated, please remove one of the instances.

This function doesn't really do anything useful now. But I think we should still keep it, because it reminds us of where we would need to plug something in for reproducible mode. Reproducible mode would be desirable, we just haven't gotten around to creating one yet that's compatible with PSA.

File: programs/ssl/ssl_test_lib.c [hunk 2]
```diff
@@ -97,87 +61,14 @@ int rng_seed(rng_context_t *rng, int reproducible, const char *pers)
...
-    mbedtls_hmac_drbg_free(&rng->drbg);
-#else
-#error "No DRBG available"
-#endif
-
-    mbedtls_entropy_free(&rng->entropy);
-#endif /* !MBEDTLS_TEST_USE_PSA_CRYPTO_RNG */
-}
-
 int rng_get(void *p_rng, unsigned char *output, size_t output_len)
```
Comment (gilles-peskine-arm) [inline programs/ssl/ssl_test_lib.c]: Just like the removal of `rng_init` and `rng_free`, we can remove `rng_get` as well. We had this abstraction layer due to the multiple possible ways to set up an RNG. Now there is only `psa_get_random()` (even `mbedtls_psa_get_random()` is just a trivial wrapper over that). So please replace the calls to `rng_get()` by `psa_get_random()`. And we don't need `rng_context_t` either (even if we reintroduce reproducible mode, it won't involve a local context object).

File: programs/test/selftest.c [hunk 3]
```diff
@@ -331,21 +286,12 @@ const selftest_t selftests[] =
 #if defined(MBEDTLS_ARIA_C)
     { "aria", mbedtls_aria_self_test },
 #endif
-#if defined(MBEDTLS_CTR_DRBG_C)
```
Comment (gilles-peskine-arm) [inline programs/test/selftest.c:331]: HMAC_DRBG and CTR_DRBG are cryptographic modules, regardless of whether a corresponding PSA API exists. So we should keep their self-tests.

(Entropy is not really a cryptographic module and doesn't need a self-test of its own.)

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Almost LGTM except in `selftest.c`, and please clean up the RNG abstraction that we no longer need a little more.

File: programs/ssl/ssl_test_lib.c (hunk 1 above)
Comment (bjwtaylor) [reply programs/ssl/ssl_test_lib.c]: OK, I've kept one instance and removed the second.

File: programs/ssl/ssl_test_lib.c (hunk 2 above)
Comment (bjwtaylor) [reply programs/ssl/ssl_test_lib.c]: Should now be removed.

File: programs/test/selftest.c (hunk 3 above)
Comment (bjwtaylor) [reply programs/test/selftest.c:331]: These have now been re-added.

**Comment by bjwtaylor** [comment]
@gilles-peskine-arm, I've noticed I've missed a signoff from one of the commit's. If it's ok with I'll ammend it and force push to correct this?

**Comment by gilles-peskine-arm** [comment]
Please go ahead and amend the commit.

File: programs/ssl/ssl_server2.c [hunk 4]
```diff
@@ -2948,8 +2948,8 @@ int main(int argc, char *argv[])
         if (opt.ticket_rotate) {
             unsigned char kbuf[MBEDTLS_SSL_TICKET_MAX_KEY_BYTES];
             unsigned char name[MBEDTLS_SSL_TICKET_KEY_NAME_BYTES];
-            if ((ret = rng_get(&rng, name, sizeof(name))) != 0 ||
-                (ret = rng_get(&rng, kbuf, sizeof(kbuf))) != 0 ||
+            if ((ret = mbedtls_psa_get_random(MBEDTLS_PSA_RANDOM_STATE, name, sizeof(name))) != 0 ||
```
Comment (gilles-peskine-arm) [inline programs/ssl/ssl_server2.c]: Please go all the way to `psa_get_random`, since `mbedtls_psa_get_random` is also a backward compatibility wrapper.

File: programs/ssl/ssl_server2.c [hunk 5]
```diff
@@ -3081,7 +3081,7 @@ int main(int argc, char *argv[])
         ssl_async_keys.inject_error = (opt.async_private_error < 0 ?
                                        -opt.async_private_error :
                                        opt.async_private_error);
-        ssl_async_keys.f_rng = rng_get;
+        ssl_async_keys.f_rng = mbedtls_psa_get_random;
```
Comment (gilles-peskine-arm) [inline programs/ssl/ssl_server2.c]: I think `ssl_async_keys.f_rng` and `ssl_async_keys.p_rng` aren't used at all, please remove them while you're at it.

File: programs/ssl/ssl_test_lib.h [hunk 6]
```diff
@@ -106,32 +106,12 @@ void my_debug(void *ctx, int level,
...
-    mbedtls_entropy_context entropy;
-#if defined(MBEDTLS_CTR_DRBG_C)
-    mbedtls_ctr_drbg_context drbg;
-#elif defined(MBEDTLS_HMAC_DRBG_C)
-    mbedtls_hmac_drbg_context drbg;
-#else
-#error "No DRBG available"
-#endif
-#endif /* MBEDTLS_TEST_USE_PSA_CRYPTO_RNG */
 } rng_context_t;
```
Comment (gilles-peskine-arm) [inline programs/ssl/ssl_test_lib.h]: `rng_context_t` no longer has any useful content, and won't get useful again in the future even if we re-add reproducible mode since there's nothing to pass an RNG context to. Please remove it. (Keep `rng_seed` as a placeholder, but without its `rng` argument.)

File: programs/ssl/ssl_server2.c (hunk 4 above)
Comment (bjwtaylor) [reply programs/ssl/ssl_server2.c]: On inspection of the code, it looks like mbedtls_psa_get_random is a wrapper for psa_generate_random. So I'm assuming we want to replace mbedtls_psa_get_random with psa_generate_random. Let me know if this isn't the case though.

File: programs/ssl/ssl_server2.c (hunk 5 above)
Comment (bjwtaylor) [reply programs/ssl/ssl_server2.c]: Now removed.

File: programs/ssl/ssl_test_lib.h (hunk 6 above)
Comment (bjwtaylor) [reply programs/ssl/ssl_test_lib.h]: Should now be removed.

File: programs/test/selftest.c (hunk 3 above)
Comment (mpg) [reply programs/test/selftest.c:331]: From the issue's description:
> Programs under test (selftests, benchmark) are an exception: they're allowed to still use drbg for the purpose of directly testing/benchmarking it.

File: programs/test/selftest.c [hunk 7]
```diff
@@ -340,9 +297,6 @@ const selftest_t selftests[] =
 #if defined(MBEDTLS_ECJPAKE_C)
     { "ecjpake", mbedtls_ecjpake_self_test },
 #endif
-#if defined(MBEDTLS_ENTROPY_C)
-    { "entropy", mbedtls_entropy_self_test_wrapper },
```
Comment (mpg) [inline programs/test/selftest.c:344]: I don't think we want to remove that. (I think it was forgotten when you added back the DRBG selftest functions.)

**Review by mpg — CHANGES_REQUESTED** [review]
I'm pretty happy with what's there (except for the point about entropy selftest), but I might want more :) I can see that `entropy.h`, `ctr_drbg.h` and `hmac_drbg.h` are still included in `programs/ssl/ssl_test_lib.h` and I don't think that should be necessary. Am I missing something or can we remove them?

Moderately related to this PR, but I checked which remaining programs do no call `psa_crypto_init()`, and found that they're all OK (ie, not performing any crypto operation, eg `strerror`, `udp_proxy`, stuff for testing cmake, etc.) so that's good.

Thanks for removing `#define MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS` from so many programs, that's very satisfying :)

Note in case of force-pushes: this was for 778f1a62d4b62648ab8fe2b68d1168e3b7a5b44e

File: programs/test/selftest.c (hunk 7 above)
Comment (gilles-peskine-arm) [reply programs/test/selftest.c:344]: I did want to remove that. DRBG modules have a well-defined cryptographic interface, and so they have self-tests. Having a self-test in the entropy module doesn't make much sense: it's not testing the entropy collection (you need outside context for that) and it's not testing the RNG as a whole (you need the whole RNG for that). And the entropy module is a piece of legacy that we want to remove in 1.x.

But it's no big deal to have these lines, we can remove them as part of the RNG rework.

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

File: programs/test/selftest.c (hunk 7 above)
Comment (bjwtaylor) [reply programs/test/selftest.c:344]: Ok, I re-added them before I read the second comment. @gilles-peskine-arm @mpg, let me know if this agreeable for you both and if not which way you want to go and I'll action it.

Comment (mpg) [reply programs/test/selftest.c:344]: Ah sorry, I didn't realise there was a distinction. I'm happy with the entropy selftest present or removed. IIUC, so is Gilles, so I'd guess just keep the PR as it is now, unless it needs reworking for another reason.
