### PR TITLE
Remove deprecated functions and constants.

### LINKED ISSUE #4282: Remove deprecated things - remainder
This is a catch-all issue to remove deprecated things that are not covered by more specific issues. Here goes the laundry list:

- in AES: remove `mbedtls_aes_encrypt()` and `mbedtls_aes_decrypt()`
- in bignum: remove `mbedtls_mpi_is_prime()`
- in cipher: remove `mbedtls_cipher_auth_encrypt()` and `mbedtls_cipher_auth_decrypt()`
- in DRBGs: remove `mbedtls_ctr_drbg_update()` and `mbedtls_hmac_drbg_update()`
- in DHM: remove `MBEDTLS_DHM_RFC5114_MODP_2048_P`, `MBEDTLS_DHM_RFC5114_MODP_2048_G`, `
MBEDTLS_DHM_RFC3526_MODP_2048_P`, `MBEDTLS_DHM_RFC3526_MODP_2048_G`, `MBEDTLS_DHM_RFC3526_MODP_3072_P`, `MBEDTLS_DHM_RFC3526_MODP_3072_G`, `MBEDTLS_DHM_RFC3526_MODP_4096_P` and `MBEDTLS_DHM_RFC3526_MODP_4096_G`.
- in ECDSA: remove `mbedtls_ecdsa_write_signature_det()` and `mbedtls_ecdsa_sign_det()`
- remove the file `include/mbedtls/net.h`
- in SSL: remove `mbedtls_ssl_conf_dh_param()` and `mbedtls_ssl_get_max_frag_len()`.

Note: normally those functions are not used in the library or programs or even tests. One exception is that the test function `auth_crypt_tv` currently tests the deprecated functions in addition to the new ones. This test function needs to be changed to only test the new functions, by removing the sections guarded by `#if !defined(MBEDTLS_DEPRECATED_REMOVED)` and adapting the comments with mention testing both sets of functions.

### PR DESCRIPTION
**Pull request by TRodziewicz**
Signed-off-by: TRodziewicz <tomasz.rodziewicz@mobica.com>

## Description
Remove all remaining deprecated functions and constants and adjust the code which depends on them.

Fixes #4282 

## Status
READY

## Requires Backporting
NO  

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog updated

### CODE REVIEW

File: library/ecdsa.c [hunk 1]
```diff
@@ -756,10 +681,11 @@ int mbedtls_ecdsa_write_signature_restartable( mbedtls_ecdsa_context *ctx,
...
     mbedtls_mpi r, s;
-    ECDSA_VALIDATE_RET( ctx  != NULL );
-    ECDSA_VALIDATE_RET( hash != NULL );
-    ECDSA_VALIDATE_RET( sig  != NULL );
-    ECDSA_VALIDATE_RET( slen != NULL );
+    ECDSA_VALIDATE_RET( ctx   != NULL );
+    ECDSA_VALIDATE_RET( hash  != NULL );
+    ECDSA_VALIDATE_RET( sig   != NULL );
+    ECDSA_VALIDATE_RET( slen  != NULL );
+    ECDSA_VALIDATE_RET( f_rng != NULL );
```
Comment (mpg) [inline library/ecdsa.c:688]: Thanks for adding that check! However I think this line should be replaced with
```
if( f_rng == NULL )
    return( MBEDTLS_ERR_ECP_BAD_INPUT_DATA );
```
The reason is `ECDSA_VALIDATE_RET()` is not doing anything in most builds, but we want this particular check (just the `f_rng`, not the others) to be present in all builds.

File: tests/suites/test_suite_cipher.function [hunk 2]
```diff
@@ -1184,12 +1059,6 @@ void auth_crypt_tv( int cipher_id, data_t * key, data_t * iv,
                     cipher_id == MBEDTLS_CIPHER_AES_256_KW ||
                     using_nist_kw_padding;
 
-    /****************************************************************
```
Comment (mpg) [inline tests/suites/test_suite_cipher.function:1187]: [This is a comment about another line, but github doesn't let me comment on the proper line.]

Please also remove the comment on lines 1012-1015 that starts with "Do that twice:" as we're now only doing this once :)

**Review by mpg — CHANGES_REQUESTED** [review]
This is looking pretty good! I mostly only have suggestions about updating comments.

Also, this needs ChangeLog entries and Migration guide entries (one for each thing or group of things that were removed). The ChangeLog should just mention what has been removed. The Migration guide should also mention what users should now use instead. See https://github.com/ARMmbed/mbedtls/pull/4402/files#diff-597bd55d5c9a4c3d242dbc9a798d7c23ca3b60f35d05e24b888f479180e615ca

File: tests/suites/test_suite_cipher.function (hunk 2 above)
Comment (TRodziewicz) [reply tests/suites/test_suite_cipher.function:1187]: Done

File: library/ecdsa.c (hunk 1 above)
Comment (TRodziewicz) [reply library/ecdsa.c]: Done

File: include/mbedtls/config.h [hunk 3]
```diff
@@ -446,8 +446,8 @@
  *            the ephemeral key and nothing else. If this is not possible, then
  *            MBEDTLS_ECDSA_DETERMINISTIC should be disabled and an alternative
  *            implementation should be provided for mbedtls_ecdsa_sign_det_ext()
- *            (and for mbedtls_ecdsa_sign_det() too if backward compatibility is
- *            desirable).
+ *            (and for mbedtls_ecdsa_sign_det_ext() too if backward compatibility
+ *            is desirable).
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply include/mbedtls/config.h]: Done

File: include/mbedtls/config.h [hunk 4]
```diff
@@ -424,8 +424,8 @@
  * \note Because of a signature change, the core AES encryption and decryption routines are
  *       currently named mbedtls_aes_internal_encrypt and mbedtls_aes_internal_decrypt,
  *       respectively. When setting up alternative implementations, these functions should
- *       be overridden, but the wrapper functions mbedtls_aes_decrypt and mbedtls_aes_encrypt
- *       must stay untouched.
+ *       be overridden, but the wrapper functions mbedtls_internal_aes_decrypt and
+ *       mbedtls_internal_aes_encrypt must stay untouched.
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply include/mbedtls/config.h]: Done

File: configs/config-psa-crypto.h [hunk 5]
```diff
@@ -400,8 +400,8 @@
  * \note Because of a signature change, the core AES encryption and decryption routines are
  *       currently named mbedtls_aes_internal_encrypt and mbedtls_aes_internal_decrypt,
  *       respectively. When setting up alternative implementations, these functions should
- *       be overridden, but the wrapper functions mbedtls_aes_decrypt and mbedtls_aes_encrypt
- *       must stay untouched.
+ *       be overridden, but the wrapper functions mbedtls_internal_aes_decrypt and
+ *       mbedtls_internal_aes_encrypt must stay untouched.
```
[the remark this answers is not in the document]
Comment (TRodziewicz) [reply configs/config-psa-crypto.h]: Done

**Comment by TRodziewicz** [comment]
> This is looking pretty good! I mostly only have suggestions about updating comments.
> 
> Also, this needs ChangeLog entries and Migration guide entries (one for each thing or group of things that were removed). The ChangeLog should just mention what has been removed. The Migration guide should also mention what users should now use instead. See https://github.com/ARMmbed/mbedtls/pull/4402/files#diff-597bd55d5c9a4c3d242dbc9a798d7c23ca3b60f35d05e24b888f479180e615ca

The ChangeLog has been expanded and the Migration Guide has been added.

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md [hunk 6]
```diff
@@ -0,0 +1,64 @@
+Deprecated functions were removed from AES
+------------------------------------------
+
+The functions `mbedtls_aes_encrypt()` and `mbedtls_aes_decrypt()` were removed.
+Please use `mbedtls_internal_aes_encrypt()` and `mbedtls_internal_aes_decrypt()`
+respectively.
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md:6]: I think the situation here is special as those functions are not meant to be called by normal users of the module anyway. Suggested text:

```
The functions `mbedtls_aes_encrypt()` and `mbedtls_aes_decrypt()` were
removed.

If you're simply using the AES module, you should be calling the
higher-lever functions `mbedtls_aes_crypt_xxx()`.

If you're providing an alternative implementation using
`MBEDTLS_AES_ENCRYPT_ALT` or `MBEDTLS_AES_DECRYPT_ALT`, you should be
replacing `mbedtls_internal_aes_encrypt()` and
`mbedtls_internal_aes_decrypt()` respectively.
```

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+
+The functions `mbedtls_ecdsa_write_signature_det()` and
+`mbedtls_ecdsa_sign_det()` were removed. They were superseded by
+`mbedtls_ecdsa_write_signature()` and `mbedtls_ecdsa_sign_det_ext()`
+respectively.
+
+Deprecated functions were removed from SSL
+------------------------------------------
+
+The functions `mbedtls_ssl_conf_dh_param()` and
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md:42]: I think it would be clearer to have two paragraphs here, one for `dh_param()` and one for `get_max_frag_len()`, as they're unrelated (other than being part of the SSL module).

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+Deprecated hex-encoded primes were removed from DHM
+---------------------------------------------------
+
+The macros `MBEDTLS_DHM_RFC5114_MODP_2048_P`, `MBEDTLS_DHM_RFC5114_MODP_2048_G`,
+`MBEDTLS_DHM_RFC3526_MODP_2048_P`, `MBEDTLS_DHM_RFC3526_MODP_2048_G`,
+`MBEDTLS_DHM_RFC3526_MODP_3072_P`, `MBEDTLS_DHM_RFC3526_MODP_3072_G`,
+`MBEDTLS_DHM_RFC3526_MODP_4096_P `and `MBEDTLS_DHM_RFC3526_MODP_4096_G` were
+removed. The hex-encoded primes from RFC 5114 are deprecated because their 
+derivation is not documented and therefore their usage constitutes a security 
+risk. They are removed from the library without replacement.
```
Comment (mpg) [inline docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md:57]: I think this sound a bit more negative than it should, so I suggest changing to:

The primes from RFC 5114 are deprecated because their derivation is not documented and therefore their usage constitutes a security risk; they are fully removed from the library. Please use parameters from RFC3526 (still in the library, only in binary form) or RFC 7919 (also available in the library) or other trusted sources instead.

**Review by mpg — CHANGES_REQUESTED** [review]
Thanks for addressing my feedback. I have a few suggestions for improving the migration guide, but overall this is looking good!

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md (hunk 8 above)
Comment (TRodziewicz) [reply docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md]: Done.

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md (hunk 7 above)
Comment (TRodziewicz) [reply docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md]: Done.

File: docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md (hunk 6 above)
Comment (TRodziewicz) [reply docs/3.0-migration-guide.d/remove_deprecated_functions_and_constants.md]: Done.

**Review by mpg — APPROVED** [review]
Thanks for addressing my feedback. Looks all good to me now!

File: library/ecdsa.c [hunk 9]
```diff
@@ -420,6 +420,9 @@ int mbedtls_ecdsa_sign( mbedtls_ecp_group *grp, mbedtls_mpi *r, mbedtls_mpi *s,
 #if defined(MBEDTLS_ECDSA_DETERMINISTIC)
 /*
  * Deterministic signature wrapper
+ *
+ * note:    The f_rng_blind parameter must not be NULL.
```
Comment (davidhorstmann-arm) [inline library/ecdsa.c:424]: Would it be worthwhile adding a check to make sure that this is the case? (or even just an assert() of some kind)

Comment (TRodziewicz) [reply library/ecdsa.c:424]: My understanding is that it's the responsibility of the caller to check what is used when the function is called. But the experts here are Manuel and Gilles.

Comment (gilles-peskine-arm) [reply library/ecdsa.c:424]: It's impossible to validate pointers, so why specifically validate that pointers are not null, and not validate far more dangerous invalid pointers such as use after free? Dereferencing a null pointer is a clean crash on most (granted, not all) platforms.

Mbed TLS is a library designed for non-hosted environments, so it can't assert: asserting is not appropriate in all environments. All it can do is return an error.

Having null pointer checks tells static analyzers that it's ok for the argument to be null. So it doesn't necessarily improve the correctness of applications, because now unintended null pointers might not be caught statically.

Mbed TLS 2.x has an optional feature for null pointer checks, which [we're removing in 3.0](https://github.com/ARMmbed/mbedtls/issues/4313) because it was high cost and low benefit.

Comment (davidhorstmann-arm) [reply library/ecdsa.c:424]: Ah that makes sense re validating null pointers in general.

However, this specific case seems different because calling the function with a null pointer used to be valid, but is no longer valid. Anyone who doesn't notice this extra line in the documentation might keep calling this function with NULL.
This will fail at the start of `mbedtls_ecp_gen_privkey()` though, and return `MBEDTLS_ERR_ECP_BAD_INPUT_DATA`, so I suppose it takes care of itself.

**Review by davidhorstmann-arm — APPROVED** [review]

**Comment by mpg** [comment]
The CI is passing except for the ABI-API check which is fully expected to fail considering the nature of this PR.
