### PR TITLE
Restore full TLS compatibility testing

### LINKED ISSUE #5629: compat.sh only runs G->m test cases
Running `tests/compat.sh` with no options only runs `G->m` test cases.

This may or may not be the only problem. I originally noticed this with `tests/scripts/test-ref-configs.pl` (see below). There's something wrong at least with test case enumeration and maybe also with cipher suite filtering.

----

`tests/scripts/test-ref-configs.pl` runs `tests/compat.sh` in some configurations, with certain options to restrict which test suites are tested. But currently this runs 0 test cases in each configuration, so it isn't doing its job.
```
$ tests/scripts/test-ref-configs.pl
…
running compat.sh -m tls12 -f '^TLS-PSK-WITH-AES-...-CCM-8'
------------------------------------------------------------------------
PASSED (0 / 0 tests (0 skipped))
…
running compat.sh -m tls12 -f '^TLS-PSK-WITH-AES-...-CCM-8'
------------------------------------------------------------------------
PASSED (0 / 0 tests (0 skipped))
…
running compat.sh -m tls12 -f 'ECDHE-ECDSA.*AES.*GCM' -p mbedTLS
------------------------------------------------------------------------
PASSED (0 / 0 tests (0 skipped))
…
running compat.sh -m tls12 -f 'ECDHE-ECDSA.*AES.*GCM' -p mbedTLS
------------------------------------------------------------------------
PASSED (0 / 0 tests (0 skipped))
…
```
Expected: whenever `compat.sh` runs, it should invoke a nonzero number of test cases. (In some configurations, `compat.sh` is skipped, and that's ok.)

Both `development` (seen on 868d38f50ff2ee9f17962786336a5563c8d049fd) and `mbedtls-2.28` (seen on 2f39f191e31aec25b57e5eeac0118526469ea46c) are affected.

I think there are multiple issues since `tests/compat.sh -p mbedTLS` runs 0 test cases, and `tests/compat.sh -m tls12 -f '^TLS-PSK-WITH-AES-...-CCM-8'` also runs 0 test cases.

### Task breakdown

For both `mbedtls-2.28` and `development`.

1. Review where `compat.sh` is called from test scripts, and with which arguments.
1. Review the CI logs, and at each point where `compat.sh` is invoked, check whether the expected test cases run. (The bug may result in no test cases running, or more insidiously, only some of the expected test cases running.)
1. Analyze which parameters cause fewer test cases to run than expected. (Suggested output: post a message on this issue explaining the problems.)
1. As applicable, either fix the parameters passed to `compat.sh` or fix the parameter parsing inside `compat.sh`.
1. If the issue turns out to be wrong parameters, improve the documentation of `compat.sh` to help people pass correct parameters.
1. Review CI logs again and ensure that all expected test cases are now invoked.
1. If some of the test cases that were formerly not invoked are failing:
    * Either fix them;
    * Or arrange to skip them temporarily and file an issue to fix them;
    * Or demonstrate that these test cases are not applicable and arrange to skip them.

### PR DESCRIPTION
**Pull request by ronald-cron-arm**
## Description
Restore full TLS compatibility testing that was broken in #5166 / #5262. Fixes #5629.

## Status
IN DEVELOPMENT

## Requires Backporting
Yes
Which branch: [2.28](https://github.com/ARMmbed/mbedtls/pull/5660)

### CODE REVIEW

File: tests/compat.sh [hunk 1]
```diff
@@ -217,7 +217,7 @@ filter_ciphersuites()
     # supports from the s_server help. (The s_client help isn't
     # accurate as of 1.0.2g: it supports DTLS 1.2 but doesn't list it.
     # But the s_server help seems to be accurate.)
-    if ! $OPENSSL_CMD s_server -help 2>&1 | grep -q "^ *-$MODE "; then
+    if ! $OPENSSL_CMD s_server -help 2>&1 | grep -q "^ *-$O_MODE "; then
         M_CIPHERS=""
```
Comment (gilles-peskine-arm) [inline tests/compat.sh:221]: Why would we skip m-m tests based on the availability of openssl features? This looks like a bug which affects test runs with `OPENSSL_LEGACY`. This bug was introduced in https://github.com/ARMmbed/mbedtls/pull/2779/commits/6eece5b666a36094f5ebef93b9683df06b81c698.

Comment (gilles-peskine-arm) [reply tests/compat.sh:221]: For example https://ci.trustedfirmware.org/job/mbed-tls-pr-head/job/PR-5630-head/1/execution/node/1276/log/ lacks `m->m` and `m->G` tests under `test: compat.sh DES, 3DES & NULL (full config)`.

**Review by gilles-peskine-arm — DISMISSED** [review]
The fix is correct but incomplete. Based on [my understanding](https://github.com/ARMmbed/mbedtls/issues/5629#issuecomment-1067919492), it's fixing one of two bugs. Please fix [the skipping of non-openssl tests based on the openssl version](https://github.com/ARMmbed/mbedtls/pull/5630/files#r826849976).

I have not made a thorough review of the logs, only spot checks.

**Comment by ronald-cron-arm** [comment]
> The fix is correct but incomplete. Based on [my understanding](https://github.com/ARMmbed/mbedtls/issues/5629#issuecomment-1067919492), it's fixing one of two bugs. Please fix [the skipping of non-openssl tests based on the openssl version](https://github.com/ARMmbed/mbedtls/pull/5630/files#r826849976).
> 
> I have not made a thorough review of the logs, only spot checks.

Indeed, so far, I have only addressed the bug introduced in #5166. Thanks for looking at this more broadly. I will look at the other issue you mention.

**Review by mpg — APPROVED** [review]
LGTM

**Comment by mpg** [comment]
The only CI failure is an instance of #5279 so can be ignored as far as this PR is concerned.

**Comment by mprse** [comment]
One test has failed on CI:

```
[2022-03-25T18:35:23.010Z] FAILED: 1 components

[2022-03-25T18:35:23.010Z] test_variable_ssl_in_out_buffer_len_CID: test: ssl-opt.sh, MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH and MBEDTLS_SSL_DTLS_CONNECTION_ID enabled: tests/ssl-opt.sh -> 1

```

**Review by mprse — APPROVED** [review]
LGTM
