### PR TITLE
Force cleanup by using goto exit instead of direct return

### LINKED ISSUE #2905: Missing cleanup in a few error cases in SSL test programs
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

* In `ssl_client2.c` and `ssl_server2.c`, in the `main` function, if the option `query_config` is found, we `return` instead of `goto exit`.
* In `ssl_client2.c`, in the `main` function, if `mbedtls_ssl_set_cid` fails, we `return` instead of `goto exit`.

This could cause spurious errors about memory leaks since some objects allocated at the beginning of `main` aren't cleaned up. It's minor because we never run against this in any of our tests. It may cause true positives that we don't care about in static analysis.

### PR DESCRIPTION
**Pull request by gabor-mezei-arm**
## Description
Fixes #2905

### CODE REVIEW

File: programs/ssl/ssl_client2.c [hunk 1]
```diff
@@ -1718,7 +1718,8 @@ int main( int argc, char *argv[] )
         }
         else if( strcmp( p, "query_config" ) == 0 )
         {
-            return query_config( q );
+            ret = query_config( q );
+            goto exit;
```
Comment (yanesca) [inline programs/ssl/ssl_client2.c:1722]: This changes the behaviour:
- if `MBEDTLS_ERROR_C` is defined and `query_config( q )` == 1, then an extra error message will be printed in the log (line 4278)
- if `MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED` is defined, then the return value will be overridden (line 4322)
This is probably the reason why the CI is failing.

**Comment by yanesca** [comment]
We usually only update PRs with the development branch if there is a CI failure or there would be a merge commit. When doing so, we usually prefer rebase to merging `development`. We only use merge in exceptional cases, when the PR is very big and/or very old.

Could you please remove the merge commits from this PR? (For example by cherry-picking the 3 meaningful commits on the top of `development`?)

Also, please ensure that every commit has your sign-off!

File: tests/ssl-opt.sh [hunk 2]
```diff
@@ -8807,8 +8807,8 @@ run_test    "DTLS reordering: Buffer out-of-order hs msg before reassembling nex
             hs_timeout=2500-60000" \
             0 \
             -c "Buffering HS message" \
-            -c "attempt to make space by freeing buffered future messages" \
-            -c "Enough space available after freeing buffered HS messages" \
+            -C "attempt to make space by freeing buffered future messages" \
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh]: Please explain in the commit message why you have to update those error messages.

File: programs/ssl/ssl_server2.c [hunk 3]
```diff
@@ -1759,7 +1759,7 @@ int report_cid_usage( mbedtls_ssl_context *ssl,
 
 int main( int argc, char *argv[] )
 {
-    int ret = 0, len, written, frags, exchanges_left;
+    int ret = 0, r = 0, len, written, frags, exchanges_left;
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c]: Declare the variable just before to use it and name it 'psk_free_ret' ?
Like this the name of the variable does convey much information and the variable it used far away from where it is declared.

File: tests/ssl-opt.sh [hunk 4]
```diff
@@ -202,6 +202,7 @@ get_config_value_or_default() {
 
 requires_config_value_at_least() {
     VAL="$( get_config_value_or_default "$1" )"
+    VAL=${VAL//[^0-9]*}
```
Comment (ronald-cron-arm) [inline tests/ssl-opt.sh]: Please explain in the commit message why you need this change and what test failure it does fix.

File: tests/ssl-opt.sh (hunk 2 above)
Comment (gabor-mezei-arm) [reply tests/ssl-opt.sh]: Done

File: tests/ssl-opt.sh (hunk 4 above)
Comment (gabor-mezei-arm) [reply tests/ssl-opt.sh]: Done

File: programs/ssl/ssl_server2.c (hunk 3 above)
Comment (gabor-mezei-arm) [reply programs/ssl/ssl_server2.c]: Done

File: programs/ssl/ssl_client2.c (hunk 1 above)
Comment (yanesca) [reply programs/ssl/ssl_client2.c:1685]: I still think that this changes behaviour. I just noticed that I gave the line numbers for `ssl_server2.c` in my previous comment and that you fixed it there, but the same problem holds here too.

File: tests/ssl-opt.sh [hunk 5]
```diff
@@ -8846,8 +8846,6 @@ run_test    "DTLS reordering: Buffer out-of-order hs msg before reassembling nex
             hs_timeout=2500-60000" \
             0 \
             -c "Buffering HS message" \
-            -c "attempt to make space by freeing buffered future messages" \
```
Comment (yanesca) [inline tests/ssl-opt.sh:8849]: These lines are testing the presence of these messages in the client output. A couple of extra messages wouldn't make them fail.

Also, removing these lines changes the purpose of these tests. I think we should not change observable behaviour in this PR. If we keep the observable behaviour we won't need to change any tests.

File: tests/ssl-opt.sh [hunk 6]
```diff
@@ -215,6 +215,8 @@ get_config_value_or_default() {
 
 requires_config_value_at_least() {
     VAL="$( get_config_value_or_default "$1" )"
+    # Pick only the relevant information from the output
```
Comment (yanesca) [inline tests/ssl-opt.sh:218]: Again, instead of changing the output here in the test script, we should make sure that the program produces the correct output.

**Comment by ronald-cron-arm** [comment]
I can see some back and forth in the commit history with two commits reverted, could you please simplify the history and just get rid of the commits that are reverted later on.

**Comment by yanesca** [comment]
@gabor-mezei-arm Thank you for cleaning up the history, it makes reviewing much easier!

File: programs/ssl/ssl_client2.c [hunk 7]
```diff
@@ -2361,25 +2362,25 @@ int main( int argc, char *argv[] )
             goto exit;
         }
 
-        if( ( ret = mbedtls_ssl_conf_psk_opaque( &conf, slot,
+        if( ( ssl_conf_ret = mbedtls_ssl_conf_psk_opaque( &conf, slot,
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_client2.c:2369]: `ssl_conf_ret` is used only locally here thus I don't see the point. Isn't it a leftover from previous changes? Furthermore with this we don't see the message "Last error was;" ...

File: programs/ssl/ssl_client2.c [hunk 8]
```diff
@@ -1682,6 +1685,7 @@ int main( int argc, char *argv[] )
         }
         else if( strcmp( p, "query_config" ) == 0 )
         {
+            opt.query_config_mode = 1;
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_client2.c:1688]: What about to introduce a "query_config_ret" local variable and thus not change anything with the usage of `ret` here and below. Then at the end of the `main()` function check `opt.query_config_mode` and if it is different from `DFL_QUERY_CONFIG_MODE` call `mbedtls_exit(  query_config_ret )`.

File: programs/ssl/ssl_client2.c [hunk 9]
```diff
@@ -2680,7 +2681,7 @@ int main( int argc, char *argv[] )
         {
             mbedtls_printf( " failed\n  ! mbedtls_ssl_set_cid returned %d\n\n",
                             ret );
-            return( ret );
+            goto exit;
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_client2.c:2689]: It would be better not to mix this change with the changes related to `query_config` in the same commit. Those are two different things and then in the following commit it is not obvious if the changes are related to this change or to the `query_config` change. Do first the fixes/changes only related to `query_config` in one or several commits, then fix that one, again in one or several commits.

File: programs/ssl/ssl_client2.c [hunk 10]
```diff
@@ -3302,7 +3308,7 @@ int main( int argc, char *argv[] )
      */
 exit:
 #ifdef MBEDTLS_ERROR_C
-    if( ret != 0 )
+    if( ret != 0 && opt.query_config_mode == DFL_QUERY_CONFIG_MODE )
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_client2.c:3311]: This change is probably not needed anymore as in the case of query_config `ret` is expected to be equal to 0, right?

File: programs/ssl/ssl_server2.c [hunk 11]
```diff
@@ -4287,8 +4288,8 @@ int main( int argc, char *argv[] )
     sni_free( sni_info );
 #endif
 #if defined(MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED)
-    if( ( ret = psk_free( psk_info ) ) != 0 )
-        mbedtls_printf( "Failed to list of opaque PSKs - error was %d\n", ret );
+    if( ( psk_free_ret = psk_free( psk_info ) ) != 0 )
+        mbedtls_printf( "Failed to list of opaque PSKs - error was %d\n", psk_free_ret );
```
Comment (ronald-cron-arm) [inline programs/ssl/ssl_server2.c:4292]: I'd say that it is rather that we want to avoid the printf in case of failure rather than preserving `ret`, thus rather:
```
ret = psk_free( psk_info );
if( ( ret != 0 ) && ( opt.query_config_mode == DFL_QUERY_CONFIG_MODE ) )
    mbedtls_printf ...
```

Comment (gabor-mezei-arm) [reply programs/ssl/ssl_server2.c:4292]: Do you mean that all printf after the `exit` label should be changed to be dependent from `query_config_mode`?

Comment (ronald-cron-arm) [reply programs/ssl/ssl_server2.c:4292]: That is my understanding of the solution that we end up with. Before this PR there was just a return thus a return from the function without any output. Thus to keep the same visible behavior there shouldn't be any output when we go through the code after the exit label. Does it make sense?

Comment (gabor-mezei-arm) [reply programs/ssl/ssl_server2.c:4292]: Absolutely.

**Review by ronald-cron-arm — DISMISSED** [review]
I am happy with the final state of the code in this PR.

**Comment by yanesca** [comment]
@gabor-mezei-arm The API/ABI checking script fails on the CI, could you please rebase the PR on current development head to make it pass?

**Comment by gilles-peskine-arm** [comment]
@yanesca The ABI check compares development with merge(PR, development) so a rebase won't make any difference (in the usual case where the result of the rebase is identical to the result of the merge).

**Comment by yanesca** [comment]
@gilles-peskine-arm Ok, then I am not sure what is going on, this PR does not touch the APIs mentioned in the error message.

**Comment by gilles-peskine-arm** [comment]
I'm not sure why an [old run](https://jenkins-internal.mbed.com/blue/organizations/jenkins/mbedtls-pr-multibranch/detail/PR-3282-merge/61/pipeline) but anyway the [latest run](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbedtls-pr-multibranch/detail/PR-3282-merge/49/pipeline) passed so I'm not going to investigate further.

**Comment by yanesca** [comment]
@gilles-peskine-arm Indeed, I was looking at the wrong CI. Thank you for having had a look at it!

**Review by yanesca — APPROVED** [review]
Looks good to me.

**Review by ronald-cron-arm — APPROVED** [review]
LGTM

**Review by ronald-cron-arm — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
None of the changes seem to be applicable to 2.16, let alone 2.7. `query_config` already existed in 2.16 but it worked differently and doesn't cause similar missing cleanup. So no backports are needed.
