### PR TITLE
Fix release scripts for 3.0

### LINKED ISSUE #4744: bump_version.sh misses some places in 3.0
After running `scripts/bump_version.sh` in the 3.0 release branch:
```
$ git grep -F 2.26.0 '*' ':!ChangeLog' ':!*.md'
CMakeLists.txt:        VERSION 2.26.0)
include/mbedtls/build_info.h:#define MBEDTLS_VERSION_STRING         "2.26.0"
include/mbedtls/build_info.h:#define MBEDTLS_VERSION_STRING_FULL    "mbed TLS 2.26.0"
```

`bump_version.sh` needs to be updated to handle `build_info.h` (moved from `version.h` since https://github.com/ARMmbed/mbedtls/pull/4589) and `CMakeLists.txt` (new since https://github.com/ARMmbed/mbedtls/pull/4259).

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Adapt `bump_versions.sh` for the places where the version number appears in 3.0. Fix #4744.
* `check-generated-files -l` now lists the generated files, which would have been useful when preparing the release.

No backports needed since none of the changes are required on 2.27.

### CODE REVIEW

**Comment by Coeur** [comment]
What about also fixing `Formula/mbedtls.rb` by replacing:
```
inreplace "include/mbedtls/config.h" do |s|
```
With:
```
inreplace "include/mbedtls/mbedtls_config.h" do |s|
```
That would help Homebrew users to install mbedtls 3.0.

File: scripts/bump_version.sh [hunk 1]
```diff
@@ -81,6 +81,10 @@ then
   exit 1
 fi
 
+[ $VERBOSE ] && echo "Bumping VERSION in CMakeLists.txt"
+sed -e "s/ VERSION [0-9.]\{1,\}/ VERSION $VERSION/g" < CMakeLists.txt > tmp
```
Comment (mstarzyk-mobica) [inline scripts/bump_version.sh:85]: Why not just use `sed -i`?

Comment (mstarzyk-mobica) [reply scripts/bump_version.sh:85]: Ah, I see that it's done like this all over the file. Is this just for consistency?

**Review by mstarzyk-mobica — APPROVED** [review]

**Review by yanesca — APPROVED** [review]
LGTM
