### PR TITLE
Fix failure detection and failures in basic-build-test.sh with SSL3 in basic-build-test

### LINKED ISSUE #3178: basic-build-test.sh exits successfully even if some tests fail
`tests/scripts/basic-build-test.sh` exits successfully even if there were test failures.

I think it does make sense to run the script to completion even if there are failures. Coverage information can be useful even if some tests fail. However this should not result in a pass on the CI.

The script reports the number of failed test cases. It should `exit 1` if this number is nonzero.

### LINKED ISSUE #3179: SSLv3 failing in basic-build-tests.sh on development
In the `development` branch, `basic-build-test.sh` runs `compat.sh -m ssl3`. This makes sense since SSLv3 is deprecated but still a tested feature and the job of `basic-build-test.sh` is to measure test coverage.

`basic-build-test.sh` uses `config.py full`, which since https://github.com/ARMmbed/mbedtls/pull/2236 no longer includes `MBEDTLS_SSL_PROTO_SSL3`. So all the `ssl3` compat test cases fail.

I think that the job of `config.py full` is to include everything that fits together, even deprecated modules. For example we still include MD4 in that configuration.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Fix #3178: make basic-build-test.sh exit with a failure status if some test cases fail
* Minor log readability improvements
* Fix #3179: enable SSL3 in basic-build-test.sh

Needs partial backports. This PR is release-critical, but the backports aren't (we can check the logs manually to verify that there are no failures).

Alternative that does change the full config: https://github.com/ARMmbed/mbedtls/pull/3180

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
CI run of `basic-build-test.sh`: https://jenkins-internal.mbed.com/job/mbedtls-release-new/719/

**Comment by gilles-peskine-arm** [comment]
CI run of `basic-build-test.sh`: https://jenkins-internal.mbed.com/job/mbedtls-release-new/721/

File: tests/scripts/basic-build-test.sh [hunk 1]
```diff
@@ -104,7 +104,14 @@ echo
...
 # Step 3 - Process the coverage report
 cd ..
-make lcov |tee tests/cov-$TEST_OUTPUT
+{
+    make lcov
+    echo SUCCESS
+} | tee tests/cov-$TEST_OUTPUT
+
+if [ "$(tail -n1 tests/cov-$TEST_OUTPUT)" != "SUCCESS" ]; then
+    echo >&2 "Fatal: 'make lcov' failed"
```
Comment (mpg) [inline tests/scripts/basic-build-test.sh:131]: The commit message says "exit immediately" but I'm not seeing what part of the code actually does that.

Comment (gilles-peskine-arm) [reply tests/scripts/basic-build-test.sh:131]: Oops. I amended the commit.

**Comment by gilles-peskine-arm** [comment]
CI run of `basic-build-test.sh`: https://jenkins-internal.mbed.com/job/mbedtls-release-new/722/

**Comment by gilles-peskine-arm** [comment]
The PR CI has passed and `basic-build-test.sh` has passed. Backports can wait until after the upcoming release, since LTS branches are not affected meaningfully by the issues that this PR fixes. Merging.
