### PR TITLE
Fix ILP32 issues

### LINKED ISSUE #849: New test in 2.4.2 pk_rsa_alt segfaults on 64-bit ILP32 systems
The test added to `pk_rsa_alt` in 511f83db0712fbcb8b3a5b173ae074ae035a4748 segfaults on 64-bit ILP32 systems (eg: x86 x32, mips n32, etc). These systems have a 64-bit native word size, but store pointers in 32-bits.

Here `MBEDTLS_HAVE_INT64` is defined due to the native word size but `size_t` is still only 32-bits. This means that the check added in 2.4.2 here: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.4.2/library/pk_wrap.c#L419 does not return because all `size_t` values will fit in an `unsigned int`, and then the test segfaults because `sig_len` is `NULL`.

```
RSA_ALT consistency ............................................... 
Program received signal SIGSEGV, Segmentation fault.
0x0041e790 in rsa_alt_sign_wrap (ctx=0x65c6f0, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, p_rng=0x0)
    at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk_wrap.c:423
423	    *sig_len = rsa_alt->key_len_func( rsa_alt->key );
(gdb) bt
#0  0x0041e790 in rsa_alt_sign_wrap (ctx=0x65c6f0, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, 
    p_rng=0x0) at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk_wrap.c:423
#1  0x0041dcab in mbedtls_pk_sign (ctx=0xffffc230, md_alg=MBEDTLS_MD_NONE, hash=0xffffc170 '*' <repeats 50 times>, "\377\377", hash_len=4294967295, sig=0x0, sig_len=0x0, f_rng=0x406178 <rnd_std_rand>, 
    p_rng=0x0) at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/library/pk.c:269
#2  0x00408a3d in test_suite_pk_rsa_alt () at /build/mbedtls-Wtyzgt/mbedtls-2.4.2/tests/suites/test_suite_pk.function:496
#3  0x0040a078 in dispatch_test (cnt=1, params=0xffffc4e0) at main_test.function:424
#4  0x0040aad6 in main (argc=1, argv=0xffffda54) at main_test.function:420
```

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
1. Rebase of #900: Add a build and a test runs to `all.sh` to ensure that mbed TLS builds and works with the GCC flags `-m32` and `-mx32`. Fixes #849

2. Fix tests with forced 64-bit or 32-bit bignum limb size: execute them once, regardless of the architecture.

Internal ref: IOTSSL-1300

Note to reviewers: the first three commits are from #900 (previously approved), rebased on top of current development, which meant adjusting to the changes in `all.sh`. The subsequent commits are new, to fix issue 2 which I noticed.

Backports (of (1) + other ILP32 fixes as applicable; (2) does not apply): #1334, #1335

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
CI failed only due to timing self-test on FreeBSD (known unrelated issue), so ok to merge on that count.

File: tests/scripts/all.sh [hunk 1]
```diff
@@ -678,17 +678,6 @@ if uname -a | grep -F x86_64 >/dev/null; then
     scripts/config.pl unset MBEDTLS_AESNI_C
     scripts/config.pl unset MBEDTLS_PADLOCK_C
     make CC=gcc CFLAGS='-Werror -Wall -Wextra -DMBEDTLS_HAVE_INT64'
-
-    msg "test: gcc, force 64-bit compilation"
-    make test
```
Comment (mpg) [inline tests/scripts/all.sh]: I think this paragraph should be kept.

Also, from the commit message it looks like you were meaning to add something like:
```
msg "test: gcc, force 32-bit compilation"
make test
```
above, which you didn't.

Comment (mpg) [reply tests/scripts/all.sh]: Oh OK, this was fixed in the next commit. Cool.
