### PR TITLE
Hardening: Make `mbedtls_ssl_get_verify_result()` default to failure

### LINKED ISSUE #10373: verify_result should default to failure
### Summary

`ssl_handshake_init()` or `mbedtls_ssl_session_init()` should initialize `ssl->session_negotiate->verify_result` to an invalid result, and later MbedTLS should only set it to a valid result once the certificate has been validated(client) or understood that a certificate is not needed(server that does not require client certificates).

### System information

Mbed TLS version (number or commit id): 3.6.4 c765c831e5c2a0971410692f92f
Operating system and version: ESP-IDF 6 development FreeRTOS
Configuration (if not default, please attach `mbedtls_config.h`): attached
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): I don't think this is a compiler-related problem, but ESP-IDF 4e036983a7
Additional environment information: 

### Expected behavior

mbedtls_ssl_get_verify_result() must not return ok verify result until the certificate has been validated.

### Actual behavior

Before the handshake is started, mbedtls_ssl_get_verify_result() returns 0(success) because `ssl->session_negotiate->verify_result` is initialized to 0(success).

The documentation states it should return `0 if successful, -1 if result is not available (eg because the handshake was aborted too early), or a combination of BADCERT_xxx and BADCRL_xxx flags, see x509.h`. Seems like it should return -1 if called before handshake begins?

### Steps to reproduce

1. Create an mbedTLS client-context with a session, as-if you were going to connect
2. Before connecting, call `mbedtls_ssl_get_verify_result()`

### Additional information

Relevant documentation snippet: `With MBEDTLS_SSL_VERIFY_OPTIONAL, the user needs to call mbedtls_ssl_get_verify_result() at the right time(s), which may not be obvious`

I believe the fact that I've noticed this is an indication that ESP-IDF was calling `mbedtls_ssl_get_verify_result()` at the wrong time, which is a client-side bug outside MbedTLS, but defaulting to a failure code would make identifying this type of bug more obvious(see https://github.com/espressif/esp-idf/issues/16239)

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
Guard against a potential API misuse. Currently, when `mbedtls_ssl_get_verify_result()` is called before attempting a handshake, it returns 0 indicating success.

Change this so that we initialize the result to a new verification error value when we first initialize the session object.

Fixes #10373

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** provided
- [x] **development PR** here
- [x] **TF-PSA-Crypto PR** not required because: TLS change only
- [x] **framework PR** not required
- [x] **3.6 PR** provided #10443
- **tests**  provided

### CODE REVIEW

**Comment by irwir** [comment]
> Change this so that we initialize the result to 0xFFFFFFFF (indicating failure) when we first initialize the session object.

This solution could have been cleaner.
First, it uses `magic value` without a name.
Second, and more important, `verify_result` is essentially a collection of bit fields, but checks for individuls bits do not take into account possibility of having all bits set.

There are unused bits in 32-bit integer, it would be more appropriate to take one bit and give it a good name.

**Comment by davidhorstmann-arm** [comment]
> There are unused bits in 32-bit integer, it would be more appropriate to take one bit and give it a good name.

That's a fair point. I think I will change to this strategy, thanks!

File: include/mbedtls/x509.h [hunk 1]
```diff
@@ -104,6 +104,7 @@
 #define MBEDTLS_X509_BADCRL_BAD_MD           0x020000  /**< The CRL is signed with an unacceptable hash. */
 #define MBEDTLS_X509_BADCRL_BAD_PK           0x040000  /**< The CRL is signed with an unacceptable PK alg (eg RSA vs ECDSA). */
 #define MBEDTLS_X509_BADCRL_BAD_KEY          0x080000  /**< The CRL is signed with an unacceptable key (eg bad curve, RSA too short). */
+#define MBEDTLS_X509_VERIFY_NOT_STARTED      0x100000  /**< No verification has yet been performed (used as a safe initial value). */
```
Comment (ronald-cron-arm) [inline include/mbedtls/x509.h]: The documentation of mbedtls_ssl_get_verify_result() is:
```
/**                                                                             
 * \brief          Return the result of the certificate verification            
 *                                                                              
 * \param ssl      The SSL context to use.                                      
 *                                                                              
 * \return         \c 0 if the certificate verification was successful.         
 * \return         \c -1u if the result is not available. This may happen       
 *                 e.g. if the handshake aborts early, or a verification        
 *                 callback returned a fatal error.                             
 * \return         A bitwise combination of \c MBEDTLS_X509_BADCERT_XXX         
 *                 and \c MBEDTLS_X509_BADCRL_XXX failure flags; see x509.h.    
 */                                                                             
uint32_t mbedtls_ssl_get_verify_result(const mbedtls_ssl_context *ssl);
```
thus why not just initialize `verify_result` in `mbedtls_ssl_session` to -1?
If we stick with MBEDTLS_X509_VERIFY_NOT_STARTED, we need probably to update the above documentation.

File: library/ssl_tls.c [hunk 2]
```diff
@@ -954,6 +955,8 @@ void mbedtls_ssl_transform_init(mbedtls_ssl_transform *transform)
 void mbedtls_ssl_session_init(mbedtls_ssl_session *session)
 {
     memset(session, 0, sizeof(mbedtls_ssl_session));
+    /* Set verify_result to indicate failure by default. */
+    session->verify_result = MBEDTLS_X509_VERIFY_NOT_STARTED;
```
Comment (ronald-cron-arm) [inline library/ssl_tls.c]: What about `mbedtls_ssl_session_free()`?
We have a `mbedtls_platform_zeroize(session, sizeof(mbedtls_ssl_session));` in this function.
We should probably reset `verify_result` to its non-zero value there as well.

File: include/mbedtls/x509.h (hunk 1 above)
Comment (davidhorstmann-arm) [reply include/mbedtls/x509.h]: Ah I did not spot that we allow for a value of `-1`, thanks. In that case I can change it back to return `-1`, since verification not started is included in 'result not available'.

That allows us to fix this without changing the API.

File: library/ssl_tls.c (hunk 2 above)
Comment (davidhorstmann-arm) [reply library/ssl_tls.c]: That's a good point, I will add that.

**Comment by davidhorstmann-arm** [comment]
Comments should be addressed by these 2 new commits. I will now rebase.

**Comment by davidhorstmann-arm** [comment]
Rebased atop `development`. Only conflicts were with the merge of #10514 (both introduced a new ssl testcase and the two were similar enough that git thought they were the same).

File: ChangeLog.d/verify-result-default-value.txt [hunk 3]
```diff
@@ -0,0 +1,5 @@
+Changes
+   * Harden mbedtls_ssl_get_verify_result() against misuse.
+     Return failure if the handshake has not yet been attempted. Previously
```
Comment (ronald-cron-arm) [inline ChangeLog.d/verify-result-default-value.txt]:
```suggestion
     Return that the result is not available  if the handshake has not yet been attempted. Previously
```
?

Comment (davidhorstmann-arm) [reply ChangeLog.d/verify-result-default-value.txt]: I've reworded it to say something hopefully equivalent. Let me know if you think the new version makes sense.

File: library/ssl_tls.c [hunk 4]
```diff
@@ -2016,6 +2018,9 @@ int mbedtls_ssl_set_hs_psk(mbedtls_ssl_context *ssl,
         return MBEDTLS_ERR_SSL_HW_ACCEL_FAILED;
     }
 
+    /* Since we're not using a certificate, set verify_result to skipped */
+    ssl->session_negotiate->verify_result = MBEDTLS_X509_BADCERT_SKIP_VERIFY;
```
Comment (ronald-cron-arm) [inline library/ssl_tls.c]: This is not completely correct. In the case of early data on client side, we may call `mbedtls_ssl_set_hs_psk()` but eventually do a handshake that involves a certificate. 

Thus for TLS 1.3 I would rather do the above where we have the equivalent of the tests done in `ssl_parse_certificate_coordinate()`.

The equivalent of the test https://github.com/Mbed-TLS/mbedtls/blob/37e3dcf00d84f4783282d197549e85399a3ad7c7/library/ssl_tls.c#L6985 is:
. for TLS 1.3 client: https://github.com/Mbed-TLS/mbedtls/blob/37e3dcf00d84f4783282d197549e85399a3ad7c7/library/ssl_tls13_client.c#L2265
. for TLS 1.3 server: https://github.com/Mbed-TLS/mbedtls/blob/37e3dcf00d84f4783282d197549e85399a3ad7c7/library/ssl_tls13_server.c#L2617

The equivalent of the test https://github.com/Mbed-TLS/mbedtls/blob/37e3dcf00d84f4783282d197549e85399a3ad7c7/library/ssl_tls.c#L6991-L6992 is https://github.com/Mbed-TLS/mbedtls/blob/37e3dcf00d84f4783282d197549e85399a3ad7c7/library/ssl_tls13_server.c#L2655 and we already have `ssl->session_negotiate->verify_result = MBEDTLS_X509_BADCERT_SKIP_VERIFY;` there.

File: library/ssl_tls.c [hunk 5]
```diff
@@ -954,8 +954,8 @@ void mbedtls_ssl_transform_init(mbedtls_ssl_transform *transform)
 void mbedtls_ssl_session_init(mbedtls_ssl_session *session)
 {
     memset(session, 0, sizeof(mbedtls_ssl_session));
-    /* Set verify_result to indicate failure by default. */
-    session->verify_result = MBEDTLS_X509_VERIFY_NOT_STARTED;
+    /* Set verify_result to -1u to indicate 'result not available'. */
+    session->verify_result = 0xFFFFFFFF;
```
Comment (bensze01) [inline library/ssl_tls.c:958]: Why not use `-1u` directly?
```suggestion
    session->verify_result = -1u;
```

File: library/ssl_tls.c [hunk 6]
```diff
@@ -4571,6 +4571,9 @@ void mbedtls_ssl_session_free(mbedtls_ssl_session *session)
 #endif
 
     mbedtls_platform_zeroize(session, sizeof(mbedtls_ssl_session));
+
+    /* Set verify_result to -1u to indicate 'result not available'. */
+    session->verify_result = 0xFFFFFFFF;
```
Comment (bensze01) [inline library/ssl_tls.c:4576]: Ditto
```suggestion
    session->verify_result = -1u;
```

File: tests/suites/test_suite_ssl.function [hunk 7]
```diff
@@ -6065,7 +6065,7 @@ void verify_result_without_handshake(void)
 
     uint32_t verify_result = mbedtls_ssl_get_verify_result(&ssl);
 
-    TEST_EQUAL(verify_result, MBEDTLS_X509_VERIFY_NOT_STARTED);
+    TEST_EQUAL(verify_result, 0xFFFFFFFF);
```
Comment (bensze01) [inline tests/suites/test_suite_ssl.function:6068]: Ditto.
```suggestion
    TEST_EQUAL(verify_result, -1u);
````

File: tests/suites/test_suite_ssl.function [hunk 8]
```diff
@@ -6067,6 +6067,16 @@ void verify_result_without_handshake(void)
...
 
+    /* Set the verify result manually and check that session_free resets it. */
+
+    /* Set the verify result to 0. */
+    ssl.session_negotiate->verify_result = 0;
+
+    mbedtls_ssl_session_free(ssl.session_negotiate);
+
+    verify_result = mbedtls_ssl_get_verify_result(&ssl);
+    TEST_EQUAL(verify_result, 0xFFFFFFFF);
```
Comment (bensze01) [inline tests/suites/test_suite_ssl.function:6078]: Ditto
```suggestion
    TEST_EQUAL(verify_result, -1u);
```

File: library/ssl_tls.c (hunk 5 above)
Comment (irwir) [reply library/ssl_tls.c:958]: Maybe because _unsigned_ value with a minus _sign_ is somewhat illogical?
If all bits need to be set, a better choice might be `~(uint32_t)0`; type cast here for bit count being the same as in the variable.

Comment (bensze01) [reply library/ssl_tls.c:958]: According to the standard, [`unsigned` integers always perform modulo `2^n` arithmetic](https://en.cppreference.com/w/c/language/operator_arithmetic.html).
Since [`1u` always has the type `unsigned int`](https://en.cppreference.com/w/c/language/integer_constant.html), applying the unary negation operator results in `-1u == UINT_MAX`

Comment (irwir) [reply library/ssl_tls.c:958]: UINT_MAX does not have to be 0xFFFFFFFF in any 32-bit processor architecture.

Comment (bensze01) [reply library/ssl_tls.c:958]: Right, `verify_result` is `uint32_t`. I guess leaving it as `0xFFFFFFFF` should be fine.

**Comment by davidhorstmann-arm** [comment]
> We are left with the additional checks I suggested earlier

Whoops, sorry, I entirely forgot about those! I'll do those shortly.

**Comment by davidhorstmann-arm** [comment]
I have added these checks to the testcases. Apologies for 2 very similar commit titles for commits that do different things, I am happy to rewrite those if you'd like.

Otherwise that should be ready to review (once CI is happy).

**Comment by ronald-cron-arm** [comment]
Looking a the failures in the CI, if there is no support in the build for certificate based handshakes (`MBEDTLS_SSL_HANDSHAKE_WITH_CERT_ENABLED` not defined, we have some all.sh components like that) the code logging "Certificate verification was skipped" in ssl_client2/server2.c is not present. Thus in `tests/opt-testcases/tls13-kex-modes.sh` we can check for the log "Certificate verification was skipped" in the test cases that:
1. Have a successful handshake 
2. already check for "(Selected) key exchange mode: psk$" or "Selected key exchange mode: psk_ephemeral" (client or server) being present (not absent)  in the logs
3. depend on MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED being enabled

**Comment by davidhorstmann-arm** [comment]
Thanks for the pointers as to where the problem was! That should be fixed now (but we can see if the CI agrees).

**Comment by ronald-cron-arm** [comment]
@davidhorstmann-arm CI is still not happy. I've tried to improve the description in https://github.com/Mbed-TLS/mbedtls/pull/10442#issuecomment-4045201505 of the test cases where we should add the check for the presence of "Certificate verification was skipped" in the logs.

**Comment by davidhorstmann-arm** [comment]
Ah whoops, I forgot the 'successful handshake' part, thanks! I did previously discover that but forgot it this time. Should be an easy fix.

**Comment by davidhorstmann-arm** [comment]
CI is happy, hooray!

**Comment by ronald-cron-arm** [comment]
@bensze01 please have another look.
