### PR TITLE
Correct RSA key generation test in case of missing entropy

### LINKED ISSUE #1023: MBEDTLS_NO_PLATFORM_ENTROPY causes segfault in RSA test suite
Defining in `config.h` the option `MBEDTLS_NO_PLATFORM_ENTROPY` causes the RSA test suite to segfault on execution.

Maybe the test isn't valid with the option and is missing a dependency.

### PR DESCRIPTION
**Pull request by hanno-arm**
__Context:__ Fixes #1023 and #1024.

__Summary:__ This PR addresses the following problems:
1. The RSA key generation test initializes the RSA context after seeding the CTR DRBG random number generator. If no strong entropy is present on the system, e.g. because the configuration flag `MBEDTLS_NO_PLATFORM_ENTROPY` is set and no other sources are provided, the seeding fails and leads to an attempt to free the uninitialized RSA context in the cleanup section - this most likely results in a segmentation fault, as originally observed in #1023 and #1024.
2. The entropy self-test should also catch the problem but doesn't because the conditional `depends_on:!MBEDTLS_TEST_NULL_ENTROPY` is not parsed correctly leading to the test case being dropped.
3. In light of the _expected_ failure of the RSA key generation test when no strong entropy is present, the test must be made conditional on the presence of strong entropy. 

Fixing (1) is a line swap in `tests/suites/test_suite_rsa.function`. For (2), test suite generation script `tests/scripts/generate_code.pl` is adapted. For (3), an internal convenience preprocessor flag `MBEDTLS_ENTROPY_HAVE_STRONG` is introduced in the testfiles capturing whether some of the default strong entropy sources considered in `mbedtls_entropy_init` is enabled in the configuration, and the RSA key generation tests are made dependent on this flag.

__Internal references:__ IOTSSL-1580 and IOTSSL-1581.

__Comment for reviewing:__ There is no significant reverting of earlier changes in later commits so far, and reviewing commit-by-commit should be fine.

### CODE REVIEW

File: include/mbedtls/entropy.h [hunk 1]
```diff
@@ -55,6 +55,16 @@
...
 #define MBEDTLS_ERR_ENTROPY_FILE_IO_ERROR                 -0x003F  /**< Read/write error in file. */
 
+/* Indicates whether at least one standard strong entropy source is enabled. */
+#if defined(MBEDTLS_TEST_NULL_ENTROPY) ||             \
+    ( !defined(MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES) && \
+      ( !defined(MBEDTLS_NO_PLATFORM_ENTROPY)  ||     \
+         defined(MBEDTLS_HAVEGE_C)             ||     \
+         defined(MBEDTLS_ENTROPY_HARDWARE_ALT) ||     \
+         defined(ENTROPY_NV_SEED) ) )
+#define MBEDTLS_ENTROPY_HAVE_STRONG
```
Comment (RonEld) [inline include/mbedtls/entropy.h]: why is `MBEDTLS_TEST_NULL_ENTROPY` considered STRONG?
Why is `MBEDTLS_HAVEGE_C` considered strong?
Actually, I would consider only `MBEDTLS_ENTROPY_HARDWARE_ALT` as a strong source. Perhaps `ENTROPY_NV_SEED` as well, depending on the implementation

Comment (hanno-arm) [inline include/mbedtls/entropy.h]: @RonEld This is not my judgement but taken from what's considered strong in `mbedtls_entropy_init`, see https://github.com/ARMmbed/mbedtls/blob/development/library/entropy.c#L69.

Comment (RonEld) [inline include/mbedtls/entropy.h]: I see this now, thanks.

Comment (hanno-arm) [inline include/mbedtls/entropy.h]: @RonEld But now you mentioned it, it's probably better to define `MBEDTLS_ENTROPY_HAVE_STRONG` in the testing files only, because it is not relevant to the library otherwise.

**Comment by hanno-arm** [comment]
I'll rework the PR to move the flag indicating the presence of standard strong entropy sources (as judged by `mbedtls_entropy_init`) to the test files.

**Comment by hanno-arm** [comment]
@RonEld I've updated the PR, could you have another look?

File: tests/suites/helpers.function [hunk 2]
```diff
@@ -103,6 +103,21 @@ static int test_errors = 0;
...
+
+/* Indicates whether we expect mbedtls_entropy_init
+ * to initialize some strong entropy source. */
+#if defined(MBEDTLS_TEST_NULL_ENTROPY) ||             \
+    ( !defined(MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES) && \
+      ( !defined(MBEDTLS_NO_PLATFORM_ENTROPY)  ||     \
+         defined(MBEDTLS_HAVEGE_C)             ||     \
+         defined(MBEDTLS_ENTROPY_HARDWARE_ALT) ||     \
+         defined(ENTROPY_NV_SEED) ) )
+#define ENTROPY_HAVE_STRONG
```
Comment (RonEld) [inline tests/suites/helpers.function]: Although this is for tests only, I would rename it to `MBEDTLS_ENTROPY_HAVE_STRONG`

**Comment by hanno-arm** [comment]
@RonEld @andresag01 Added a commit renaming `MBEDTLS_ENTROPY_HAVE_STRONG` to content `tests/scripts/check-names.pl` (reason for previous CI failure).

**Comment by andresag01** [comment]
This PR also fixes: https://github.com/ARMmbed/mbedtls/issues/931

**Comment by hanno-arm** [comment]
Re-pushed last commit to trigger CI which didn't seem to be working.

**Comment by hanno-arm** [comment]
retest CI
