### PR TITLE
Fix misuse of MD API in SSL constant-flow HMAC

### LINKED ISSUE #4118: stm32 sha1 acceleration does not work since 2.16.8 release
I'm using mbedtls on stm32f7 board. Until 2.16.7 it worked fine with alternative functions providing hw acceleration (same as ones in mbedos (https://github.com/ARMmbed/mbed-os/blob/master/connectivity/drivers/mbedtls/TARGET_STM/sha1_alt.cpp)). I have recently tried to update to actual 2.16 tip but here I noticed that my webserver does not work and reports `SSL - Verification of the message MAC failed` when `MBEDTLS_SHA1_ALT` is defined. With internal SHA1 everything works fine.

With bisecting I have found that it started with this commit de02b580c8bd2d122746616205344dae4a2e9243. I do not see on the first sight what could be the issue here, hopefuly someone with more knowledge can help...

### PR DESCRIPTION
**Pull request by mpg**
## Description

Fixes #4118

The sequence of calls starts-update-starts-update-finish is not a
guaranteed valid way to abort an operation and start a new one. Our
software implementation just happens to support it, but alt
implementations may very well not support it.

## Status
**READY**

## Requires Backporting

Yes

- [x] 2.x - #4541 
- [x] 2.16 - #4542 

## Migrations

NO

## Additional comments

See #4524 for how to avoid similar bugs in the future.

## Todos

- [x] Tests - omitted for now, but tracked in #4524
- [x] Documentation
- [x] Changelog updated
- [x] Backported

### CODE REVIEW

File: ChangeLog.d/fix-ssl-cf-hmac-alt.txt [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Bugfix
+   * Fix a regression introduced in 2.24.0 which broke (D)TLS CBC ciphersuites
+     (when the encrypt-then-MAC extension is not in use) when an ALT
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/fix-ssl-cf-hmac-alt.txt:3]: Nitpick: only some alt implementations are affected.

**Review by gilles-peskine-arm — DISMISSED** [review]

**Review by daverodgman — COMMENTED** [review]
Fix seems good. Should we update the documentation for mbedtls_md_starts to say that you need to first call mbedtls_md_finish if you are reusing a context?

**Comment by gilles-peskine-arm** [comment]
Re. documentation: more documentation wouldn't hurt, but I think what's there is already clear enough (you must call setup before starts and starts before update; you must call finish after update; you may call starts after finish).

**Comment by daverodgman** [comment]
> Re. documentation: more documentation wouldn't hurt, but I think what's there is already clear enough (you must call setup before starts and starts before update; you must call finish after update; you may call starts after finish).

I think it isn't 100% clear - but it's a minor nitpick. I'll approve as-is & leave it to @mpg to decide on that point.

**Review by daverodgman — DISMISSED** [review]

**Comment by mpg** [comment]
@daverodgman I've left a note about documentation in the issue about testing - I think documentation and testing go well together as we should make sure what's documented and what's tested is the same thing.

**Review by daverodgman — APPROVED** [review]

**Review by gilles-peskine-arm — APPROVED** [review]
