### PR TITLE
Test and fix mutex usage

### LINKED ISSUE #4017: Problem with mutex used in CTR_DRBG and HMAC_DRBG
## Bug

**OS**  
embedded system

**mbed TLS build:**  
Version: 2.7.17

Hello everyone.

I am trying to upgrade the library from version 2.7.17 to 2.7.18.
In my application I use the mbedtls library together with curl.
After updating, my device stops connecting to servers properly after some time.

My application control the number of mutexes used by mbedtls. Logs show that there are no free mutexes to use and a new one could not be initialized.

This has to do with 'In CTR_DRBG and HMAC_DRBG, don't reset the reseed interval in seed (). Fixes # 2927. '

In the mbedtls_crt_drbg_free and mbedtls_hmac_drbg_free functions, a new mutex is initialized at the end of these functions. What if we don't want to use mbedtls_crt_drbg_context or mbedtls_hmac_drbg_context anymore?

In the library I found this function:
https://github.com/ARMmbed/mbedtls/blob/d0c7b79170dbfa42932523c8b4dd326559cf698e/library/ecp.c#L2241
which uses the local ecp_drbg_context. After executing the function, ecp_drbg_context is released but the mutex is initialized and its address is dropped.

Perhaps this is the real problem. I cannot define it.

### LINKED ISSUE #4022: Test mutex resource management
The goal of this issue is to test mutex resource management. We should run the unit tests (and optionally SSL tests) in a mode that would detect:

* Calling `mbedtls_mutex_lock` or `mbedtls_mutex_unlock` or `mbedtls_mutex_free` on a mutex that hasn't been initialized.
* Calling `mbedtls_mutex_lock` twice on a mutex with no intervening unlock.
* Calling `mbedtls_mutex_unlock` on a mutex that isn't locked.
* Calling `mbedtls_mutex_lock` or `mbedtls_mutex_unlock` on a mutex that has been freed.
* Forgetting to call `mbedtls_mutex_free` on a mutex that has been initialized, as reported in https://github.com/ARMmbed/mbedtls/issues/4017.

Note that this does not require any multithreaded execution. The proper use of the mutex to protect data structures is out of scope.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
* Add a framework to test the correct usage of mutex objects: paring of init/free and lock/unlock, etc. Fix #4022.
* Fix a resource leak due to a mutex being left in the initialized state after `mbedtls_ctr_drbg_free` and `mbedtls_hmac_drbg_free`. Fix #4017, #4045, #4071.

And also:

* Add some missing calls to `mbedtls_psa_crypto_free` under `MBEDTLS_USE_PSA_CRYPTO` in unit tests and SSL test programs.
* Use the mutex usage verification framework in `ssl_client2` and `ssl_server2`.

See https://github.com/ARMmbed/mbedtls/pull/4090 for a discussion of the design.

Note for reviewers: the commit structure is the same as in https://github.com/ARMmbed/mbedtls/pull/4090, namely:

1. Branch-specific preparation (2.7: odds and ends; development: `PSA_INIT` and `PSA_DONE` cleanup).
2. Set up the test framework. Essentially the same code, but in 2.7 it all goes into `helpers.function` whereas in development it's more cleanly organized under `tests/src`, with declarations under `tests/include`, and with names prefixed with `mbedtls_test_`.
3. Fix the bugs (CTR_DRBG, HMAC_DRBG, a test function, RSA). Straightforward cherrypicks.
4. Only in development: testing in SSL programs.

Backports: https://github.com/ARMmbed/mbedtls/pull/4090 → 2.7, #4154 → 2.16.

Note (added by mpg): the 2.16 backport should probably be based on the 2.7 PR, as it has the closest file structure (monolithic `tests/helpers.function` and no PSA).

### CODE REVIEW

**Comment by mpg** [comment]
I just did a quick design review of the part that differ from the 2.7 version, namely testing of mutexes in `ssl_client2` and `ssl_server2`. I really like the way it's done, and I'm very happy we previously made changes to the structure of the test code and build system that make this possible.

**Comment by mpg** [comment]
@gilles-peskine-arm both prerequisites have been merged now. Feel free to rebase (also to resolve conflicts) and request a review from me when this is ready. (I haven't done more than a high-level design review here so far.)

File: programs/ssl/ssl_test_lib.h [hunk 1]
```diff
@@ -219,5 +219,36 @@ int idle( mbedtls_net_context *fd,
...
 
+#if defined(MBEDTLS_TEST_HOOKS)
+/** Initialize whatever test hooks are enabled by the compile-time
+ * configuration and make sense for the TLS test programs. */
+void test_hooks_init( void );
+
+/** Check if any test hooks detected a problem.
+ *
+ * If a problem was detected, make sure to print an explanation to stderr,
+ * either at the time of detection or during the call to this function.
```
Comment (mpg) [inline programs/ssl/ssl_test_lib.h:230]: I find this unclear. Is this a description of what this function does, of what the caller should do, or what somebody else should does or should do?

**Review by mpg — APPROVED** [review]
This looks good to me, except one place where I think internal documentation could be improved.

I also tested that without the last commit, building with the full config then running `ssl-opt.sh -f Default` results in mutex leaks being detected and reported in the server output (`[mutex: 2 leaked] Test hooks detected errors.`) and `ssl-opt.sh` failing as expected.

File: programs/ssl/ssl_test_lib.h [hunk 2]
```diff
@@ -226,9 +226,16 @@ void test_hooks_init( void );
 
 /** Check if any test hooks detected a problem.
  *
- * \note When implementing a test hook, make sure to print a message
- *       to standard error either at the time the problem is detected
- *       or during the execution of this function.
+ * If a problem was detected, it's ok for the calling program to keep going,
+ * but should ultimately exit with an error status.
```
Comment (mpg) [inline programs/ssl/ssl_test_lib.h:230]: Type: but _it_ should.

Comment (gilles-peskine-arm) [reply programs/ssl/ssl_test_lib.h]: Fixed by amending the last commit.

**Review by mpg — DISMISSED** [review]
Thanks for clarifying the internal documentation! Looks all good to me now.

**Review by mpg — APPROVED** [review]
Still looking good to me.

**Review by chris-jones-arm — COMMENTED** [review]
I think there's one thing that could be made clearer but overall I'm happy with the additional SSL tests.

I will also note, as @mpg mentioned, I think this is a good example and way of performing invasive tests with test hooks.

File: programs/ssl/ssl_client2.c [hunk 3]
```diff
@@ -734,6 +734,8 @@ int main( int argc, char *argv[] )
     mbedtls_memory_buffer_alloc_init( alloc_buf, sizeof(alloc_buf) );
 #endif
 
+    test_hooks_init( );
```
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply programs/ssl/ssl_client2.c:738]: There are two schools of thought:

1. `test_hooks_xxx` does whatever it can, which happens to be nothing if `MBEDTLS_TEST_HOOKS` is disabled.
2. `test_hooks_xxx` is conditional to `MBEDTLS_TEST_HOOKS`.

I don't particularly care here, so I switched from (1) to (2).

It's possible that `test_hooks_xxx` could expand to cover things that don't require `MBEDTLS_TEST_HOOKS` (for example, things where it can work through platform functions). But we can change how the functions are called if and when that happens.

**Review by mpg — DISMISSED** [review]
I agree with Gilles that he two ways of doing this are both OK, so I'm happy with the new version as well.

**Comment by mpg** [comment]
The failure in the pr-merge job was caused by an infrastructure issue, so it can be ignored for the purpose of merging this PR.

File: programs/ssl/ssl_client2.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (chris-jones-arm) [reply programs/ssl/ssl_client2.c:738]: I completely agree. I'm not opposed to (1) in general indeed there are some situations in which that would be clearer however in this situation with only one reference to test hooks I prefer (2). Thanks for making the change.

**Review by chris-jones-arm — DISMISSED** [review]
Thanks for the change, I'm happy with this now.

**Comment by gilles-peskine-arm** [comment]
I fixed a typo in a comment that happened to catch my eye. There's a merge conflict, so I'll rebase and push a new version with the same history except that I'll squash the typo-fixing comments. I've uploaded the current state as https://github.com/gilles-peskine-arm/mbedtls/tree/test-mutex-usage-count-development-3.

**Comment by gilles-peskine-arm** [comment]
An entropy double-free (i.e. `mbedtls_entropy_free(&ctx); mbedtls_entropy_free(&ctx);` did not work, for the same reason that RSA double-free did not work: that did a mutex double-free, which is not supported. This was revealed by the new `test_suite_random` failing after the last rebase. I pushed two more commits to fix that. They should be backported (after CI and reviewer feedback).

**Review by mpg — DISMISSED** [review]
Looks good to me. Thanks for finding and fixing this.

**Comment by gilles-peskine-arm** [comment]
I just noticed I had an uncommitted comment. I amended the last commit to add it.

**Review by mpg — APPROVED** [review]
Thanks for adding the comment. Looking even better to me.

**Review by chris-jones-arm — APPROVED** [review]
New entropy double-free changes looks good to me.

**Comment by gilles-peskine-arm** [comment]
pr-merge hasn't run, but the target branch is identical to the merge-base, so it would be a duplicate of pr-head.
