### PR TITLE
Fixes for invalid printf format specifiers

### LINKED ISSUE #1534: Don't use %d printf format string for size_t variables
There are multiple places in the library, e.g. https://github.com/ARMmbed/mbedtls/blob/90226be77957608b89f409ad851c4e79c46849a1/library/ssl_tls.c#L2472 where the value of variables of type `size_t` is formatted using the `%d`-flag for integers when being printed for debugging purposes. Depending on the platform, this can lead to wrong output or crash.

The correct format string `%zu` is not used as it is not supported by Visual Studio versions prior to 2013.

One possible fix which prints the correct output most of the time and is not endangering a crash is to use `%lu` instead while explicitly casting the respective variable to `unsigned long` in debugging calls.

### PR DESCRIPTION
**Pull request by paul-elliott-arm**
## Description

Fixes for printf format specifiers, where they have been flagged as invalid sizes by coverity, and one case where the variables were completely missing. There is a possiblity there are more of these in the code base that have not been caught yet, but hopefully fixes for these will follow as coverity picks them up. Note that this patch uses %zu and %hhu, both of which require C99 or later.

## Status
**READY**

Scope of patch now to include adding warnings in to catch further instances of this, and fixes for the further instances.

This patch fixes #1534 and #3957

## Additional comments
I have posted to the list about potential issues from using the C99 specific printf format specifiers. %z is the only way of working around having it build safely in both 32 and 64 bit, however this in itself brings portability issues. Hopefully, given the standard is 10 years old, this won't be too much of an issue. Given the C99 spec, though I am not considering these fixes for backports.

### CODE REVIEW

File: library/ssl_cli.c [hunk 1]
```diff
@@ -1922,10 +1922,10 @@ static int ssl_parse_server_hello( mbedtls_ssl_context *ssl )
     }
 
     MBEDTLS_SSL_DEBUG_MSG( 3, ( "server hello, current time: %lu",
-                           ( (uint32_t) buf[2] << 24 ) |
-                           ( (uint32_t) buf[3] << 16 ) |
-                           ( (uint32_t) buf[4] <<  8 ) |
-                           ( (uint32_t) buf[5]       ) ) );
+                           (uint32_t)( (uint32_t) buf[2] << 24 ) |
```
Comment (gilles-peskine-arm) [inline library/ssl_cli.c:1925]: This is still wrong: the format is `%lu` but the argument type is `uint32_t`. Possible fixes:

* Make the format `%u` and leave the argument uncast. This is wrong on platforms where `unsigned int` is less than 32 bits, but Mbed TLS assumes that `unsigned int` is at least 32-bits anyway. It's obviously correct if `uint32_t` is an alias for `unsigned int`. It's also correct if `unsigned int` is 33 bits or more since the argument is promoted to `int` or `unsigned` and both are valid arguments to a `%u` specifier. I'm not sure if it's correct on hypothetical platforms where `uint32_t` and `unsigned` are both 32-bit types but they have different representations
* Keep the format as `%lu` and cast the argument to `unsigned long`.

File: library/ssl_msg.c [hunk 2]
```diff
@@ -2980,15 +2982,15 @@ int mbedtls_ssl_prepare_handshake_record( mbedtls_ssl_context *ssl )
...
+        MBEDTLS_SSL_DEBUG_MSG( 1, ( "handshake message too short: %zu",
                             ssl->in_msglen ) );
         return( MBEDTLS_ERR_SSL_INVALID_RECORD );
     }
 
     ssl->in_hslen = mbedtls_ssl_hs_hdr_len( ssl ) + ssl_get_hs_total_len( ssl );
 
     MBEDTLS_SSL_DEBUG_MSG( 3, ( "handshake message: msglen ="
-                        " %d, type = %d, hslen = %d",
+                        " %zu, type = %hhu, hslen = %zu",
```
Comment (gilles-peskine-arm) [inline library/ssl_msg.c:2993]: You can't actually pass a `short`, `char` or `float` to `printf` and friends: they're variadic functions, whose arguments are promoted. Both `%d` and `%u` are correct specifiers. (`%d` is only correct if the actual value is less than `INT_MAX`, which is always the case for Mbed TLS since we don't support platforms where `CHAR_BIT > 8`.) The `h` and `hh` modifiers are only useful for `scanf` and for `%n`. So I think we shouldn't use `%hhu` or even `%hu`, which reduced printf libraries might not implement, and stick to `%u`.

File: library/ssl_cli.c [hunk 3]
```diff
@@ -687,7 +687,7 @@ static int ssl_write_session_ticket_ext( mbedtls_ssl_context *ssl,
         return( 0 );
 
     MBEDTLS_SSL_DEBUG_MSG( 3,
-        ( "sending session ticket of length %d", tlen ) );
+        ( "sending session ticket of length %zu", tlen ) );
```
Comment (gilles-peskine-arm) [inline library/ssl_cli.c:690]: Is there a GCC or Clang option (`-Wformat=…`) that we could enable to avoid such errors in the future?

**Review by gilles-peskine-arm — COMMENTED** [review]
I've taken a first look. I haven't reviewed all the changes and haven't done a search for other possibly needed changes.

File: library/ssl_cli.c (hunk 3 above)
Comment (paul-elliott-arm) [reply library/ssl_cli.c:690]: Yes, as it turns out we were not actually getting ANY warnings for MBEDTLS_SSL_DEBUG_MSG. The scope of this patch has just changed slightly (found a tonne more warnings), so will push second pass when that is done

File: library/ssl_msg.c (hunk 2 above)
Comment (paul-elliott-arm) [reply library/ssl_msg.c:2993]: Ok, I will admit I wasn't sure myself - %hh was introduced in C99 as well, and proved slightly devisive (some people did not believe it necessary), will reduce to %u in next patch

File: library/ssl_cli.c (hunk 1 above)
Comment (paul-elliott-arm) [reply library/ssl_cli.c:1925]: Just realised this when the warning finally threw on it. The original coverity bug was that the result of the shifts is unsigned int, rather than unsigned long, and I clearly misrread it (and this was before I realised we were not getting any warnings). Will fix in next patch.

**Comment by gilles-peskine-arm** [comment]
I expect that most of these issues also apply to LTS branches. We shouldn't introduce a dependency on `%zu` in LTS branches. So we need to figure out what to do there.

Casting to `unsigned long` and using `%lu` is correct C but truncates the values on platforms where `ULONG_MAX > SIZE_MAX` (such as 64-bit Windows). Maybe that's good enough for log entries, which is what most of the printf calls do (but if we choose that, we should document it). Note that problematic cases would already be problematic today (either truncating a 64-bit value to 32 bits, or outright broken because they're passing a 64-bit value on the stack and the function consumes a 32-bit value).

**Review by daverodgman — COMMENTED** [review]
The conversions look correct to me - however the question remains on %zu introducing a C99 dependency (note however that there seem to be a couple already in memory_buffer_alloc.c)

**Comment by gilles-peskine-arm** [comment]
@daverodgman We officially use C89 on 2.7 and 2.16, but C99 on development. We don't assume a full C99 library though (and even with compiler features, we're conservative, mostly for the sake of MSVC). Printf specifier support is an area where embedded libc often omit many features. I think `%zu` is generally ok. [Nobody complained on the mailing list when we asked](https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-August/000172.html).

**Review by daverodgman — APPROVED** [review]

**Comment by daverodgman** [comment]
In that case, I think this is fine for development, and for the backports, we obviously should backport the bugfix re. PSA_ITS_STORAGE_FILENAME_LENGTH, but probably can skip the %zu changes.

**Comment by gilles-peskine-arm** [comment]
No LTS branch has any PSA stuff.

CI is still unhappy.

File: library/ssl_msg.c [hunk 4]
```diff
@@ -4620,14 +4622,14 @@ static int ssl_buffer_future_record( mbedtls_ssl_context *ssl,
...
+        MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffering of future epoch record of size %zu would exceed the compile-time limit %d (already %zu bytes buffered) -- ignore\n",
+                        rec->buf_len, MBEDTLS_SSL_DTLS_MAX_BUFFERING,
+                        hs->buffering.total_bytes_buffered ) );
         return( 0 );
     }
 
     /* Buffer record */
-    MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffer record from epoch %u",
+    MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffer record from epoch %d",
                                 ssl->in_epoch + 1 ) );
```
Comment (gabor-mezei-arm) [inline library/ssl_msg.c:4633]: The signedness of the variable should be kept.
```suggestion
    MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffer record from epoch %u",
                                ssl->in_epoch + 1U ) );
```

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]

File: library/ssl_msg.c (hunk 4 above)
Comment (gabor-mezei-arm) [reply library/ssl_msg.c]: The `U` suffix is necessary to the expression value be unsigned.

Comment (paul-elliott-arm) [reply library/ssl_msg.c]: Doh, sorry. For some reason the build I did didn't catch this. Fixed.

**Comment by paul-elliott-arm** [comment]
Rebased as a community contribution conflicted

**Review by gabor-mezei-arm — DISMISSED** [review]

**Comment by mpg** [comment]
This has one approval and apparently two other reviewers on previous versions, so I'm removing the label "needs: reviewer", based on the assumption that either @gilles-peskine-arm or @daverodgman will review the changes since your previous review. (Perhaps you want to coordinate to avoid duplicated work here.)

**Comment by gilles-peskine-arm** [comment]
I intend to review this week. If it turns out I can't, I'll go looking for someone else.

File: library/ssl_msg.c [hunk 5]
```diff
@@ -4325,31 +4325,31 @@ static int ssl_buffer_message( mbedtls_ssl_context *ssl )
                     {
                         /* If we can't buffer a future message because
                          * of space limitations -- ignore. */
-                        MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffering of future message of size %u would exceed the compile-time limit %u (already %u bytes buffered) -- ignore\n",
-                             (unsigned) msg_len, MBEDTLS_SSL_DTLS_MAX_BUFFERING,
-                             (unsigned) hs->buffering.total_bytes_buffered ) );
+                        MBEDTLS_SSL_DEBUG_MSG( 2, ( "Buffering of future message of size %zu would exceed the compile-time limit %d (already %zu bytes buffered) -- ignore\n",
+                             msg_len, MBEDTLS_SSL_DTLS_MAX_BUFFERING,
```
Comment (gilles-peskine-arm) [inline library/ssl_msg.c:4329]: `MBEDTLS_SSL_DTLS_MAX_BUFFERING` could be defined as `1234L` or `0x123456789a`, so we don't know whether it fits `int`. It should be cast to a `size_t`.

Applies everywhere `MBEDTLS_SSL_DTLS_MAX_BUFFERING` is printed out.

File: library/ssl_srv.c [hunk 6]
```diff
@@ -1116,7 +1116,7 @@ static int ssl_ciphersuite_match( mbedtls_ssl_context *ssl, int suite_id,
             mbedtls_ssl_sig_hash_set_find( &ssl->handshake->hash_algs, sig_type ) == MBEDTLS_MD_NONE )
         {
             MBEDTLS_SSL_DEBUG_MSG( 3, ( "ciphersuite mismatch: no suitable hash algorithm "
-                                        "for signature algorithm %d", sig_type ) );
+                                        "for signature algorithm %u", sig_type ) );
```
Comment (gilles-peskine-arm) [inline library/ssl_srv.c:1119]: As line 301

File: library/ssl_srv.c [hunk 7]
```diff
@@ -298,13 +298,13 @@ static int ssl_parse_signature_algorithms_ext( mbedtls_ssl_context *ssl,
         {
             mbedtls_ssl_sig_hash_set_add( &ssl->handshake->hash_algs, sig_cur, md_cur );
             MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello v3, signature_algorithm ext:"
-                                        " match sig %d and hash %d",
+                                        " match sig %u and hash %u",
```
Comment (gilles-peskine-arm) [inline library/ssl_srv.c:301]: `mbedtls_pk_type_t` and `mbedtls_md_type_t` are enums. In C, the size of an enumerated type is implementation-defined and can be as large as the compiler wants. ([Cppreference says otherwise, but that's in C++](https://en.cppreference.com/w/cpp/language/enum): in [C99](http://www.iso-9899.info/n1256.html#6.7.2.2p4) and [C11](http://www.iso-9899.info/n1570.html#6.7.2.2p4) there is no upper limit). Therefore `sig_cur` and `md_cur` need to be cast. We know that the values are small positive values, so a cast to `unsigned` is fine.

Same with `md_cur` in the else branch just below.

File: library/ssl_srv.c [hunk 8]
```diff
@@ -2274,7 +2274,7 @@ static int ssl_parse_client_hello( mbedtls_ssl_context *ssl )
         else
         {
             MBEDTLS_SSL_DEBUG_MSG( 3, ( "no hash algorithm for signature algorithm "
-                                        "%d - should not happen", sig_alg ) );
+                                        "%u - should not happen", sig_alg ) );
```
Comment (gilles-peskine-arm) [inline library/ssl_srv.c:2277]: As line 301

File: library/ssl_srv.c [hunk 9]
```diff
@@ -3502,7 +3502,7 @@ static int ssl_prepare_server_key_exchange( mbedtls_ssl_context *ssl,
             md_alg = MBEDTLS_MD_NONE;
         }
 
-        MBEDTLS_SSL_DEBUG_MSG( 3, ( "pick hash algorithm %d for signing", md_alg ) );
+        MBEDTLS_SSL_DEBUG_MSG( 3, ( "pick hash algorithm %u for signing", md_alg ) );
```
Comment (gilles-peskine-arm) [inline library/ssl_srv.c:3505]: As line 301

File: library/ssl_tls.c [hunk 10]
```diff
@@ -897,15 +897,15 @@ static int ssl_populate_transform( mbedtls_ssl_transform *transform,
     cipher_info = mbedtls_cipher_info_from_type( ciphersuite_info->cipher );
     if( cipher_info == NULL )
     {
-        MBEDTLS_SSL_DEBUG_MSG( 1, ( "cipher info for %d not found",
+        MBEDTLS_SSL_DEBUG_MSG( 1, ( "cipher info for %u not found",
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:900]: Same as `ssl_srv.c` line 301

File: library/ssl_tls.c [hunk 11]
```diff
@@ -897,15 +897,15 @@ static int ssl_populate_transform( mbedtls_ssl_transform *transform,
...
                                     ciphersuite_info->cipher ) );
         return( MBEDTLS_ERR_SSL_BAD_INPUT_DATA );
     }
 
     md_info = mbedtls_md_info_from_type( ciphersuite_info->mac );
     if( md_info == NULL )
     {
-        MBEDTLS_SSL_DEBUG_MSG( 1, ( "mbedtls_md info for %d not found",
+        MBEDTLS_SSL_DEBUG_MSG( 1, ( "mbedtls_md info for %u not found",
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:908]: Same as `ssl_srv.c` line 301

File: library/ssl_tls.c [hunk 12]
```diff
@@ -2151,7 +2151,7 @@ int mbedtls_ssl_write_certificate( mbedtls_ssl_context *ssl )
         n = crt->raw.len;
         if( n > MBEDTLS_SSL_OUT_CONTENT_LEN - 3 - i )
         {
-            MBEDTLS_SSL_DEBUG_MSG( 1, ( "certificate too large, %d > %d",
+            MBEDTLS_SSL_DEBUG_MSG( 1, ( "certificate too large, %zu > %d",
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:2154]: Same as `ssl_msg.c` line 4329 for `MBEDTLS_SSL_OUT_CONTENT_LEN`

File: library/ssl_tls.c [hunk 13]
```diff
@@ -2644,7 +2644,7 @@ static int ssl_parse_certificate_verify( mbedtls_ssl_context *ssl,
     if( ssl->session_negotiate->verify_result != 0 )
     {
         MBEDTLS_SSL_DEBUG_MSG( 3, ( "! Certificate verification flags %x",
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:2646]: Not strictly speaking in scope, but this is a 32-bit flag mask, so `%08x` would make more sense.

File: library/ssl_tls.c [hunk 14]
```diff
@@ -6086,7 +6086,8 @@ void mbedtls_ssl_handshake_free( mbedtls_ssl_context *ssl )
                 }
                 else
                 {
-                    MBEDTLS_SSL_DEBUG_MSG( 2, ( "Reallocating in_buf to %d", buf_len ) );
+                    MBEDTLS_SSL_DEBUG_MSG( 2, ( "Reallocating in_buf to %lu",
+                                                (unsigned long) buf_len ) );
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:6090]: [`buf_len` should have been a `size_t`](https://github.com/ARMmbed/mbedtls/pull/3809#discussion_r513060447). I think here it would be better to use `%zu` and cast to `size_t`. When we rework #3809, we'll remove the cast.

Same with the out case below.

**Review by gilles-peskine-arm — DISMISSED** [review]
I've made a first pass where I reviewed:

* The changes other than `MBEDTLS_SSL_DEBUG_MSG` calls.
* The changes in `MBEDTLS_SSL_DEBUG_MSG` calls.

I have yet to review whether all the necessary changes to `MBEDTLS_SSL_DEBUG_MSG` have been made.

Given the size of the changes and its potential to conflict with pretty much any SSL changes, please prioritize rework on this PR and make it as easy as possible to review later iterations. This means no rebasing: make all changes in separate commits.

For future reference, please don't make a single giant commit like this. This should have been:

1. Enable more compilation warnings.
2. Declare `mbedtls_debug_print_msg` as printf-like.
3. One or more commits fixing `ssl/*.c`.
4. The PSA ITS change (except I don't see why it was done — a commit message should have explained why).
5. Changelog entry.

I'd in fact prefer to split this commit as indicated above, but I won't insist on it in the interest of wrapping this PR up quickly. If you do split the commit, please do it BEFORE any rework, i.e. the new commit sequence should reach content that's identical to 32832ddc9e460a4fd6089e19cb11acc1955b25fa.

File: library/psa_its_file.c [hunk 15]
```diff
@@ -51,6 +51,7 @@
 #define PSA_ITS_STORAGE_SUFFIX ".psa_its"
 #define PSA_ITS_STORAGE_FILENAME_LENGTH         \
     ( sizeof( PSA_ITS_STORAGE_PREFIX ) - 1 + /*prefix without terminating 0*/ \
+      16 + /*UID (64-bit number in hex)*/                               \
```
[the remark this answers is not in the document]
Comment (paul-elliott-arm) [reply library/psa_its_file.c:54]: This was caught by one of the printf warning flags. Basically the buffer is not big enough - the format specifier used is PSA_ITS_STORAGE_FILENAME_PATTERN or "%08lx%08lx". Each of those %08lx 's could product a 16 byte hex number, which would overflow the buffer.
The storage format has not changed, but this bug has potentially been with us for some time.

[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply library/psa_its_file.c:54]: Each `%08lx` prints a 32-bit number, so won't print more than 8 characters, making the total 16 characters for a 64-bit number. The 64-bit number is printed in two parts (upper then lower 32 bits) so that the code works on 32-bit platforms.

[the remark this answers is not in the document]
Comment (paul-elliott-arm) [reply library/psa_its_file.c:54]: Ah. This is why I already had to tame down that warning. In fairness to it, the input fed into it is a 64 bit number each time, however it doesn't take notice the shifted / masked part. Its a shame, in that this warning could be rather useful, however it tends to catch false positives a lot.

[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply library/psa_its_file.c:54]: Does it help to change `uid >> 32` to `( uid >> 32 ) & 0xffffffff`?

**Comment by paul-elliott-arm** [comment]
Commits split up as requested, although this should be exactly the same code as before. I will now address the rework.

**Review by gilles-peskine-arm — COMMENTED** [review]
Thank you for splitting the commit and writing informative commit messages.

**Comment by gilles-peskine-arm** [comment]
For completeness, I've written a script that uses the Clang AST tools to detect calls to `mbedtls_debug_print_msg()` and check printf formats against the type of the corresponding argument. With the library from 5353e10ccc6e5c55fdd7be270089e2cbb628e773 and the script at 5291b9f353ad176efc02d5865e99599537f8f012, after `scripts/config.py full`, here's what it has to say:
```
library/ssl_cli.c:843: Invalid type for format %d: mbedtls_ssl_srtp_profile
library/ssl_cli.c:2631: Invalid type for format %zu: unsigned long
library/ssl_msg.c:947: Invalid type for format %zu: unsigned long
library/ssl_msg.c:1627: Invalid type for format %zu: unsigned long
library/ssl_msg.c:2233: Invalid type for format %zu: unsigned long
library/ssl_msg.c:2289: Invalid type for format %zu: unsigned long
library/ssl_srv.c:300: Invalid type for format %u: mbedtls_pk_type_t
library/ssl_srv.c:300: Invalid type for format %u: mbedtls_md_type_t
library/ssl_srv.c:306: Invalid type for format %u: mbedtls_md_type_t
library/ssl_srv.c:1118: Invalid type for format %u: mbedtls_pk_type_t
library/ssl_srv.c:2276: Invalid type for format %u: mbedtls_pk_type_t
library/ssl_srv.c:3505: Invalid type for format %u: mbedtls_md_type_t
library/ssl_tls.c:900: Invalid type for format %u: mbedtls_cipher_type_t
library/ssl_tls.c:908: Invalid type for format %u: mbedtls_md_type_t
library/ssl_tls.c:2154: Invalid type for format %zu: unsigned long
library/ssl_tls.c:2770: Invalid type for format %zu: unsigned long
```

File: CMakeLists.txt [hunk 16]
```diff
@@ -167,6 +167,9 @@ if(CMAKE_COMPILER_IS_GNU)
     execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpversion
                     OUTPUT_VARIABLE GCC_VERSION)
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Wwrite-strings")
+    if (GCC_VERSION VERSION_GREATER 3.0 OR GCC_VERSION VERSION_EQUAL 3.0)
```
[the remark this answers is not in the document]
Comment (paul-elliott-arm) [reply CMakeLists.txt:170]: I went to the bother of diffing each version of gcc in order to work out which flags were introduce where, so I put it in anyway. I know we don't really support versions that old.

File: library/psa_its_file.c (hunk 15 above)
[the remark this answers is not in the document]
Comment (gilles-peskine-arm) [reply library/psa_its_file.c:54]: Alternatively, since we assume that `int` is ≥32 bits anyway, it's ok to change the formats to `%08x` and cast the arguments to `unsigned` instead of `unsigned long`.

**Review by gabor-mezei-arm — APPROVED** [review]
Looks good to me

File: ChangeLog.d/fix-printf-specifiers.txt [hunk 17]
```diff
@@ -0,0 +1,10 @@
+Bugfix
+   * Add printf function attributes to mbedtls_debug_print_msg because we were
+     not actually getting any printf format specifier warnings prior to this.
+     Also add extra printf compiler warning flags to builds.
+Requirement changes
+   * Use %zu for print of type size_t in new work, however please do not use
```
Comment (mpg) [inline ChangeLog.d/fix-printf-specifiers.txt:6]: The target reader of ChangeLog entries is normally a basic user. I think this entry should be rewritten to start with that perspective before shifting to the perspective of a developer or contributor. Maybe something like "The library now uses the %zu format specifier with the printf() family of functions, so requires a toolchain that supports it. This change does not affect the maintained LTS branches, so when contributing changes please [...]"

**Review by mpg — COMMENTED** [review]
This is only a first pass focusing on the general aspects. I need to do a second pass for the tedious but necessary work of double-checking that we use a sensible type when we have to cast things.

**Review by mpg — CHANGES_REQUESTED** [review]
Ok, I've completed my review and didn't find anything new since [my first pass](https://github.com/ARMmbed/mbedtls/pull/3579#pullrequestreview-585321648). I've also reviewed previous comments from Gilles and double-checked they had all been addressed.

Apart from minor issues in the documentation and the ChangeLog, my only real concern is about using `__GNUC__` which I don't think is precise enough. Other than that, the PR is looking really good to me.

**Comment by paul-elliott-arm** [comment]
I hope to have addressed all the requests - once you are happy I have done this, I will do the rebase.

**Review by mpg — APPROVED** [review]
Thanks for addressing my feedback, it all looks good to me now.

However unfortunately in the meantime another conflict has developed, can you resolve it? Then I'll be sure to review quickly so that we can hopefully merge this before it develops yet another conflict. (cc @gabor-mezei-arm fyi on upcoming re-review)

**Review by gabor-mezei-arm — APPROVED** [review]

**Review by mpg — APPROVED** [review]
I checked that the rebased PR does the same changes as the version I approved yesterday, except for one occurrence that had been moved in the meantime in #3809 - that was removed from the initial series of commits, and handled in an additional commit at the end.

Note: I used `git range-diff development..0b737c61c431 development..b74499071747` to check the rebase.

**Comment by mpg** [comment]
I'm not sure what the backport strategy is here, but I suggest that as an exception to our usual rules, we merge this PR as soon as it's approved, without waiting for the backport to be ready, as there's just to much risk of new conflicts otherwise.

**Review by gabor-mezei-arm — APPROVED** [review]
