### PR TITLE
NetBSD 9.0 build fixes

### LINKED ISSUE #2310: 2.14.1: Compilation issue on NetBSD
When compiling on NetBSD (8.99.27/amd64) the build stops because `sockaddr_storage` is not defined.

The problem is that in `library/net_sockets.c`, the symbol `_POSIX_C_SOURCE` is defined to `200112L`. In contrast to Linux, NetBSD _removes_ symbols from the namespace when particular namespaces are requested.

(I think this might also be a problem on Solaris because it also likes to removes symbols.)
Workaround:
````
--- library/net_sockets.c.orig  2018-12-02 13:20:52.000000000 +0000
+++ library/net_sockets.c
@@ -22,7 +22,7 @@
 /* Enable definition of getaddrinfo() even when compiling with -std=c99. Must
  * be set before config.h, which pulls in glibc's features.h indirectly.
  * Harmless on other platforms. */
-#define _POSIX_C_SOURCE 200112L
+//#define _POSIX_C_SOURCE 200112L
 
 #if !defined(MBEDTLS_CONFIG_FILE)
 #include "mbedtls/config.h"
````
Please note the comment is incorrect ;)

### PR DESCRIPTION
**Pull request by niacat**
- Define `_XOPEN_SOURCE` in specific files to get definitions of `gethostname` and `sockaddr_storage`
- Add another check for `socklen_t`'s definition. I'm not really happy adding to this since it's quite hacky/messy, but it seems like the least intrusive change I can make for now. (I'm not sure which platforms without socklen_t need special-casing).

Fixes #2310

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
Thanks! I assume that you've tested on NetBSD, including any relevant older versions.

Please adjust either the author or the signed-off-by to placate the DCO check.

**Comment by gilles-peskine-arm** [comment]
Since this could break a “weird” platform that doesn't follow POSIX exactly, we shouldn't backport this.

**Comment by gilles-peskine-arm** [comment]
Please add a changelog entry file under `ChangeLog.d` (see `ChangeLog` for style).

**Comment by niacat** [comment]
@gilles-peskine-arm  Done.

**Comment by mpg** [comment]
The failure of Mbed OS testing in the pr-merge job is unrelated to this PR (it's caused by changes to the Mbed OS importer).

File: ChangeLog.d/bugfix_PR3422.txt [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Bugfix
+   * Fix building library/net_sockets.c and the ssl_mail_client program on NetBSD. Contributed by Nia Alarie in #3422.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/bugfix_PR3422.txt:2]: I'm not going to reject the PR for this because it doesn't break any automation and we'll likely do a pass of reformatting when we prepare the release. But for future reference, please wrap changelog lines to 80 columns.

**Comment by krytarowski** [comment]
Can we have a new release please with this and https://github.com/ARMmbed/mbedtls/pull/3423 included?

**Comment by gilles-peskine-arm** [comment]
Both will be in Mbed TLS 2.23.0 which is scheduled to be released today.
