### PR TITLE
Remove integer conversion warning in non-blocking ECC

### LINKED ISSUE #2141: ecp.c no longer builds with Microsoft Visual Studio
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
Windows

**mbed TLS build:**  
Version: 169712e15ac142412063d3fcae1894ac9e7e9e6c  
Configuration: default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  

Microsoft Visual Studio versions 2013, 2015, and 2017 when building Release or Debug builds with CMake

When building the following warning are generated, which are treated as errors and fail the build:

```
         ecp.c
    52>C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\library\ecp.c(1583): error C2220: warning treated as error - no 'object' file generated [C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\cmake_solution\library\mbedcrypto.vcxproj]
    52>C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\library\ecp.c(1583): warning C4267: 'function' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\cmake_solution\library\mbedcrypto.vcxproj]
    52>C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\library\ecp.c(1620): warning C4267: 'function' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\builds\ws\mbedtls-release\worktrees\tmp19i7oxoy\cmake_solution\library\mbedcrypto.vcxproj]
```

This was introduced by non-blocking ECC support.

### PR DESCRIPTION
**Pull request by hanno-arm**
__Context:__ The macro `MBEDTLS_ECP_BUDGET()` is called before performing a number of potentially time-consuming ECC operations. If restartable ECC is enabled, it wraps a call to `mbedtls_ecp_check_budget()` which in turn checks if the requested number of operations can be performed without exceeding the maximum number of consecutive ECC operations.

__Issue:__ The function `mbedtls_ecp_check_budget()` expects the number of requested operations to be given as a value of type `unsigned`, while some calls of the wrapper macro `MBEDTLS_ECP_BUDGET()` use
expressions of type `size_t`. This rightfully leads to warnings about implicit truncation from `size_t` to `unsigned` on some compilers, and was reported in #2141.

__Fix:__ Commit abdf67e makes the truncation explicit by adding an explicit cast to `unsigned` in the expansion of the `MBEDTLS_ECP_BUDGET()` macro.

__Justification:__ Functionally, the new version if equivalent to the previous code. The warning about truncation can be discarded because, as can be inferred from `ecp.h`, the number of requested operations is never larger than `~1000`. The _total_ number of operations since the last interruption can be larger, though, and commit b10c660 makes sure that `mbedtls_ecp_check_budget()` behaves correctly even if the requested number of operations would overflow the operation counter.

Fixes #2141.

### CODE REVIEW

**Comment by Patater** [comment]
Typo in commit message "Cast number of operations to `uint` in MBEDTLS_ECP_BUDGET"

```diff
- the new version if equivalent
+ the new version is equivalent
```

File: library/ecp.c [hunk 1]
```diff
@@ -248,9 +248,16 @@ int mbedtls_ecp_check_budget( const mbedtls_ecp_group *grp,
         else if( grp->pbits >= 384 )
             ops *= 2;
 
-        /* avoid infinite loops: always allow first step */
-        if( rs_ctx->ops_done != 0 && rs_ctx->ops_done + ops > ecp_max_ops )
+        /* Avoid infinite loops: always allow first step.
+         * Because of that, however, it's not true that
+         * ops_done <= ecp_max_ops at any time, so the
```
Comment (Patater) [inline library/ecp.c]: "at all times" or "at any time"? I would think at some times ops_done <= ecp_max_ops, but not all times.

Comment (hanno-arm) [reply library/ecp.c]: @Patater The implicit bracketing is `it's not true that (ops_done <= ecp_max_ops at any time)`, and not `(it's not true that ops_done <= ecp_max_ops) at any time`. I'm not sure how `at all times` would make things clearer. I'll switch to `Because of that, however, it's not generally true that ops_done <= ecp_max_ops, so the ...`.

**Comment by hanno-arm** [comment]
@sbutcher-arm @Patater Thanks for your review - I took the liberty to amend the PR. Could you please re-review?
