### PR TITLE
Fix miscalculations of maximum record expansion in mbedtls_ssl_get_record_expansion()

### LINKED ISSUE #1913: mbedtls_ssl_get_record_expansion() does not consider ChaChaPoly suites
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
All

**Mbed TLS build:**  
Version: 2.12
Configuration: ChaChaPoly ciphersuites enabled (e.g., default configuration)

**Description**
The public function `mbedtls_ssl_get_record_expansion()` is supposed to return the maximum difference between the length of a protected record and the length of the plaintext it encapsulates, with respect to the currently enabled outgoing record protection. 

```c
int mbedtls_ssl_get_record_expansion( const mbedtls_ssl_context *ssl )
{
    size_t transform_expansion;
    const mbedtls_ssl_transform *transform = ssl->transform_out;

#if defined(MBEDTLS_ZLIB_SUPPORT)
    if( ssl->session_out->compression != MBEDTLS_SSL_COMPRESS_NULL )
        return( MBEDTLS_ERR_SSL_FEATURE_UNAVAILABLE );
#endif

    if( transform == NULL )
        return( (int) mbedtls_ssl_hdr_len( ssl ) );

    switch( mbedtls_cipher_get_cipher_mode( &transform->cipher_ctx_enc ) )
    {
        case MBEDTLS_MODE_GCM:
        case MBEDTLS_MODE_CCM:
        case MBEDTLS_MODE_STREAM:
            transform_expansion = transform->minlen;
            break;

        case MBEDTLS_MODE_CBC:
            transform_expansion = transform->maclen
                      + mbedtls_cipher_get_block_size( &transform->cipher_ctx_enc );
            break;

        default:
            MBEDTLS_SSL_DEBUG_MSG( 1, ( "should never happen" ) );
            return( MBEDTLS_ERR_SSL_INTERNAL_ERROR );
    }

    return( (int)( mbedtls_ssl_hdr_len( ssl ) + transform_expansion ) );
}
```

PR #1752 introduced ChaChaPoly ciphersuites, the cipher mode for which is `MBEDTLS_MODE_CHACHAPOLY`, but this mode is not yet considered in `mbedtls_ssl_get_record_expansion()`. 

---------------------------------------------------------------
## Impact

**Internal**

_Currently_, there is no internal impact on the library as Mbed TLS does not use `mbedtls_ssl_get_record_expansion()`. However, PR #1879 starts to make use of `mbedtls_ssl_get_record_expansion()` to deduce the maximum plaintext length from the maximum MTU, and miscalculation will lead to Mbed TLS not obeying the MTU.

**Users**

Users relying on `mbedtls_ssl_get_record_expansion()` in any way will observe a failure with error `MBEDTLS_ERR_SSL_INTERNAL_ERROR` when enabling to ChaChaPoly ciphersuites (default).

### PR DESCRIPTION
**Pull request by hanno-arm**
__Summary:__ This PR fixes miscalculations of the maximum record expansion in `mbedtls_ssl_get_record_expansion()` in the case of ChachaPoly ciphersuites, as well as CBC ciphersuites in (D)TLS versions 1.1 or higher. Fixes #1913 and #1914.

This PR has high relevance for the ongoing fragmentation work #1879, which uses `mbedtls_ssl_get_record_expansion()` to deduce from the configured MTU the maximum record payload.

### CODE REVIEW

File: library/ssl_tls.c [hunk 1]
```diff
@@ -6854,13 +6855,33 @@ int mbedtls_ssl_get_record_expansion( const mbedtls_ssl_context *ssl )
...
+#if defined(MBEDTLS_SSL_PROTO_TLS1_1) || defined(MBEDTLS_SSL_PROTO_TLS1_2)
+            if( ssl->minor_ver >= MBEDTLS_SSL_MINOR_VERSION_2 )
+            {
+                /* Expansion due to addition of
+                 * - MAC
+                 * - CBC padding (theoretically up to 256 bytes, but
+                 *                we never use more than block_size)
+                 * - explicit IV
+                 */
+                transform_expansion = transform->maclen + 2 * block_size;
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c]: This would be clearer with successive additions, with a structure like this:
```
transform_expansion = transform->maclen;
transform_expansion += block_size; // max padding size
if (TLS version >= 1.1) transform_expansion += block_size; // max IV size for explicit padding
```

File: library/ssl_tls.c [hunk 2]
```diff
@@ -6854,13 +6855,33 @@ int mbedtls_ssl_get_record_expansion( const mbedtls_ssl_context *ssl )
...
-            transform_expansion = transform->maclen
-                      + mbedtls_cipher_get_block_size( &transform->cipher_ctx_enc );
+
+            block_size = mbedtls_cipher_get_block_size(
+                &transform->cipher_ctx_enc );
+
+#if defined(MBEDTLS_SSL_PROTO_TLS1_1) || defined(MBEDTLS_SSL_PROTO_TLS1_2)
+            if( ssl->minor_ver >= MBEDTLS_SSL_MINOR_VERSION_2 )
+            {
+                /* Expansion due to addition of
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c]: This logic is largely duplicated in `mbedtls_ssl_derive_keys` with the calculation of `transform->minlen`. We have a mostly-duplicated calculation, and we got it wrong in one place, so we really should de-duplicate it.

`transform->minlen` is the size of a record with a payload of size 0, i.e. it's the record overhead for a payload of size 0. `get_record_expansion` is the maximum record overhead. The difference between the two is that `transform->minlen` calculates the exact padding length (which is not necessarily the block size: it's true in most cases, but not for mac-then-encrypt with a MAC size that isn't a multiple of the block size) whereas `get_record_expansion` uses the maximum padding size.

We could either have a function that takes a flag to indicate “padding for empty record” vs “maximum padding size”, or a pair of functions, one that returns the constant part of the overhead and one that returns the part that gets padded.

Comment (hanno-arm) [reply library/ssl_tls.c]: @gilles-peskine-arm 

I suggest the following: We introduce a function `mbedtls_ssl_transform_get_expansion` which takes an SSL transform and an optional plaintext length, and returns pre-expansion and post-expansion values for the transform. If the plaintext length is specified, both must be accurate; if not, the postexpansion must be an overapproximation for all plaintext lengths. Pre-expansions never vary, so it is always accurate.

With that, `minlen` can be defined as `pre_exp(0) + post_exp(0)`, and `mbedtls_ssl_get_record_expansion()` can be defined as `mbedtls_ssl_hdr_len + pre_exp(unspecified) + post_exp(unspecified)`. 

Since `transform->minlen` is redundant, we might remove it from `mbedtls_ssl_transform` on that occasion.

The pre-expansion determines the offset of `ssl->out_msg` from `ssl->out_iv`, so we could also rewrite updating these pointers in terms of `mbedtls_ssl_transform_get_expansion`. 

The above proposal can not yet be implemented as stated since not all information determining a transform are actually contained in `mbedtls_ssl_transform`, for example the Encrypt-then-MAC flag. PR #1633 fixes this, so if you think the above sounds reasonable, I suggest we come back to it as soon as #1633 is merged, and stay with the current version of this PR until then.

WDYT?

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: Ok, but why not add the missing information to the transform, or pass it separately?

Comment (hanno-arm) [reply library/ssl_tls.c]: @gilles-peskine-arm I don't want to mix up this PR with #1633, which does add the missing fields.

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: Ok, then let's stick with the duplicated calculation for now.

Comment (hanno-arm) [reply library/ssl_tls.c]: @gilles-peskine-arm Do you approve, then?

File: library/ssl_tls.c [hunk 3]
```diff
@@ -6854,13 +6855,33 @@ int mbedtls_ssl_get_record_expansion( const mbedtls_ssl_context *ssl )
...
+                 * - MAC
+                 * - CBC padding (theoretically up to 256 bytes, but
+                 *                we never use more than block_size)
+                 * - explicit IV
+                 */
+                transform_expansion = transform->maclen + 2 * block_size;
+            }
+            else
+#endif /* MBEDTLS_SSL_PROTO_TLS1_1 || MBEDTLS_SSL_PROTO_TLS1_2 */
```
Comment (mpg) [inline library/ssl_tls.c]: Note: I'm not too happy about this structure, because it doesn't automatically detect when new versions are added. I'd much prefer "if( 1.1 or 1.2 ) then ... else if( 1.0 or 3.0 ) then ... else return error" as elsewhere. For now it's OK, but when you rework this during deduplication, please use a safer pattern.

Comment (hanno-arm) [reply library/ssl_tls.c]: @mpg Ok!

**Comment by mpg** [comment]
@hanno-arm Note: #1939 now includes this (by merging it). In order to avoid unnecessary complexity, please refrain from rewriting history in this PR from now on. If changes are needed here, please only add new commits. Thanks!

File: library/ssl_tls.c (hunk 2 above)
Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: I'm ok to keep the duplicated calculation until #1633 is merged. But please make the calculation clearer as per https://github.com/ARMmbed/mbedtls/pull/1915/files#r207555016

Comment (hanno-arm) [reply library/ssl_tls.c]: @gilles-peskine-arm If you insist I will change it, but if we leave a thorough cleanup for post #1633 anyway, would you accept leaving this PR as is for now? I think the documentation is quite clear on the source of the arithmetic, and the PR has already seen two approvals and @mpg's work on https://github.com/ARMmbed/mbedtls/pull/1939 builds on it.

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: I'd really prefer the clear code. It doesn't conflict with any of the changes in #1939, does it?

**Comment by hanno-arm** [comment]
@mpg @k-stachowiak @gilles-peskine-arm Please re-review.

File: library/ssl_tls.c (hunk 2 above)
Comment (hanno-arm) [reply library/ssl_tls.c]: @gilles-peskine-arm Done.

**Comment by mpg** [comment]
Note: as noted by Gilles, this is difficult to test properly with the current stack. However, #1939 includes tests that rely on `mbedtls_ssl_get_record_expansion()` crucially to succeed, and would have detected the two issues fixed here, so they can be considered non-regression tests, even if they're not complete tests for this function (they wouldn't detect an over-estimation for example).

**Comment by hanno-arm** [comment]
@sbutcher-arm This PR is only partially included in #1939 (#1939 doesn't include a readability-improving change that @gilles-peskine-arm requested), so it should be merged even if #1939 gets in.
