### PR TITLE
Remove Extraneous bytes from buffer post pem write

### LINKED ISSUE #3682: Error when generating a certificate via mbedtls_x509write_crt_pem and then parsing it.
### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug
**mbed TLS build:**  
Version: 2.16.8 (build statically, with GCC)

Due to the changes in #2632 (and its backport #3488), creating a PEM certificate via `mbedtls_x509write_crt_pem`, then reading it into a `mbedtls_x509_crt` via `mbedtls_x509_crt_parse` will fail when passing the full buffer size in `2.16.8 ` while not failing in `2.16.7`.

(see example code below, compiled with `gcc example.c -I./build/include/ -Lbuild/library/ -lmbedtls -lmbedx509 -lmbedcrypto -Wl,-rpath,"build/library"`).

```c
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/entropy.h>
#include <mbedtls/pem.h>
#include <mbedtls/ssl.h>

#include <stdio.h>
#include <string.h>

int main(int argc, char **argv) {
	// Init entropy/random number generator.
	mbedtls_entropy_context entropy;
	mbedtls_ctr_drbg_context ctr_drbg;

	mbedtls_ctr_drbg_init(&ctr_drbg);
	mbedtls_entropy_init(&entropy);

	mbedtls_ctr_drbg_seed(&ctr_drbg, mbedtls_entropy_func, &entropy, NULL, 0);

	// Create key
	mbedtls_pk_context pkey;
	mbedtls_pk_init(&pkey);
	int ret = mbedtls_pk_setup(&pkey, mbedtls_pk_info_from_type(MBEDTLS_PK_RSA));
	ret = mbedtls_rsa_gen_key(mbedtls_pk_rsa(pkey), mbedtls_ctr_drbg_random, &ctr_drbg, 2048, 65537);

	// Create certificate
	mbedtls_x509write_cert crt;
	mbedtls_x509write_crt_init(&crt);

	mbedtls_x509write_crt_set_subject_key(&crt, &(pkey));
	mbedtls_x509write_crt_set_issuer_key(&crt, &(pkey));
	mbedtls_x509write_crt_set_subject_name(&crt, "CN=example.com,O=A Game Company,C=IT");
	mbedtls_x509write_crt_set_issuer_name(&crt, "CN=example.com,O=A Game Company,C=IT");
	mbedtls_x509write_crt_set_version(&crt, MBEDTLS_X509_CRT_VERSION_3);
	mbedtls_x509write_crt_set_md_alg(&crt, MBEDTLS_MD_SHA256);

	mbedtls_mpi serial;
	mbedtls_mpi_init(&serial);
	uint8_t rand_serial[20];
	mbedtls_ctr_drbg_random(&ctr_drbg, rand_serial, 20);
	mbedtls_mpi_read_binary(&serial, rand_serial, 20);
	mbedtls_x509write_crt_set_serial(&crt, &serial);

	mbedtls_x509write_crt_set_validity(&crt, "20140101000000", "20340101000000");
	mbedtls_x509write_crt_set_basic_constraints(&crt, 1, -1);
	mbedtls_x509write_crt_set_basic_constraints(&crt, 1, 0);

	// Write certificate to buffer.
	unsigned char buf[4096];
	memset(buf, 0, 4096);
	mbedtls_x509_crt out;
	mbedtls_x509_crt_init(&out);
	mbedtls_x509write_crt_pem(&crt, buf, 4096, mbedtls_ctr_drbg_random, &ctr_drbg); // In 2.16.8, due to #3488/#2632 , this writes at the end of the buffer.

	// Parse the wrote buffer in output certificate.
	int err = mbedtls_x509_crt_parse(&out, buf, 4096); // This fail in 2.16.8 because buf[buflen-1] is not '\0'.
	// buf[4095] = '\0'; would work around it while still hacky.
	// Using `strlen((char *)buf) + 1` instead of 4096 would also work.
	if (err != 0) {
	        mbedtls_mpi_free(&serial);
	        mbedtls_x509write_crt_free(&crt);
	        printf("Generated invalid certificate\n");
	        return 1;
	}

	mbedtls_mpi_free(&serial);
	mbedtls_x509write_crt_free(&crt);
	mbedtls_x509_crt_free(&out);
	return 0;
}
```

### PR DESCRIPTION
**Pull request by paul-elliott-arm**
## Description

In order to remove some big (4k) buffers from being created on the stack, the output buffer was re-used - in this case the raw der data is written to the buffer prior to being base64 encoded into an allocated buffer, and then overwritten with the pem data. However, even though the pem data is zero terminated, usually der data will remain in the buffer after the terminator.

Should this buffer get passed into mbedtls_x509_crt_parse() then it will likely fail to parse, as it decides whether or not a buffer is pem by checking the last byte of the buffer for being zero - if it isn't zero, it will attempt to parse as der, which will obviously fail.

This just ensures the buffer is cleaned to avoid the regression, there may be future work around this subject to make the area safer and tests to ensure this doesn't happen again.

This closes #3682 

## Status
**READY**

## Requires Backporting
YES 
[2.16](https://github.com/ARMmbed/mbedtls/pull/3935)
[2.7](https://github.com/ARMmbed/mbedtls/pull/3945)

(Bug did not affect the 2.7 branch, but wanted to add the tests)

## Migrations
NO

## Todos
- [x] Changelog updated
- [ ] Backported

## Steps to test or reproduce
See #3682

### CODE REVIEW

File: library/x509write_crt.c [hunk 1]
```diff
@@ -537,6 +537,12 @@ int mbedtls_x509write_crt_pem( mbedtls_x509write_cert *crt,
         return( ret );
     }
 
+    if( ( size - olen ) >  0 )
```
Comment (gilles-peskine-arm) [inline library/x509write_crt.c:540]: Why do this check explicitly? `memset` will likely perform it again (unless the compiler optimizes it, in which case it's clutter).

**Review by gilles-peskine-arm — COMMENTED** [review]
I agree with this approach. It needs:

* [x] Same thing with CSR.
* [x] In unit tests, after calling `mbedtls_x509write_crt_pem`, check that the trail of the buffer is zeroed out. Make sure that there is at least one unit test where the output buffer is larger than the output data.
* [x] Unit tests for the other functions with the same pattern (`mbedtls_pk_write_pubkey_pem`, `mbedtls_pk_write_key_pem`, `mbedtls_x509write_csr_pem`).
* [x] Changelog entry.

File: ChangeLog.d/clean_pem_buffers.txt [hunk 2]
```diff
@@ -0,0 +1,13 @@
+Bugfix
+  * As an optimisation to stop large buffers being written to the stack the
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:2]: This would be the second-longest changelog entry ever. Surely it can be summarized/

File: ChangeLog.d/clean_pem_buffers.txt [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+    code was changed to write the raw der data to the same buffer that the
+    pem data would later be written to. Unfortunately even though the pem data
+    was always NULL terminated the der data would be left in the buffer after
+    the NULL termination. This is an issue as if you passed the same buffer
+    and length into one of the pem write functions and then into its
+    corresponding parse functions, then the parse function would fail, as its
+    test for whether the data was der or pem involved testing the last byte of
+    the buffer to see if it was zero. Tests have also been modified to try and
+    prevent this regression from happening again.
+    Thanks to Faless for reporting this in #3682
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:12]: We [no longer use changelog entries to acknowledge bug reporters](https://github.com/ARMmbed/mbedtls/pull/3726). And when we did, the wording was “Reported by NAME in #NUMBER.”

File: ChangeLog.d/clean_pem_buffers.txt [hunk 4]
```diff
@@ -0,0 +1,13 @@
+Bugfix
+  * As an optimisation to stop large buffers being written to the stack the
+    code was changed to write the raw der data to the same buffer that the
+    pem data would later be written to. Unfortunately even though the pem data
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:4]: PEM is a proper name that's an acronym, so it must be capitalized.

File: ChangeLog.d/clean_pem_buffers.txt [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+    was always NULL terminated the der data would be left in the buffer after
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:5]: “NULL” is only capitalized when it's the C constant (including when the name of the constant is used metonymically to mean a null pointer). Here you mean a null byte, so null is an ordinary adjective, written in lowercase.

File: tests/suites/test_suite_pkwrite.function [hunk 6]
```diff
@@ -28,12 +28,22 @@ void pk_write_pubkey_check( char * key_file )
     ret = mbedtls_pk_write_pubkey_pem( &key, buf, sizeof( buf ));
     TEST_ASSERT( ret == 0 );
 
+    pem_len = strlen( (char *) buf );
+
+    // check that the rest of the buffer remains clear
+    for( buf_index = pem_len ; buf_index < 5000; ++buf_index )
```
Comment (gilles-peskine-arm) [inline tests/suites/test_suite_pkwrite.function:34]: Don't hard-code magic constants.
```suggestion
    for( buf_index = pem_len; buf_index < sizeof( check_buf ); ++buf_index )
```

File: tests/suites/test_suite_pkwrite.function [hunk 7]
```diff
@@ -28,12 +28,22 @@ void pk_write_pubkey_check( char * key_file )
...
+    {
+        TEST_ASSERT( buf[buf_index] == 0 );
+    }
+
+    TEST_ASSERT((5000 - pem_len) > 2);
```
Comment (gilles-peskine-arm) [inline tests/suites/test_suite_pkwrite.function:39]: Style:
```suggestion
    TEST_ASSERT( (5000 - pem_len) > 2 );
```

File: tests/suites/test_suite_x509write.function [hunk 8]
```diff
@@ -293,6 +293,12 @@ void x509_crt_check( char *subject_key_file, char *subject_pwd,
 
     pem_len = strlen( (char *) buf );
 
+    // check that the rest of the buffer remains clear
+    for( buf_index = pem_len ; buf_index < 4096; ++buf_index )
+    {
+        TEST_ASSERT( buf[buf_index] == 0 );
+    }
+
```
Comment (gilles-peskine-arm) [inline tests/suites/test_suite_x509write.function:301]: Missing: similar check in `x509_csr_check`.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]

File: tests/suites/test_suite_pkwrite.function (hunk 7 above)
Comment (paul-elliott-arm) [reply tests/suites/test_suite_pkwrite.function:39]: Whoops, this wasn't meant to be here, this was just me testing that at least in one of tests the buffers was bigger than the data written to it. Removed

File: ChangeLog.d/clean_pem_buffers.txt [hunk 9]
```diff
@@ -0,0 +1,8 @@
+Bugfix
+  * As an optimisation to stop large buffers being written to the stack the
+    raw der data was instead written to the same buffer that the PEM data
+    would later be written to. Unfortunately this would cause data to be left
+    in the buffer after the null termination, which could potentially break
+    the parsing functions if the whole buffer was passed into it.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:6]: That's much better but there's still too much information. Changelog entries are for users' information. It isn't important why the bug arose, but what its consequences where. On the other hand, it might be useful to know when the bug arose (especially in 2.16 branches where this was a regression in 2.16.8 compared to previous 2.16.x). Also the lead lacks context.

Here's how I'd write this changelog entry:

> In PEM writing functions, fill the trailing part of the buffer with null bytes. This guarantees that the corresponding parsing function can read the buffer back, which was the case for mbedtls_x509write_{crt,csr}_pem until this property was inadvertently broken in Mbed TLS 2.19.0. Fix #3682.

File: library/pkwrite.c [hunk 10]
```diff
@@ -575,6 +575,9 @@ int mbedtls_pk_write_pubkey_pem( mbedtls_pk_context *key, unsigned char *buf, si
         return( ret );
     }
 
+    /* Clean any remaining der data from the buffer */
+    memset( buf + olen, 0, size - olen );
```
Comment (gilles-peskine-arm) [inline library/pkwrite.c:579]: I didn't twig earlier, but: why add after every call to `mbedtls_pem_write_buffer` instead of only once in `mbedtls_pem_write_buffer`? Doing it in `mbedtls_pem_write_buffer` makes the code more robust and smaller.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]

File: ChangeLog.d/clean_pem_buffers.txt [hunk 11]
```diff
@@ -0,0 +1,6 @@
+Bugfix
+  * In PEM writing functions, fill the trailing part of the buffer with null
+    bytes. This guarantees that the corresponding parsing function can read
+    the buffer back, which was the case for mbedtls_x509write_{crt,csr}_pem
+    until this property was inadvertently broken in Mbed TLS 2.19.0.
+    Fixes #3682.
```
Comment (gilles-peskine-arm) [inline ChangeLog.d/clean_pem_buffers.txt:6]: Please ensure that `tests/scripts/all.sh -k check_files check_changelog` passes

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
LGTM but not to CI

File: ChangeLog.d/clean_pem_buffers.txt (hunk 11 above)
Comment (paul-elliott-arm) [reply ChangeLog.d/clean_pem_buffers.txt]: Missing newline at end. Fixed.

**Review by gilles-peskine-arm — DISMISSED** [review]

File: tests/suites/test_suite_pkwrite.function [hunk 12]
```diff
@@ -28,12 +28,20 @@ void pk_write_pubkey_check( char * key_file )
     ret = mbedtls_pk_write_pubkey_pem( &key, buf, sizeof( buf ));
     TEST_ASSERT( ret == 0 );
 
+    pem_len = strlen( (char *) buf );
+
+    // check that the rest of the buffer remains clear
+    for( buf_index = pem_len ; buf_index < sizeof( buf ); ++buf_index )
```
Comment (gabor-mezei-arm) [inline tests/suites/test_suite_pkwrite.function:34]: typo
```suggestion
    for( buf_index = pem_len; buf_index < sizeof( buf ); ++buf_index )
```

File: library/pem.c [hunk 13]
```diff
@@ -478,6 +478,9 @@ int mbedtls_pem_write_buffer( const char *header, const char *footer,
     *p++ = '\0';
     *olen = p - buf;
 
+     /* Clean any remaining data previously written to the buffer */
+    memset( buf + *olen, 0, buf_len - *olen );
```
Comment (gabor-mezei-arm) [inline library/pem.c:482]: Use the `mbedtls_platform_zeroize` instead of `memset`.

File: tests/suites/test_suite_pkwrite.function [hunk 14]
```diff
@@ -60,6 +68,14 @@ void pk_write_key_check( char * key_file )
     ret = mbedtls_pk_write_key_pem( &key, buf, sizeof( buf ));
     TEST_ASSERT( ret == 0 );
 
+    pem_len = strlen( (char *) buf );
+
+    // check that the rest of the buffer remains clear
+    for( buf_index = pem_len ; buf_index < sizeof( buf ); ++buf_index )
```
Comment (gabor-mezei-arm) [inline tests/suites/test_suite_pkwrite.function:74]: typo

File: tests/suites/test_suite_x509write.function [hunk 15]
```diff
@@ -130,6 +130,11 @@ void x509_csr_check( char * key_file, char * cert_req_check_file, int md_type,
 
     pem_len = strlen( (char *) buf );
 
+    for( buf_index = pem_len ; buf_index < sizeof( buf ); ++buf_index )
```
Comment (gabor-mezei-arm) [inline tests/suites/test_suite_x509write.function:133]: typo

File: tests/suites/test_suite_x509write.function [hunk 16]
```diff
@@ -293,6 +298,12 @@ void x509_crt_check( char *subject_key_file, char *subject_pwd,
 
     pem_len = strlen( (char *) buf );
 
+    // check that the rest of the buffer remains clear
+    for( buf_index = pem_len ; buf_index < 4096; ++buf_index )
```
Comment (gabor-mezei-arm) [inline tests/suites/test_suite_x509write.function:302]: typo

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]

File: library/pem.c (hunk 13 above)
Comment (gilles-peskine-arm) [reply library/pem.c:482]: This is part of an output buffer, so `memset` is ok. When `zeroize` is not necessary, `memset` is preferred because it's more efficient (the compiler knows how to optimize it for code size or speed).

File: tests/suites/test_suite_x509write.function (hunk 16 above)
Comment (gabor-mezei-arm) [reply tests/suites/test_suite_x509write.function:302]: This has been missed

**Review by gabor-mezei-arm — CHANGES_REQUESTED** [review]

**Review by gabor-mezei-arm — APPROVED** [review]

**Review by gilles-peskine-arm — APPROVED** [review]

**Comment by gilles-peskine-arm** [comment]
The CI is being unstable, but between https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-3898-merge/10 and https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-3898-merge/11 all the jobs passed (for Windows-2013, which failed in both, all the sub-jobs passed in at least one of the runs).
