### PR TITLE
Write correct number of ciphersuites in log

### LINKED ISSUE #918: wrong log for number of ciphersuites in ssl_write_client_hello
in `ssl_write_client_hello`, the following log is incorrect: `client hello, got %d ciphersuites`  
The reason is because it is located after optionally adding renegotiation info and fallback SCSV.  
This may increase `n` by 1 or two, logging a larger number of ciphersuites sent

### PR DESCRIPTION
**Pull request by RonEld**
## Description
Change location of log, to fit the correct number of used ciphersuites
Fixes #918

## Status
**READY**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
mbedtls-1.3
mbedtls-2.1

## Migrations
NO

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Changelog updated
- [ ] Backported

## Steps to test or reproduce
use a small amount of ciphersuites, enable SSL_RENEGOTIATION and\or SSL_FALLBACK_SCSV and look at log

### CODE REVIEW

File: library/ssl_cli.c [hunk 1]
```diff
@@ -891,6 +891,8 @@ static int ssl_write_client_hello( mbedtls_ssl_context *ssl )
         *p++ = (unsigned char)( ciphersuites[i]      );
     }
 
+	MBEDTLS_SSL_DEBUG_MSG(3, ("client hello, got %d ciphersuites", n));
```
Comment (andresag01) [inline library/ssl_cli.c]: Style: Please add space after and before `(` and `)` respectively.

File: library/ssl_cli.c [hunk 2]
```diff
@@ -891,6 +891,8 @@ static int ssl_write_client_hello( mbedtls_ssl_context *ssl )
...
+
```
Comment (andresag01) [inline library/ssl_cli.c]: Perhaps we should add a log message  when adding `MBEDTLS_SSL_EMPTY_RENEGOTIATION_INFO`?

**Comment by RonEld** [comment]
Hi @andresag01 , I updated according to your comments

File: ChangeLog [hunk 3]
```diff
@@ -13,6 +13,7 @@ Bugfix
      Found by redplait #590
    * Add MBEDTLS_MPI_CHK to check for error value of mbedtls_mpi_fill_random.
      Reported and fix suggested by guidovranken in #740
+   * Log correct number of ciphersuites used in Client Hello message. Fix for #918.
```
Comment (hanno-arm) [inline ChangeLog]: After @andresag01 suggestions, I'd prefer a more specific entry here like "Modify debug output of ssl_write_client_hello to not consider SCSV entries in the ciphersuite count but to log them separately.".

File: library/ssl_cli.c [hunk 4]
```diff
@@ -891,13 +891,16 @@ static int ssl_write_client_hello( mbedtls_ssl_context *ssl )
         *p++ = (unsigned char)( ciphersuites[i]      );
     }
 
+	MBEDTLS_SSL_DEBUG_MSG( 3, ( "client hello, got %d ciphersuites (excluding SCSVs)", n ) );
```
Comment (andresag01) [inline library/ssl_cli.c]: Style: Please use spaces instead of tabs

File: library/ssl_cli.c [hunk 5]
```diff
@@ -891,13 +891,16 @@ static int ssl_write_client_hello( mbedtls_ssl_context *ssl )
...
+
     /*
      * Add TLS_EMPTY_RENEGOTIATION_INFO_SCSV
      */
 #if defined(MBEDTLS_SSL_RENEGOTIATION)
     if( ssl->renego_status == MBEDTLS_SSL_INITIAL_HANDSHAKE )
 #endif
     {
+		MBEDTLS_SSL_DEBUG_MSG( 3, ( "adding EMPTY_RENEGOTIATION_INFO_SCSV" ) );
```
Comment (andresag01) [inline library/ssl_cli.c]: Style: Please use spaces instead of tabs

File: ChangeLog (hunk 3 above)
Comment (andresag01) [reply ChangeLog]: I personally do not mind the ChangeLog entry. Actually, I think that the change is so small that it probably should not have a ChangeLog entry...

Comment (hanno-arm) [reply ChangeLog]: What about keeping it but moving it to the Changes section in it's extended form?

Comment (RonEld) [reply ChangeLog]: I agree with Andres, that this is a minor change, only on a log message, which doesn't require a ChangeLog Entry

**Comment by RonEld** [comment]
Hi @andresag01 @hanno-arm I addressed your comments. Although I agree with Andres that this PR doesn''t necessary need a ChangeLog entry, I modified the ChangeLog according to Hanno's comments, as I also saw duplication in the BugFix section

**Comment by andresag01** [comment]
@RonEld: There seems to be a few conflicts with the ChangeLog. You should not have to delete duplicated entries. Could you please rebase your changes on top of the current development. I know this affects a little the review history, but I think it would be good in this case. Thanks!

**Comment by RonEld** [comment]
@andresag01 I rebased and fixed conflicts.
Please approve

**Comment by gilles-peskine-arm** [comment]
This fixes a debug message, so it's low-risk. Can you please make a 2.1 backport? This PR is old enough to be mergeable into 2.7 so we don't need a separate PR for 2.7.
