### PR TITLE
[3.6] Rsa: use the CRT to generate base blinding values

### LINKED ISSUE #10476: Performance Regression in RSA Test Suite (v3.6.4 → v3.6.5)
### Summary

Hey all,

I am testing mbedtls 3.6.5 and encountered a significant performance regression between v3.6.4 and v3.6.5 with RSA test suite, with approximately **35% increase in execution time** (1.37s → 1.85s) for identical test coverage (250/250 tests passed).

I noticed the v3.6.5 release notes mention a fix for the SSBleed/M-Step timing side-channel vulnerability. I assume this performance change is the intentional cost of the mitigation, but I wanted to confirm if this is expected and understand if any optimizations are possible.

### System information

Mbed TLS version (number or commit id): v3.6.4 (baseline) vs v3.6.5 (regression)
Operating system and version: macOS (Apple Silicon M3)
Configuration (if not default, please attach `mbedtls_config.h`):  Default configuration
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Default compiler (clang on macOS)

### Expected behavior

I was expecting a minor release to not have a significant performance penalty.

### Actual behavior

| Metric | v3.6.4 | v3.6.5 | % Change |
|--------|--------|--------|----------|
| Elapsed Time | 1.37s | 1.85s | **+35.0%** |
| User CPU Time | 1.36s | 1.84s | **+35.3%** |
| System Time | 0.01s | 0.01s | 0% |

### Steps to reproduce

```bash
# v3.6.4
git clone https://github.com/Mbed-TLS/mbedtls.git && cd mbedtls
git checkout v3.6.4 && make clean && make
gtime -f "\nElapsed: %e seconds\nUser: %U\nSys: %S" ./tests/test_suite_rsa

# v3.6.5  
git checkout v3.6.5 && make clean && make
gtime -f "\nElapsed: %e seconds\nUser: %U\nSys: %S" ./tests/test_suite_rsa
```

**Result:** v3.6.5 takes ~35% longer than v3.6.4

### Additional information

**Questions:**

1. Is this the expected cost of the SSBleed/M-Step mitigation?
2. Are there optimization opportunities to reduce the impact while maintaining security?
3. Could there be configuration options for different threat models (e.g., `MBEDTLS_ALLOW_VARIABLE_TIME_FOR_PERFORMANCE` for systems not vulnerable to SSBleed/M-Step)?
4. Should the release notes explicitly mention this performance impact for capacity planning?

We appreciate the security fix! We're looking for confirmation this is expected, guidance on threat model applicability, and possible configuration options for controlled environments where the additional overhead may be unnecessary.

### PR DESCRIPTION
**Pull request by mpg**
## Description

In builds where `MBEDTLS_RSA_NO_CRT` is disabled, take advantage of the CRT when generating the initial value for base blinding.

Fixes #10476

## PR checklist

- [x] **changelog** included
- [x] **development PR** not required because: on the crypto side
- [x] **TF-PSA-Crypto PR** provided https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/589
- [x] **framework PR** not required
- [x] **3.6 PR** provided HERE
- **tests**  not required because: covered by existing tests

### CODE REVIEW

File: library/rsa.c [hunk 1]
```diff
@@ -1327,6 +1328,31 @@ static int rsa_gen_rand_with_inverse(const mbedtls_rsa_context *ctx,
...
+#else
+    int ret;
+    mbedtls_mpi Ap, Aq, Bp, Bq;
+
+    mbedtls_mpi_init(&Ap); mbedtls_mpi_init(&Aq);
+    mbedtls_mpi_init(&Bp); mbedtls_mpi_init(&Bq);
+
+    /* Generate Ap in [1, P) and compute Bp = Ap^-1 mod P */
+    MBEDTLS_MPI_CHK(mbedtls_mpi_random(&Ap, 1, &ctx->P, f_rng, p_rng));
+    MBEDTLS_MPI_CHK(mbedtls_mpi_gcd_modinv_odd(NULL, &Bp, &Ap, &ctx->P));
```
Comment (gilles-peskine-arm) [inline library/rsa.c]: If P is not actually prime, there is a chance that Ap is not invertible mod P, and Bp is “indeterminate” according to the documentation of `mbedtls_mpi_gcd_modinv_odd`. So subsequent uses of the RSA private key will use indeterminate blinding values.

An RSA key should have probable primes as P and Q, so the probability of finding a factor is very small. However, it bothers me that we aren't checking this. Especially since the old code did check (the condition G=1 catches multiple of P or Q for a perfect RSA key, but also more generally any value that isn't invertible mod N).

In both cases, I'd be ok with erroring immediately out if A turns out not to be invertible, or to try a few iterations. I don't see a reason why the number of retries would be different with a single random value or with two: the case of a multiple of P or Q has negligible probability, so it doesn't really make a difference in terms of expected retries to find a suitable A.

File: library/rsa.c [hunk 2]
```diff
@@ -1268,6 +1268,93 @@ int mbedtls_rsa_public(mbedtls_rsa_context *ctx,
     return 0;
 }
 
+#if !defined(MBEDTLS_RSA_NO_CRT)
```
Comment (gilles-peskine-arm) [inline library/rsa.c:1270]: We're fixing a performance regression in an LTS branch, so this needs a changelog entry.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
LGTM for nominal RSA keys, but I don't see why the CRT version would make a difference with respect to the number of retries to find a suitable blinding value.

I haven't run any benchmarks.

File: library/rsa.c (hunk 1 above)
Comment (mpg) [reply library/rsa.c]: I was working on the assumption that P and Q were primes. You're right that in practice they only a probable primes, so the probably that they're not and that we're finding a factor here is non-zero.

This probability is also not significantly smaller than the probably of either drawing a multiple of P or Q or finding one of their factors in the non-CRT case, so indeed it makes sense to handle both in the same way.

I'll just error out immediately, since I think it's a bit ridiculous to have loops for events whose probability is less than say 2^-100. (In some cases the standard requires it, and in those cases let's follow the standard regardless of my opinion, but here we're free, so let's skip the loop.)

**Comment by mpg** [comment]
Ah, quite embarrassing, I didn't even build that config before pushing. Let me try again.

File: library/rsa.c [hunk 3]
```diff
@@ -1268,6 +1268,38 @@ int mbedtls_rsa_public(mbedtls_rsa_context *ctx,
...
+/*
+ * Compute T such that T = TP mod P and T = TP mod Q.
```
Comment (davidhorstmann-arm) [inline library/rsa.c]: I believe this should be:
```suggestion
 * Compute T such that T = TP mod P and T = TQ mod Q.
```
Unless I have missed something.

File: library/rsa.c [hunk 4]
```diff
@@ -1268,6 +1268,38 @@ int mbedtls_rsa_public(mbedtls_rsa_context *ctx,
...
+     */
+    MBEDTLS_MPI_CHK(mbedtls_mpi_sub_mpi(T, TP, TQ));
+    MBEDTLS_MPI_CHK(mbedtls_mpi_mul_mpi(TP, T, &ctx->QP));
+    MBEDTLS_MPI_CHK(mbedtls_mpi_mod_mpi(T, TP, &ctx->P));
+
+    /*
+     * T = TQ + T * Q
+     */
+    MBEDTLS_MPI_CHK(mbedtls_mpi_mul_mpi(TP, T, &ctx->Q));
+    MBEDTLS_MPI_CHK(mbedtls_mpi_add_mpi(T, TQ, TP));
```
Comment (davidhorstmann-arm) [inline library/rsa.c]: [Preexisting] It looks like this is trying to avoid using `T` as both an input and an output, so it uses `TP` as a temporary store. However AFAICT all of the bignum functions allow reuse of a parameter (`mul_mpi()` seems to check for it explicitly).

Would you be able to change this to reuse `T` for intermediate computation, as the way it is now somewhat obscures the calculations that are happening and makes it harder to understand.

```suggestion
    MBEDTLS_MPI_CHK(mbedtls_mpi_mul_mpi(T, T, &ctx->QP));
    MBEDTLS_MPI_CHK(mbedtls_mpi_mod_mpi(T, T, &ctx->P));

    /*
     * T = TQ + T * Q
     */
    MBEDTLS_MPI_CHK(mbedtls_mpi_mul_mpi(T, T, &ctx->Q));
    MBEDTLS_MPI_CHK(mbedtls_mpi_add_mpi(T, T, TQ));
```

File: library/rsa.c [hunk 5]
```diff
@@ -1327,6 +1328,31 @@ static int rsa_gen_rand_with_inverse(const mbedtls_rsa_context *ctx,
...
+    mbedtls_mpi Ap, Aq, Bp, Bq;
+
+    mbedtls_mpi_init(&Ap); mbedtls_mpi_init(&Aq);
+    mbedtls_mpi_init(&Bp); mbedtls_mpi_init(&Bq);
+
+    /* Generate Ap in [1, P) and compute Bp = Ap^-1 mod P */
+    MBEDTLS_MPI_CHK(mbedtls_mpi_random(&Ap, 1, &ctx->P, f_rng, p_rng));
+    MBEDTLS_MPI_CHK(mbedtls_mpi_gcd_modinv_odd(NULL, &Bp, &Ap, &ctx->P));
+
+    /* Generate Ap in [1, Q) and compute Bq = Aq^-1 mod P */
```
Comment (davidhorstmann-arm) [inline library/rsa.c]: Typo:
```suggestion
    /* Generate Aq in [1, Q) and compute Bq = Aq^-1 mod Q */
```

File: library/rsa.c [hunk 6]
```diff
@@ -1327,6 +1328,31 @@ static int rsa_gen_rand_with_inverse(const mbedtls_rsa_context *ctx,
     mbedtls_mpi_free(&G);
 
     return ret;
+#else
+    int ret;
+    mbedtls_mpi Ap, Aq, Bp, Bq;
+
+    mbedtls_mpi_init(&Ap); mbedtls_mpi_init(&Aq);
+    mbedtls_mpi_init(&Bp); mbedtls_mpi_init(&Bq);
+
```
Comment (davidhorstmann-arm) [inline library/rsa.c:1349]: It would be good to have some explanation here about what is going on and why it works (or a link to an external source).

Maybe something like:

> Instead of generating A, B = A^-1 (mod N) directly, generate one A, B pair (mod P) and one pair (mod Q) and use Chinese Remainder Theorem to construct an A and B from those.

It would also help to know why this works. Specifically:
* Given that A ≡ Aq (mod Q) and A ≡ Ap (mod P), why does it follow that A^-1 ≡ Aq^-1 (mod Q) and A^-1 ≡ Ap^-1 (mod P) (i.e. why are the residues of the inverse the same as the inverses of the residues?) As a non-mathematician, this is not clear and it would be good to have some explanation or a link to somewhere to read more.
* How do we know that reconstructing a pair like this is the right kind of random? Having thought about it for a while I think that because we're choosing Ap and Aq uniformly from the ranges [1, P) and [1, Q), their cartesian product (Ap, Aq) is equivalent to a uniform random number in the range [1, N), which makes sense. However, it would be helpful to have an explanation just to make it blindingly obvious (pardon the pun).

File: library/rsa.c (hunk 4 above)
Comment (mpg) [reply library/rsa.c]: Good point. In addition to the readability issue inside the function, having to warn that it modifies one of its input parameters was not great, even for a static function .

File: library/rsa.c (hunk 6 above)
Comment (mpg) [reply library/rsa.c:1349]: Fair point, I've added a comment starting with your suggestion and expanding on it. I've decided to include the proper maths keywords (ring isomorphism) because that can be looked up, but of course expanded on their meaning :) Hope it's not confusing. Please let me know what you think.

**Comment by mpg** [comment]
> Given the mathematical and potentially confusing nature of this part of the code, I am treating them as blockers, I'm afraid.

Fully agreed. Thanks for your careful review!
