### PR TITLE
Fix issues in ssl_tls.c

### LINKED ISSUE #2717: Strange sizeof
https://github.com/ARMmbed/mbedtls/blob/66b7edb10865809a972362ce362c62820075ade3/library/ssl_tls.c#L6897-L6898
Since `MBEDTLS_SSL_PEER_CERT_DIGEST_DFL_LEN` is defined as a number, `sizeof` operator should be an error.

### LINKED ISSUE #2800: Unused variable warning in VS 2019
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_tls.c#L122
When `MBEDTLS_SSL_PROTO_DTLS` is undefined, this declaration generates an _unused variable_ warning.

The simplest fix could be to make the declaration local in the block where the variable was used, which would be directly before this line:
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_tls.c#L139

### LINKED ISSUE #2801: Repetitive assignment
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_tls.c#L6208-L6218
`ssl->in_msg` is assigned twice, and the first value was never used.

### PR DESCRIPTION
**Pull request by irwir**
## Description
Fix issues:
Resolve #2717 - remove erroneous `sizeof` (the operator was applied to constant integer number)
Resolve #2800 - move declaration to avoid unused variable warning in case `MBEDTLS_SSL_PROTO_DTLS` was undefined
Resolve #2801 - remove repetitive assignment to `ssl->in_msg` (the first value was never used)
Additionally, `mbedtls_ssl_send_fatal_handshake_failure` was overcomplicated and could be written in one line.

## Status
**READY**

## Requires Backporting
NO  
Which branch?
development

## Migrations
NO

Edit Ron: Add the "Resolve" magic word to automatically close the issues once merged

### CODE REVIEW

**Comment by irwir** [comment]
Two tests failed, and there is no way to see the error.
If `Details` were clicked, the browser always times out.
That behaviour appeared a long time ago. Should it be fixed, or these checks could be disregarded?

**Comment by RonEld** [comment]
CI failed in the following test, on both CI jobs :
~~~
Session resume using cache, DTLS: session copy ......................... FAIL
  ! bad client exit code (expected 0, got 1)
  ! outputs saved to o-XXX-179.log
~~~
for 
~~~
******************************************************************
* test_no_renegotiation: test: !MBEDTLS_SSL_RENEGOTIATION - ssl-opt.sh (ASan build) 
* Sat Sep 21 15:16:30 UTC 2019
******************************************************************
~~~

**Comment by irwir** [comment]
Thanks a lot, @RonEld 
Is it possible to point out which one of the changes causes failure?

**Comment by RonEld** [comment]
@irwir I have tried to reproduce this on my machine, unfortuantely it didn't reproduce.
Perhaps this is a flaky test in the CI which I am not aware of. @Patater Are you aware of such test?

**Comment by irwir** [comment]
@RonEld, thanks again.
Unreliable test deems quite possible.
Things are even worse in crypto repository; currently all open PRs failed to pass.

> I would prefer the commit message to explain more the changes, and even split it to separate commits for every fix.

Description was expanded slightly. For the other point, this PR modifies one file only, and overall amount of changes is small.
Is it really necessary to split this commit into several one-liners?

File: library/ssl_tls.c [hunk 1]
```diff
@@ -6413,7 +6414,7 @@ static int ssl_get_next_record( mbedtls_ssl_context *ssl )
 #if defined(MBEDTLS_SSL_DTLS_CONNECTION_ID)
     ssl->in_len = ssl->in_cid + rec.cid_len;
 #endif /* MBEDTLS_SSL_DTLS_CONNECTION_ID */
-    ssl->in_iv  = ssl->in_msg = ssl->in_len + 2;
+    ssl->in_iv = ssl->in_len + 2;
```
Comment (k-stachowiak) [inline library/ssl_tls.c]: There is a pattern of aligning the assignments in this function. If you rework the PR, please consider keeping the extra space before the assignment operator, so that it is aligned with the previous assignment.

**Comment by RonEld** [comment]
@irwir 

>Description was expanded slightly. 

Have you updated the PR with the expansion? I can't find it

**Comment by irwir** [comment]
@RonEld 

> Have you updated the PR with the expansion? I can't find it

Description of the PR was edited.
Did you mean to change the commit message?

**Comment by RonEld** [comment]
@irwir 
>Description of the PR was edited, not the commit message.

I apologize for not being clear. I was referring to edit the commit message, to better reflect the changes. If one would like to look at the history, for investigating issues, the commit message is not informative.

**Comment by irwir** [comment]
@RonEld, @k-stachowiak 
As you suggested, the commit was splitted into four; assignment operator alignmented.
Locally the module compiles fine in VS 2019, and the CI check unsurprisingly fails.

File: library/ssl_tls.c [hunk 2]
```diff
@@ -6567,16 +6568,9 @@ int mbedtls_ssl_handle_message_type( mbedtls_ssl_context *ssl )
...
-                    MBEDTLS_SSL_ALERT_LEVEL_FATAL,
-                    MBEDTLS_SSL_ALERT_MSG_HANDSHAKE_FAILURE ) ) != 0 )
-    {
-        return( ret );
-    }
-
-    return( 0 );
+    return mbedtls_ssl_send_alert_message( ssl,
+               MBEDTLS_SSL_ALERT_LEVEL_FATAL,
+               MBEDTLS_SSL_ALERT_MSG_HANDSHAKE_FAILURE );
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c]: Style:
```
    return( mbedtls_ssl_send_alert_message( ssl,
￼                 MBEDTLS_SSL_ALERT_LEVEL_FATAL,
￼                 MBEDTLS_SSL_ALERT_MSG_HANDSHAKE_FAILURE ) );
```

**Comment by gilles-peskine-arm** [comment]
CI is ok — all the tests passed (except for a spurious ABI incompatibility report on -head because this PR uses a slightly older crypto submodule), but for some reason the pass status of the -merge job isn't displayed on Github.

File: library/ssl_tls.c (hunk 2 above)
Comment (irwir) [reply library/ssl_tls.c]: Thanks for reviewing.
Function arguments were re-aligned.
Change log had no lines for the next version, so I had to create 2.19.2 header for the suggested bugfix enties.

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: Could you please add parentheses around the return value? i.e. `return( mbedtls_xxx( ) );`
