### PR TITLE
Fix build failure on gcc-11

### LINKED ISSUE #3782: mbedtls fails on build on gcc-11: ssl_tls.c:1724:41: error: argument 2 of type 'unsigned char[36]' with mismatched bound [-Werror=array-parameter=]
On (yet unreleased) gcc-11 mbedtls fails build due to new diagnstics:

```
[ 16%] Building C object library/CMakeFiles/mbedtls.dir/ssl_tls.c.o
cd /home/slyfox/dev/git/mbedtls/b/library && /usr/x86_64-pc-linux-gnu/gcc-bin/11.0.0/gcc  -I/home/slyfox/dev/git/mbedtls/include -I/home/slyfox/dev/git/mbedtls/library -Wall -Wextra -Wwrite-strings -Wvla -Wlogical-op -Wshadow -Wformat-signedness -Werror -Wmissing-declarations -Wmissing-prototypes -o CMakeFiles/mbedtls.dir/ssl_tls.c.o -c /home/slyfox/dev/git/mbedtls/library/ssl_tls.c
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:1724:41: error: argument 2 of type 'unsigned char[36]' with mismatched bound [-Werror=array-parameter=]
 1724 |                           unsigned char hash[36],
      |                           ~~~~~~~~~~~~~~^~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:684:63: note: previously declared as 'unsigned char *'
  684 | static void ssl_calc_verify_tls( const mbedtls_ssl_context *, unsigned char *, size_t * );
      |                                                               ^~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:1756:48: error: argument 2 of type 'unsigned char[32]' with mismatched bound [-Werror=array-parameter=]
 1756 |                                  unsigned char hash[32],
      |                                  ~~~~~~~~~~~~~~^~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:691:69: note: previously declared as 'unsigned char *'
  691 | static void ssl_calc_verify_tls_sha256( const mbedtls_ssl_context *,unsigned char *, size_t * );
      |                                                                     ^~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:1805:48: error: argument 2 of type 'unsigned char[48]' with mismatched bound [-Werror=array-parameter=]
 1805 |                                  unsigned char hash[48],
      |                                  ~~~~~~~~~~~~~~^~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:697:70: note: previously declared as 'unsigned char *'
  697 | static void ssl_calc_verify_tls_sha384( const mbedtls_ssl_context *, unsigned char *, size_t * );
      |                                                                      ^~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c: In function 'ssl_calc_verify_tls_sha384':
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:1839:5: error: 'mbedtls_sha512_finish_ret' accessing 64 bytes in a region of size 48 [-Werror=stringop-overflow=]
 1839 |     mbedtls_sha512_finish_ret( &sha512, hash );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:1839:5: note: referencing argument 2 of type 'unsigned char *'
In file included from /home/slyfox/dev/git/mbedtls/include/mbedtls/ssl_internal.h:51,
                 from /home/slyfox/dev/git/mbedtls/library/ssl_tls.c:41:
/home/slyfox/dev/git/mbedtls/include/mbedtls/sha512.h:145:5: note: in a call to function 'mbedtls_sha512_finish_ret'
  145 | int mbedtls_sha512_finish_ret( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c: In function 'ssl_calc_finished_tls_sha384':
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:3260:5: error: 'mbedtls_sha512_finish_ret' accessing 64 bytes in a region of size 48 [-Werror=stringop-overflow=]
 3260 |     mbedtls_sha512_finish_ret( &sha512, padbuf );
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/slyfox/dev/git/mbedtls/library/ssl_tls.c:3260:5: note: referencing argument 2 of type 'unsigned char *'
In file included from /home/slyfox/dev/git/mbedtls/include/mbedtls/ssl_internal.h:51,
                 from /home/slyfox/dev/git/mbedtls/library/ssl_tls.c:41:
/home/slyfox/dev/git/mbedtls/include/mbedtls/sha512.h:145:5: note: in a call to function 'mbedtls_sha512_finish_ret'
  145 | int mbedtls_sha512_finish_ret( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by rodrigo-dc**
Function prototypes changed to use array parameters instead of
pointers.

Signed-off-by: Rodrigo Dias Corrêa <rodrigo@correas.us>

## Description
Fixes #3782

## Status
**READY**

## Requires Backporting
I don't know.

## Migrations
NO

### CODE REVIEW

File: library/ssl_tls.c [hunk 1]
```diff
@@ -681,20 +681,20 @@ static void ssl_calc_finished_ssl( mbedtls_ssl_context *, unsigned char *, int )
 #endif
 
 #if defined(MBEDTLS_SSL_PROTO_TLS1) || defined(MBEDTLS_SSL_PROTO_TLS1_1)
-static void ssl_calc_verify_tls( const mbedtls_ssl_context *, unsigned char *, size_t * );
+static void ssl_calc_verify_tls( const mbedtls_ssl_context *, unsigned char [36], size_t * );
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:684]: Since these functions are assigned to
```
void (*calc_verify)(const mbedtls_ssl_context *, unsigned char *, size_t *);
```
from `struct mbedtls_ssl_handshake_params`, I think the prototypes here should have a pointer, not an array. Since an array type is purely indicative on a function parameter, there is no real loss in not declaring the intended buffer size.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Please add a changelog entry file in `ChangeLog.d` indicating that this fixes the build with GCC 11 and referencing #3782.

File: library/ssl_tls.c (hunk 1 above)
Comment (rodrigo-dc) [reply library/ssl_tls.c]: These `ssl_calc_verify_*` functions now use pointers in the prototypes **and** in the function definitions, because I can't mix them (pointers and arrays for the same function).
A few considerations about my latest commits:
* I kept the array parameter for the other functions because I didn't want to change the prototypes in the public headers.
* I needed to make more changes because I found other build errors switching from make to cmake.
* The only warning left is the one related to the implicit declaration of `memset`, but I saw you fixed that in #3867.

File: library/ssl_tls.c [hunk 2]
```diff
@@ -3203,7 +3203,7 @@ static void ssl_calc_finished_tls_sha384(
 {
     int len = 12;
     const char *sender;
-    unsigned char padbuf[48];
+    unsigned char padbuf[64];
```
Comment (gilles-peskine-arm) [inline library/ssl_tls.c:3206]: 16 bytes isn't much, but it would be better to save them. This is one of those cases where we know better than the compiler. Could we pacify gcc with a cast (with a comment for the sake of humans)?

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
Thanks. I'm happy with the PR now except that I'd rather avoid wasting stack space for the sake of a compiler warning.

**Comment by gilles-peskine-arm** [comment]
LTS branches should work under newer compilers too, so once we agree on the approach, this will need backports to `mbedtls-2.16` and `mbedtls-2.7`.

File: library/ssl_tls.c (hunk 2 above)
Comment (rodrigo-dc) [reply library/ssl_tls.c:3205]: It's hard do pacify GCC on this one.
1. I'm not allowed to cast to array types:
```c
mbedtls_sha512_finish_ret( &sha512, (unsigned char[64])padbuf );
```
Results in
`error: cast specifies array type`

2. Casting to a pointer triggers another warning (treated as error):
```c
mbedtls_sha512_finish_ret( &sha512, (unsigned char*)padbuf );
```
`‘mbedtls_sha512_finish_ret’ accessing 64 bytes in a region of size 48`.

---

I understand we have a few options:
1. Leave it as it is, and waste 16 bytes;
2. Change `mbedtls_sha512_finish_ret` to accept a pointer (loosing the benefits of "conformant arrays"). By the way, this function is marked for internal use only.
3. Disable a warning (I don't like this one);
4. Find another way to cast `padbuf`.

Any ideas?

Comment (gilles-peskine-arm) [reply library/ssl_tls.c:3205]: > this function is marked for internal use only.

Oh, that's an editorial mistake. This sentence was edited into the description of the wrong function in 27ff120a6121528de9f9a726dfd80a209ee05a1a. I'll make a PR to fix that.

Comment (gilles-peskine-arm) [reply library/ssl_tls.c:3205]: > Change `mbedtls_sha512_finish_ret` to accept a pointer

I'm not sure if that's acceptable. According to the C standard, a pointer and an array are equivalent in the declaration of a function parameter. But according to popular compilers, they aren't (which is why we're having this discussion).

Comment (gilles-peskine-arm) [reply library/ssl_tls.c:3205]: It's ugly, but how about casting the function?

Comment (rodrigo-dc) [reply library/ssl_tls.c]: > It's ugly, but how about casting the function?

Maybe. Please, take a look --> d596ca8

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: So casting to `int (*)(mbedtls_sha512_context*, unsigned char[48])` and not silences the warning? Wouldn't casting to `int (*)(mbedtls_sha512_context*, unsigned char*)` be more robust in case GCC's analysis starts going slightly deeper (which could happen due to an optimization flag)?

Comment (rodrigo-dc) [reply library/ssl_tls.c]: It would be more generic, at least. I've just made this change.
We are not changing `mbedtls_sha512_finish_ret()` because it's part of the public API, right? Because I feel like the use of array parameters is not worth the trouble.
Is there an overall guideline for new public functions in this project (regarding array parameters)?

Comment (gilles-peskine-arm) [reply library/ssl_tls.c]: Thanks, that's not ideal but I guess it's the best possible.

It hadn't been an issue before, but I think we'll make a new guideline to not use array parameters, and we'll change the existing ones to pointers in Mbed TLS 3.0.

**Review by gilles-peskine-arm — APPROVED** [review]
Looks good to me.

This needs to be backported to 2.16 and 2.7 (where applicable). Please wait for a second approval on this PR.

**Review by chris-jones-arm — APPROVED** [review]
Looks good to me. As already mentioned, this just needs backports and then we can merge.

**Comment by rodrigo-dc** [comment]
> Looks good to me. As already mentioned, this just needs backports and then we can merge.

Ok. Backported: #3925 and #3926.
